import test from "node:test";
import assert from "node:assert/strict";
import express from "express";
import { Readable } from "node:stream";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import type { AddressInfo } from "node:net";
import { YouTubeAdapter, LinkedInAdapter, InstagramAdapter, type AdapterContext, type ProviderResponse, type ProviderTransport } from "../src/provider-adapters.js";
import type { PlatformConnection, PublicationIntent, PublicationJob } from "../src/publication-types.js";
import { emptyPublication } from "../src/publication-types.js";
import { LocalPublicationStorage, type PublicationStorage } from "../src/publication-storage.js";
import { approvalAllowsEffect, claimPublicationJob, createPublicationScheduler } from "../src/publication-runner.js";
import { StorageConflictError } from "../src/storage-types.js";
import { buildAuthorizedConnection, discover, hasRequiredScopes, oauthCallbackRouter, parseGrantedScopes } from "../src/publication-routes.js";
import { validStorageRange } from "../src/supabase-storage.js";
import { settings } from "../src/settings.js";

settings.metaGraphApiVersion="v24.0";

function response(status:number,json:unknown={},headers:Record<string,string>={}):ProviderResponse{return{status,ok:status>=200&&status<300,headers:new Headers(headers),body:JSON.stringify(json),json:<T>()=>json as T};}
function baseJob(platform:PublicationJob["platform"]="youtube_shorts"):PublicationJob{return{id:"62000000-0000-4000-8000-000000000001",ownerId:"owner",runId:"run",intentId:"intent",platform,state:"queued",checkpoint:"prepared",revision:0,attemptCount:0,retrySafety:"automatic",allowedAction:"none",backoffAttempt:0,evidence:{},attempts:[],createdAt:"fixed",updatedAt:"fixed"};}
function intent(platform:PublicationIntent["platform"]="youtube_shorts"):PublicationIntent{return{id:"intent",ownerId:"owner",runId:"run",batchId:"batch",approvalId:"approval",approvalEpoch:0,approvalFingerprint:"a".repeat(64),platform,connectionId:"connection",target:{platform,connectionId:"connection",targetId:platform==="linkedin"?"urn:li:person:123":"channel",targetType:platform==="linkedin"?"member":"channel",targetLabel:"target",capabilityRevision:1,revision:1,updatedAt:"fixed"},payload:platform==="linkedin"?{title:"Internal title",commentary:"Approved commentary",hashtags:["#one","#two"],accessibilityNotes:"not posted",postingNotes:"not posted"}:{title:"Approved title",description:"Approved description",tags:["one","two"]},payloadHash:"b".repeat(64),youtubePrivacy:"private",idempotencyFingerprint:"c".repeat(64),provenance:"live",createdAt:"fixed",status:"started"};}
function context(jobSecret?:Record<string,unknown>):AdapterContext{return{connection:{id:"connection",ownerId:"owner",provider:"youtube",accountId:"account",accountLabel:"Account",status:"connected",grantedScopes:[],targets:[],revision:1,createdAt:"fixed",updatedAt:"fixed",provenance:"live"},token:"TOKEN",jobSecret,getMediaMetadata:async()=>({byteSize:10,sha256:"a".repeat(64)}),openMedia:async range=>({stream:Readable.from(Buffer.alloc(range?range.end-range.start+1:10)),byteSize:range?range.end-range.start+1:10,sha256:"a".repeat(64)}),beforeEffect:async()=>{}};}

test("YouTube injected transport proves authenticated resumable creation, 308 resume, completion and processing shapes",async()=>{const calls:{url:string;init?:RequestInit;options?:{allowAuthorization?:boolean}}[]=[],queue=[response(200,{}, {location:"https://www.googleapis.com/upload/youtube/session"}),response(308,{}, {range:"bytes=0-4"}),response(201,{id:"video-1"}),response(200,{items:[{processingDetails:{processingStatus:"processing"},status:{privacyStatus:"private"}}]}),response(200,{items:[{processingDetails:{processingStatus:"succeeded"},status:{privacyStatus:"private"}}]})],transport:ProviderTransport=async(url,init,options)=>{calls.push({url,init,options});return queue.shift()!;},adapter=new YouTubeAdapter(transport);let job=baseJob(),secret:Record<string,unknown>|undefined,out=await adapter.advance(job,intent(),context());assert.equal(out.state,"upload_session_created");secret=out.jobSecret;assert.equal(new Headers(calls[0].init?.headers).get("x-upload-content-length"),"10");const creationBody=JSON.parse(String(calls[0].init?.body));assert.deepEqual(Object.keys(creationBody.snippet).sort(),["description","tags","title"]);job={...job,state:out.state,evidence:{...job.evidence,...out.evidence}};out=await adapter.advance(job,intent(),context(secret));assert.equal(out.state,"uploading");assert.equal(new Headers(calls[1].init?.headers).get("authorization"),"Bearer TOKEN");assert.equal(new Headers(calls[1].init?.headers).get("content-range"),"bytes 0-9/10");secret=out.jobSecret;job={...job,state:out.state,evidence:{...job.evidence,...out.evidence}};out=await adapter.advance(job,intent(),context(secret));assert.equal(out.evidence?.videoId,"video-1");assert.equal(new Headers(calls[2].init?.headers).get("content-range"),"bytes 5-9/10");job={...job,state:out.state,evidence:{...job.evidence,...out.evidence}};out=await adapter.advance(job,intent(),context(secret));assert.equal(out.state,"provider_processing");assert.ok(out.retryAfterMs);job={...job,state:out.state,evidence:{...job.evidence,...out.evidence}};out=await adapter.advance(job,intent(),context(secret));assert.equal(out.state,"externally_published");assert.ok(calls.every(call=>new Headers(call.init?.headers).get("authorization")==="Bearer TOKEN"));});

test("YouTube status-query reconciliation authenticates the resumable session without opening media",async()=>{let opened=0;const calls:RequestInit[]=[],adapter=new YouTubeAdapter(async(_url,init)=>{calls.push(init??{});return response(308,{}, {range:"bytes=0-4"});}),ctx={...context({uploadUrl:"https://www.googleapis.com/upload/youtube/session",offset:0}),openMedia:async()=>{opened++;return context().openMedia();}},job={...baseJob(),state:"unknown" as const,allowedAction:"reconcile" as const,retrySafety:"reconcile_only" as const};const out=await adapter.reconcile(job,intent(),ctx);assert.equal(out.state,"uploading");assert.equal(opened,0);assert.equal(new Headers(calls[0].headers).get("authorization"),"Bearer TOKEN");assert.equal(new Headers(calls[0].headers).get("content-range"),"bytes */10");});
test("YouTube never forwards its bearer token to another allowlisted provider host",async()=>{let calls=0;const adapter=new YouTubeAdapter(async()=>{calls++;return response(200);}),job={...baseJob(),state:"uploading" as const};await assert.rejects(()=>adapter.advance(job,intent(),context({uploadUrl:"https://api.linkedin.com/upload/session",offset:0})),/host is invalid/);assert.equal(calls,0);});
test("an expired pre-checkpoint YouTube claim never creates a second session",async()=>{let calls=0;const adapter=new YouTubeAdapter(async()=>{calls++;return response(200);}),out=await adapter.reconcile(baseJob(),intent(),context());assert.equal(out.state,"unknown");assert.equal(out.allowedAction,"inspect");assert.equal(calls,0);});
test("approval supersession blocks every later irreversible YouTube and LinkedIn request",async()=>{let calls=0;const transport:ProviderTransport=async()=>{calls++;return response(200);},blocked={...context(),beforeEffect:async(kind:"write"|"read")=>{if(kind==="write")throw new Error("superseded");}},youtube=new YouTubeAdapter(transport),linkedin=new LinkedInAdapter(transport);await assert.rejects(()=>youtube.advance(baseJob(),intent(),blocked),/superseded/);await assert.rejects(()=>youtube.advance({...baseJob(),state:"upload_session_created"},intent(),{...blocked,jobSecret:{uploadUrl:"https://www.googleapis.com/upload/youtube/session",offset:0}}),/superseded/);await assert.rejects(()=>linkedin.advance(baseJob("linkedin"),intent("linkedin"),blocked),/superseded/);await assert.rejects(()=>linkedin.advance({...baseJob("linkedin"),state:"upload_session_created",evidence:{videoUrn:"urn:li:video:1"}},intent("linkedin"),{...blocked,jobSecret:{uploadInstructions:[{firstByte:0,lastByte:9,uploadUrl:"https://api.linkedin.com/upload/one"}],uploaded:[],uploadToken:"token"}}),/superseded/);await assert.rejects(()=>linkedin.advance({...baseJob("linkedin"),state:"upload_complete",evidence:{videoUrn:"urn:li:video:1"}},intent("linkedin"),{...blocked,jobSecret:{uploadInstructions:[{firstByte:0,lastByte:9,uploadUrl:"https://api.linkedin.com/upload/one"}],uploaded:[{firstByte:0,lastByte:9,etag:"part"}],uploadToken:"token"}}),/superseded/);await assert.rejects(()=>linkedin.advance({...baseJob("linkedin"),state:"creation_pending",evidence:{videoUrn:"urn:li:video:1"}},intent("linkedin"),blocked),/superseded/);assert.equal(calls,0);});

test("LinkedIn accepts the documented empty upload token and share result ID",async()=>{const calls:{url:string;init?:RequestInit}[]=[],queue=[response(200,{value:{video:"urn:li:video:123",uploadToken:"",uploadInstructions:[{firstByte:0,lastByte:4,uploadUrl:"https://api.linkedin.com/upload/one"},{firstByte:5,lastByte:9,uploadUrl:"https://api.linkedin.com/upload/two"}]}}),response(200,{}, {etag:"part-one"}),response(200,{}, {etag:"part-two"}),response(200),response(200,{status:"AVAILABLE"}),response(201,{}, {"x-restli-id":"urn:li:share:123"})],adapter=new LinkedInAdapter(async(url,init)=>{calls.push({url,init});return queue.shift()!;});let job=baseJob("linkedin"),secret:Record<string,unknown>|undefined,out=await adapter.advance(job,intent("linkedin"),context());secret=out.jobSecret;job={...job,state:out.state,evidence:{...job.evidence,...out.evidence}};out=await adapter.advance(job,intent("linkedin"),context(secret));secret=out.jobSecret;job={...job,state:out.state,evidence:{...job.evidence,...out.evidence}};out=await adapter.advance(job,intent("linkedin"),context(secret));secret=out.jobSecret;job={...job,state:out.state,evidence:{...job.evidence,...out.evidence}};out=await adapter.advance(job,intent("linkedin"),context(secret));const finalize=JSON.parse(String(calls[3].init?.body)).finalizeUploadRequest;assert.deepEqual(finalize.uploadedPartIds,["part-one","part-two"]);assert.equal(finalize.uploadToken,"");job={...job,state:out.state,evidence:{...job.evidence,...out.evidence}};out=await adapter.advance(job,intent("linkedin"),context(secret));job={...job,state:out.state,evidence:{...job.evidence,...out.evidence}};out=await adapter.advance(job,intent("linkedin"),context(secret));const post=JSON.parse(String(calls[5].init?.body));assert.equal(post.commentary,"Approved commentary\n\n#one #two");assert.equal(post.title,undefined);assert.equal(out.evidence?.postId,"urn:li:share:123");assert.equal(out.evidence?.resultUrl,"https://www.linkedin.com/feed/update/urn%3Ali%3Ashare%3A123");});

test("LinkedIn preserves documented ugcPost IDs and rejects missing or non-string upload tokens",async()=>{for(const invalid of [{},{uploadToken:7}]){const adapter=new LinkedInAdapter(async()=>response(200,{value:{video:"urn:li:video:123",uploadInstructions:[{firstByte:0,lastByte:9,uploadUrl:"https://api.linkedin.com/upload/one"}],...invalid}})),out=await adapter.advance(baseJob("linkedin"),intent("linkedin"),context());assert.equal(out.checkpoint,"initialize_response_invalid");}const adapter=new LinkedInAdapter(async()=>response(201,{}, {"x-restli-id":"urn:li:ugcPost:456"})),out=await adapter.advance({...baseJob("linkedin"),state:"creation_pending",evidence:{videoUrn:"urn:li:video:123"}},intent("linkedin"),context());assert.equal(out.evidence?.postId,"urn:li:ugcPost:456");assert.equal(out.evidence?.resultUrl,"https://www.linkedin.com/feed/update/urn%3Ali%3AugcPost%3A456");});

test("LinkedIn refuses finalization after a successful range without ETag",async()=>{const queue=[response(200,{value:{video:"urn:li:video:123",uploadToken:"token",uploadInstructions:[{firstByte:0,lastByte:9,uploadUrl:"https://api.linkedin.com/upload/one"}]}}),response(200)],adapter=new LinkedInAdapter(async()=>queue.shift()!),job=baseJob("linkedin"),first=await adapter.advance(job,intent("linkedin"),context()),second=await adapter.advance({...job,state:first.state,evidence:{...first.evidence}},intent("linkedin"),context(first.jobSecret));assert.equal(second.state,"needs_attention");assert.equal(second.checkpoint,"range_etag_missing");assert.equal(second.allowedAction,"inspect");});

test("safe action classification keeps ambiguous writes reconcile-only and retryable failures user-safe",async()=>{const instagram=new InstagramAdapter(async()=>response(503)),instagramFailure=await instagram.advance(baseJob("instagram_reels"),intent("instagram_reels"),context());assert.equal(instagramFailure.allowedAction,"retry");assert.equal(instagramFailure.retrySafety,"user_safe");const youtube=new YouTubeAdapter(async()=>response(503)),failed=await youtube.advance(baseJob(),intent(),context());assert.equal(failed.allowedAction,"retry");assert.equal(failed.retrySafety,"user_safe");const ambiguous=new YouTubeAdapter(async()=>response(500)),upload=await ambiguous.advance({...baseJob(),state:"uploading"},intent(),context({uploadUrl:"https://www.googleapis.com/upload/youtube/session",offset:0}));assert.equal(upload.allowedAction,"reconcile");});

test("Instagram follows the documented resumable binary upload, status and publish protocol",async()=>{const calls:{url:string;init?:RequestInit}[]=[],queue=[response(200,{id:"container-1",uri:"https://rupload.facebook.com/ig-api-upload/session"}),response(200,{}),response(200,{id:"container-1",status_code:"FINISHED"}),response(200,{id:"media-1"}),response(200,{id:"media-1",permalink:"https://www.instagram.com/reel/abc/"})],adapter=new InstagramAdapter(async(url,init)=>{calls.push({url,init});return queue.shift()!;}),igIntent={...intent("instagram_reels"),target:{...intent("instagram_reels").target,targetId:"ig-user-1",targetType:"instagram_account" as const},payload:{caption:"Approved caption",hashtags:["#one","#two"],altText:"Alt",postingNotes:"Notes"}};let job=baseJob("instagram_reels"),secret:Record<string,unknown>|undefined,out=await adapter.advance(job,igIntent,context());assert.equal(out.state,"upload_session_created");assert.equal(out.evidence?.containerId,"container-1");assert.match(String(calls[0].init?.body),/upload_type=resumable/);assert.match(String(calls[0].init?.body),/caption=Approved\+caption/);secret=out.jobSecret;job={...job,state:out.state,evidence:{...job.evidence,...out.evidence}};out=await adapter.advance(job,igIntent,context(secret));assert.equal(out.state,"upload_complete");assert.equal(new Headers(calls[1].init?.headers).get("authorization"),"OAuth TOKEN");assert.equal(new Headers(calls[1].init?.headers).get("file_size"),"10");job={...job,state:out.state,evidence:{...job.evidence,...out.evidence}};out=await adapter.advance(job,igIntent,context(secret));assert.equal(out.state,"creation_pending");job={...job,state:out.state,evidence:{...job.evidence,...out.evidence}};out=await adapter.advance(job,igIntent,context(secret));assert.equal(out.state,"externally_published");assert.equal(out.evidence?.mediaId,"media-1");assert.equal(out.evidence?.resultUrl,"https://www.instagram.com/reel/abc/");assert.match(calls[3].url,/media_publish/);});

test("Instagram rejects an untrusted saved upload host before opening media",async()=>{let calls=0,opened=0;const adapter=new InstagramAdapter(async()=>{calls++;return response(200);}),ctx={...context({uploadUrl:"https://api.linkedin.com/upload",containerId:"container-1"}),openMedia:async()=>{opened++;return context().openMedia();}},job={...baseJob("instagram_reels"),state:"upload_session_created" as const,evidence:{containerId:"container-1"}};await assert.rejects(()=>adapter.advance(job,intent("instagram_reels"),ctx),/host is invalid/);assert.equal(calls,0);assert.equal(opened,0);});

test("reconnect preserves the connection ID and missing scopes never become connected",()=>{const existing={...context().connection,provider:"youtube" as const,id:"same-id",revision:7,createdAt:"created",targets:[{id:"channel",type:"channel" as const,label:"Channel",eligible:true,capabilityRevision:1}]},missing=buildAuthorizedConnection("youtube","owner",{access_token:"secret"},existing.targets,"2026-10-02T00:00:00.000Z",existing);assert.equal(missing.id,"same-id");assert.equal(missing.revision,8);assert.equal(missing.status,"needs_attention");const granted=parseGrantedScopes({scope:"https://www.googleapis.com/auth/youtube.upload"}),connected=buildAuthorizedConnection("youtube","owner",{scope:granted.join(" ")},existing.targets,"2026-10-02T00:00:00.000Z",existing);assert.equal(hasRequiredScopes("youtube",granted),true);assert.equal(connected.status,"connected");});
test("live OAuth requests Meta Page publishing permissions and LinkedIn's real member-profile scope",async()=>{const { oauthConfig }=await import("../src/publication-routes.js"),instagram=oauthConfig("instagram"),linkedin=oauthConfig("linkedin");assert.equal(new URL(instagram.authorize).hostname,"www.facebook.com");assert.equal(new URL(instagram.token).hostname,"graph.facebook.com");assert.deepEqual(instagram.scopes,["business_management","pages_read_engagement","pages_show_list","instagram_basic","instagram_content_publish"]);assert.deepEqual(linkedin.scopes,["r_liteprofile","w_member_social"]);});
test("target discovery uses Page-linked Instagram accounts and LinkedIn /v2/me IDs",async()=>{let requested="";const instagram=await discover("instagram","TOKEN",async(url,init)=>{requested=url;assert.equal(new Headers(init?.headers).get("authorization"),"Bearer TOKEN");return response(200,{data:[{id:"page-1",name:"Page",instagram_business_account:{id:"ig-1",name:"Studio",username:"studio"}},{id:"page-2",name:"No Instagram"}]});});assert.match(requested,/graph\.facebook\.com\/v24\.0\/me\/accounts/);assert.deepEqual(instagram,[{id:"ig-1",type:"instagram_account",label:"@studio (Studio)",eligible:true,capabilityRevision:2}]);const linkedin=await discover("linkedin","TOKEN",async(url)=>{requested=url;return response(200,{id:"abc-123",localizedFirstName:"Ada",localizedLastName:"Lovelace"});});assert.equal(requested,"https://api.linkedin.com/v2/me");assert.deepEqual(linkedin,[{id:"urn:li:person:abc-123",type:"member",label:"Ada Lovelace",eligible:true,capabilityRevision:2}]);});

test("local claim-bound checkpoint commit rejects an old fence and preserves the newer secret",async()=>{const dir=await mkdtemp(`${tmpdir()}/vpo-step5c-fence-`),store=new LocalPublicationStorage(dir);await store.init();try{const aggregate=emptyPublication("owner","run"),job={...baseJob(),activeClaim:{id:"claim-new",fence:2,expiresAt:"2099-01-01T00:00:00.000Z"}},seed={...aggregate,jobs:[job]},saved=await store.putAggregate(seed,0),next=structuredClone(saved);next.jobs[0].state="uploading";delete next.jobs[0].activeClaim;const envelope={version:1 as const,keyId:"key",nonce:"nonce",tag:"tag",ciphertext:"cipher"};await store.commitJobCheckpoint(next,saved.revision,job.id,"claim-new",{ownerId:"owner",runId:"run",jobId:job.id,claimId:"claim-new",fence:2,envelope,updatedAt:"fixed"});const secret=await store.getJobSecret("owner",job.id);assert.equal(secret?.fence,2);await assert.rejects(()=>store.commitJobCheckpoint(next,saved.revision,job.id,"claim-old",{ownerId:"owner",runId:"run",jobId:job.id,claimId:"claim-old",fence:1,envelope,updatedAt:"old"}),/newer worker|changed/i);assert.equal((await store.getJobSecret("owner",job.id))?.fence,2);}finally{await store.close();await rm(dir,{recursive:true,force:true});}});

test("Supabase byte ranges require exact 206 Content-Range",()=>{assert.equal(validStorageRange(206,"bytes 5-9/10",5,9,10),true);assert.equal(validStorageRange(200,"bytes 5-9/10",5,9,10),false);assert.equal(validStorageRange(206,"bytes 0-9/10",5,9,10),false);});

test("OAuth callback failures are no-store, no-referrer, clear the cookie and use a sanitized 303",async()=>{const app=express();app.use(oauthCallbackRouter);const server=app.listen(0,"127.0.0.1");try{await new Promise<void>(resolve=>server.once("listening",resolve));const port=(server.address() as AddressInfo).port,response=await fetch(`http://127.0.0.1:${port}/oauth/youtube/callback?state=SECRET_STATE&code=SECRET_CODE`,{headers:{cookie:"vpo_oauth=SECRET_COOKIE"},redirect:"manual"});assert.equal(response.status,303);assert.equal(response.headers.get("cache-control"),"no-store");assert.equal(response.headers.get("referrer-policy"),"no-referrer");assert.match(response.headers.get("set-cookie")??"",/vpo_oauth=;/);assert.equal(response.headers.get("location"),"/?connection=failed");assert.doesNotMatch(await response.text(),/SECRET/);}finally{await new Promise<void>(resolve=>server.close(()=>resolve()));}});

test("forced CAS retry reuses one prepared claim ID, timestamp and event",async()=>{const aggregate={...emptyPublication("owner","run"),jobs:[baseJob()]},attempts:PublicationJob[][]=[],store={getAggregate:async()=>structuredClone(aggregate),putAggregate:async(next:ReturnType<typeof emptyPublication>)=>{attempts.push(structuredClone(next.jobs));if(attempts.length===1)throw new StorageConflictError("forced");return{...next,revision:1};}} as unknown as PublicationStorage,result=await claimPublicationJob("owner","run",aggregate.jobs[0].id,false,store);assert.equal(attempts.length,2);assert.equal(attempts[0][0].activeClaim?.id,attempts[1][0].activeClaim?.id);assert.equal(attempts[0][0].updatedAt,attempts[1][0].updatedAt);assert.equal(attempts[0][0].attempts[0].id,attempts[1][0].attempts[0].id);assert.equal(result.claimId,attempts[0][0].activeClaim?.id);});

class FakeClock{nowValue=0;sequence=0;tasks:{id:number;at:number;fn:()=>void;cancelled:boolean}[]=[];now=()=>this.nowValue;setTimer=(fn:()=>void,delay:number)=>{const item={id:++this.sequence,at:this.nowValue+delay,fn,cancelled:false};this.tasks.push(item);return item as unknown as ReturnType<typeof setTimeout>;};clearTimer=(timer:ReturnType<typeof setTimeout>)=>{(timer as unknown as {cancelled:boolean}).cancelled=true;};async advance(ms:number){this.nowValue+=ms;for(;;){const item=this.tasks.filter(v=>!v.cancelled&&v.at<=this.nowValue).sort((a,b)=>a.at-b.at||a.id-b.id)[0];if(!item)break;item.cancelled=true;item.fn();await new Promise(resolve=>setImmediate(resolve));}}}

test("runner scheduler automatically advances one TEST success through every checkpoint",async()=>{const clock=new FakeClock(),adapter=new (await import("../src/provider-adapters.js")).TestPublishingAdapter(),testIntent={...intent(),provenance:"test" as const},ctx={...context(),connection:{...context().connection,accountId:"simulated:success",provenance:"test" as const}},effects:string[]=[],job=baseJob();const scheduler=createPublicationScheduler(async()=>{effects.push(job.state);const out=await adapter.advance(job,testIntent,ctx);job.state=out.state;job.checkpoint=out.checkpoint;job.evidence={...job.evidence,...out.evidence};return out.reschedule?{at:new Date(clock.now()+Math.max(1,out.retryAfterMs??1)).toISOString()}:undefined;},clock as any);scheduler.schedule("owner","run",job.id);for(let count=0;count<8&&job.state!=="externally_published";count++)await clock.advance(30);assert.equal(job.state,"externally_published");assert.deepEqual(effects,["queued","upload_session_created","upload_complete","provider_processing","creation_pending"]);assert.equal(scheduler.pending(),0);});

test("runner scheduler waits for delayed processing and deduplicates schedule calls",async()=>{const clock=new FakeClock(),effects:number[]=[];let step=0;const scheduler=createPublicationScheduler(async()=>{effects.push(clock.now());step++;return step===1?{at:new Date(100).toISOString()}:undefined;},clock as any);scheduler.schedule("owner","run","job");scheduler.schedule("owner","run","job");await clock.advance(0);assert.deepEqual(effects,[0]);await clock.advance(99);assert.deepEqual(effects,[0]);await clock.advance(1);assert.deepEqual(effects,[0,100]);assert.equal(scheduler.pending(),0);});

test("runner supersession policy permits evidence reads but blocks remaining writes",async()=>{const youtube={...baseJob(),state:"upload_complete" as const,evidence:{videoId:"video-1"}},linkedinProcessing={...baseJob("linkedin"),state:"provider_processing" as const,evidence:{videoUrn:"urn:li:video:1"}},linkedinFinalize={...baseJob("linkedin"),state:"upload_complete" as const,evidence:{videoUrn:"urn:li:video:1"}},linkedinPost={...baseJob("linkedin"),state:"creation_pending" as const,evidence:{videoUrn:"urn:li:video:1"}};assert.equal(approvalAllowsEffect(youtube,false,"read"),true);assert.equal(approvalAllowsEffect(youtube,false,"write"),false);assert.equal(approvalAllowsEffect(linkedinProcessing,false,"read"),true);assert.equal(approvalAllowsEffect(linkedinFinalize,false,"write"),false);assert.equal(approvalAllowsEffect(linkedinPost,false,"write"),false);let youtubeCalls=0;const youtubeAdapter=new YouTubeAdapter(async()=>{youtubeCalls++;return response(200,{items:[{processingDetails:{processingStatus:"succeeded"},status:{privacyStatus:"private"}}]});}),guard=(job:PublicationJob)=>({...context(),beforeEffect:async(kind:"write"|"read")=>{if(!approvalAllowsEffect(job,false,kind))throw new Error("superseded");}});assert.equal((await youtubeAdapter.advance(youtube,intent(),guard(youtube))).state,"externally_published");assert.equal(youtubeCalls,1);let linkedinCalls=0;const linkedinAdapter=new LinkedInAdapter(async()=>{linkedinCalls++;return response(200,{status:"AVAILABLE"});});assert.equal((await linkedinAdapter.advance(linkedinProcessing,intent("linkedin"),guard(linkedinProcessing))).state,"creation_pending");await assert.rejects(()=>linkedinAdapter.advance(linkedinFinalize,intent("linkedin"),{...guard(linkedinFinalize),jobSecret:{uploadInstructions:[{firstByte:0,lastByte:9,uploadUrl:"https://api.linkedin.com/upload/one"}],uploaded:[{firstByte:0,lastByte:9,etag:"part"}],uploadToken:""}}),/superseded/);await assert.rejects(()=>linkedinAdapter.advance(linkedinPost,intent("linkedin"),guard(linkedinPost)),/superseded/);assert.equal(linkedinCalls,1);});
