import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { spawn, spawnSync, type ChildProcess } from "node:child_process";
import type { Run } from "../../frontend/lib/types.js";
import type { FinalMediaVersion, PackQuote, ReleaseApproval } from "../../frontend/lib/types.js";
import { activePack, applyApproval, applyMediaVersion, applyPackVersion, applyReopen, approvalMatchesActive, assertPackUserMutationIdle, calculateReadiness, ensureRelease, fingerprint, packInputReferences, preparePackVersion, prepareSupersession, readinessFingerprint, releaseReadView, RELEASE_POLICY_FINGERPRINT, storyboardLineage, validatePack } from "../src/release.js";
import { packContext, packFixture, packProvenance, packResponseJsonSchema, packSettingsFingerprint } from "../src/pack.js";
import { validateProbe } from "../src/media.js";
import { optimisticRunUpdate } from "../src/supabase-storage.js";
import { applyPackIntent, applyPackResume, preparePackIntent } from "../src/jobs.js";
import { approvedRun, userA, userB } from "./fixtures.js";

const sleep=(n:number)=>new Promise(r=>setTimeout(r,n));
test("live Pack generation supplies the complete structured response contract",()=>{const schema=packResponseJsonSchema as Record<string,any>;assert.deepEqual([...schema.required].sort(),["finalPrompt","negativePrompt","platforms","thumbnailText"]);const platforms=schema.properties.platforms;assert.deepEqual([...platforms.required].sort(),["instagram_reels","linkedin","youtube_shorts"]);assert.deepEqual([...platforms.properties.youtube_shorts.required].sort(),["accessibilityNotes","description","postingNotes","tags","title"]);assert.deepEqual([...platforms.properties.instagram_reels.required].sort(),["altText","caption","hashtags","postingNotes"]);assert.deepEqual([...platforms.properties.linkedin.required].sort(),["accessibilityNotes","commentary","hashtags","postingNotes","title"]);});
function currentQuote(run:Run,id:string,expiresAt="2999-01-01T00:00:00.000Z"):PackQuote{return{id,storyboardLineage:storyboardLineage(run)!,releaseRevision:ensureRelease(run).revision,inputHash:fingerprint(packContext(run)),amountUsd:0,expiresAt,settingsFingerprint:packSettingsFingerprint(),validationPolicyFingerprint:RELEASE_POLICY_FINGERPRINT,provenance:packProvenance(run)};}
test("Step 5B release candidate is versioned, media-probed, owner-scoped, approved, exported and reopened",async()=>{const dir=await mkdtemp(path.join(tmpdir(),"vpo-step5b-")),port=4106,base=`http://127.0.0.1:${port}/api`;let child:ChildProcess|undefined;try{const fixture=approvedRun(dir),lineage=storyboardLineage(fixture)!;assert.equal(lineage.length,64);await writeFile(path.join(dir,`run-${fixture.id}.json`),JSON.stringify(fixture));
  const video=path.join(dir,"valid.mp4"),made=spawnSync("ffmpeg",["-y","-f","lavfi","-i","color=c=black:s=720x1280:r=1:d=15","-f","lavfi","-i","anullsrc=r=44100:cl=stereo","-c:v","libx264","-pix_fmt","yuv420p","-c:a","aac","-shortest","-movflags","+faststart",video],{encoding:"utf8"});assert.equal(made.status,0,made.stderr);
  child=spawn(process.execPath,["dist/backend/src/server.js"],{cwd:process.cwd(),env:{...process.env,NODE_ENV:"test",PORT:String(port),TEST_MODE:"true",AUTH_MODE:"local",STORAGE_MODE:"local_json",STORAGE_LOCAL_PATH:dir,TEST_DELAY_MS:"5"},stdio:"pipe"});for(let i=0;i<100;i++){try{if((await fetch(`${base}/health`)).ok)break}catch{}await sleep(50)}
  const headers=(u:string,json=true)=>({Authorization:`Bearer test-user:${u}`,...(json?{"Content-Type":"application/json"}:{})});const json=async(u:string,route:string,body?:unknown,method=body?"POST":"GET")=>{const response=await fetch(base+route,{method,headers:headers(u),body:body?JSON.stringify(body):undefined});const data=await response.json();assert.ok(response.ok,JSON.stringify(data));return data};
  const quote=await json(userA,`/runs/${fixture.id}/pack-quotes`,{expectedStoryboardLineage:lineage});assert.equal(quote.amountUsd,0);await json(userA,`/runs/${fixture.id}/pack`,{quoteId:quote.id,expectedStoryboardLineage:lineage,expectedReleaseRevision:quote.releaseRevision});let run:any;for(let i=0;i<100;i++){run=await json(userA,`/runs/${fixture.id}`);if(!["queued","running"].includes(run.jobStatus))break;await sleep(20)}assert.equal(run.release.packVersions.length,1);assert.equal(run.aiCallLog.filter((c:any)=>c.task==="pack-generation").length,1);
  const content={...run.release.packVersions[0].content,thumbnailText:"Edited test"};const edited=await json(userA,`/runs/${fixture.id}/pack`,{content,expectedReleaseRevision:run.release.revision,expectedActivePackVersionId:run.release.activePackVersionId,changeSummary:"Explicit edit"},"PATCH");assert.equal(edited.release.packVersions.length,2);const stale=await fetch(`${base}/runs/${fixture.id}/pack`,{method:"PATCH",headers:headers(userA),body:JSON.stringify({content,expectedReleaseRevision:run.release.revision,expectedActivePackVersionId:run.release.activePackVersionId,changeSummary:"stale"})});assert.equal(stale.status,409);const restored=await json(userA,`/runs/${fixture.id}/pack/restore`,{sourcePackVersionId:edited.release.packVersions[0].id,expectedActivePackVersionId:edited.release.activePackVersionId,expectedReleaseRevision:edited.release.revision,changeSummary:"Restore v1 as new"});assert.equal(restored.release.packVersions.length,3);
  const bytes=await readFile(video);const upload=await fetch(`${base}/runs/${fixture.id}/final-media`,{method:"POST",headers:{...headers(userA,false),"Content-Type":"application/octet-stream","X-VPO-Filename":encodeURIComponent("course.mp4"),"X-VPO-Release-Revision":String(restored.release.revision),"X-VPO-Storyboard-Lineage":lineage,"X-VPO-Active-Media-Version":"none"},body:bytes});const uploadText=await upload.text();assert.equal(upload.status,201,uploadText);run=JSON.parse(uploadText);assert.equal(run.release.mediaVersions[0].probe.videoCodec,"h264");assert.equal(run.release.mediaVersions[0].probe.audioCodecs[0],"aac");
  const media=run.release.mediaVersions[0],preview=await fetch(`${base}/runs/${fixture.id}/final-media/${media.id}/content`,{headers:headers(userA,false)});assert.equal(preview.status,200);assert.equal(preview.headers.get("cache-control"),"private, no-store");assert.match(preview.headers.get("vary")??"",/Authorization/i);assert.ok((await preview.arrayBuffer()).byteLength>100);
  assert.equal((await fetch(`${base}/runs/${fixture.id}`,{headers:headers(userB,false)})).status,404,"User B cannot inspect User A's Pack/media through the run");assert.equal((await fetch(`${base}/runs/${fixture.id}/final-media/${media.id}/content`,{headers:headers(userB,false)})).status,404);assert.equal((await fetch(`${base}/runs/${fixture.id}/final-media/${media.id}/content?download=1`,{headers:headers(userB,false)})).status,404);assert.equal((await fetch(`${base}/runs/${fixture.id}/final-media`,{method:"POST",headers:{...headers(userB,false),"Content-Type":"application/octet-stream","X-VPO-Filename":encodeURIComponent("attack.mp4"),"X-VPO-Release-Revision":String(run.release.revision),"X-VPO-Storyboard-Lineage":lineage,"X-VPO-Active-Media-Version":"none"},body:bytes})).status,404);assert.equal((await fetch(`${base}/runs/${fixture.id}/pack`,{method:"PATCH",headers:headers(userB),body:JSON.stringify({content,expectedReleaseRevision:run.release.revision,expectedActivePackVersionId:run.release.activePackVersionId,changeSummary:"attack"})})).status,404);assert.equal((await fetch(`${base}/runs/${fixture.id}/pack/restore`,{method:"POST",headers:headers(userB),body:JSON.stringify({sourcePackVersionId:run.release.packVersions[0].id,expectedActivePackVersionId:run.release.activePackVersionId,expectedReleaseRevision:run.release.revision,changeSummary:"attack"})})).status,404);assert.notEqual((await fetch(`${base}/runs/${fixture.id}/approvals/00000000-0000-4000-8000-000000000000/export`,{headers:headers(userA,false)})).status,200);
  run=await json(userA,`/runs/${fixture.id}/destinations`,{destinations:["youtube_shorts","instagram_reels","linkedin"],expectedReleaseRevision:run.release.revision},"PUT");run=await json(userA,`/runs/${fixture.id}/release/review`,{expectedReleaseRevision:run.release.revision});assert.equal(run.currentStage,"approve");let p=run.release.packVersions.find((x:any)=>x.id===run.release.activePackVersionId),m=run.release.mediaVersions.find((x:any)=>x.id===run.release.activeMediaVersionId),approvalBody={expectedReleaseRevision:run.release.revision,storyboardLineage:lineage,packVersionId:p.id,mediaVersionId:m.id,mediaSha256:m.sha256,destinations:run.release.selectedDestinations};assert.equal((await fetch(`${base}/runs/${fixture.id}/approve`,{method:"POST",headers:headers(userB),body:JSON.stringify(approvalBody)})).status,404);const first=await json(userA,`/runs/${fixture.id}/approve`,approvalBody),second=await json(userA,`/runs/${fixture.id}/approve`,approvalBody);assert.equal(first.currentStage,"done");assert.equal(first.release.activeApprovalId,second.release.activeApprovalId);const firstExport=await fetch(`${base}/runs/${fixture.id}/approvals/${first.release.activeApprovalId}/export`,{headers:headers(userA,false)});assert.equal(firstExport.status,200);assert.equal(firstExport.headers.get("x-content-type-options"),"nosniff");assert.ok((await firstExport.arrayBuffer()).byteLength>100);assert.equal((await fetch(`${base}/runs/${fixture.id}/approvals/${first.release.activeApprovalId}/export`,{headers:headers(userB,false)})).status,404);assert.equal((await fetch(`${base}/runs/${fixture.id}/approvals/${first.release.activeApprovalId}/video`,{headers:headers(userB,false)})).status,404);
  run=await json(userA,`/runs/${fixture.id}/destinations`,{destinations:["youtube_shorts"],expectedReleaseRevision:first.release.revision},"PUT");assert.equal(run.release.activeApprovalId,undefined);assert.ok(run.release.supersessions.some((s:any)=>s.approvalId===first.release.approvals[0].id));run=await json(userA,`/runs/${fixture.id}/destinations`,{destinations:["youtube_shorts","instagram_reels","linkedin"],expectedReleaseRevision:run.release.revision},"PUT");p=run.release.packVersions.find((x:any)=>x.id===run.release.activePackVersionId);m=run.release.mediaVersions.find((x:any)=>x.id===run.release.activeMediaVersionId);approvalBody={expectedReleaseRevision:run.release.revision,storyboardLineage:lineage,packVersionId:p.id,mediaVersionId:m.id,mediaSha256:m.sha256,destinations:run.release.selectedDestinations};run=await json(userA,`/runs/${fixture.id}/approve`,approvalBody);assert.notEqual(run.release.activeApprovalId,first.release.activeApprovalId,"supersession requires a new approval record even when destinations return to the same set");
  const replacement=await fetch(`${base}/runs/${fixture.id}/final-media`,{method:"POST",headers:{...headers(userA,false),"Content-Type":"application/octet-stream","X-VPO-Filename":encodeURIComponent("replacement.mp4"),"X-VPO-Release-Revision":String(run.release.revision),"X-VPO-Storyboard-Lineage":lineage,"X-VPO-Active-Media-Version":run.release.activeMediaVersionId},body:bytes});const replacementText=await replacement.text();assert.equal(replacement.status,201,replacementText);run=JSON.parse(replacementText);assert.equal(run.release.mediaVersions.length,2);assert.equal(run.release.activeApprovalId,undefined);assert.ok(run.release.approvals.some((a:any)=>a.id===first.release.activeApprovalId));p=run.release.packVersions.find((x:any)=>x.id===run.release.activePackVersionId);m=run.release.mediaVersions.find((x:any)=>x.id===run.release.activeMediaVersionId);approvalBody={expectedReleaseRevision:run.release.revision,storyboardLineage:lineage,packVersionId:p.id,mediaVersionId:m.id,mediaSha256:m.sha256,destinations:run.release.selectedDestinations};run=await json(userA,`/runs/${fixture.id}/approve`,approvalBody);const replacementApproval=run.release.activeApprovalId;
  if(child&&child.exitCode===null){const stopped=new Promise(r=>child!.once("exit",r));child.kill("SIGKILL");await stopped}child=spawn(process.execPath,["dist/backend/src/server.js"],{cwd:process.cwd(),env:{...process.env,NODE_ENV:"test",PORT:String(port),TEST_MODE:"true",AUTH_MODE:"local",STORAGE_MODE:"local_json",STORAGE_LOCAL_PATH:dir,TEST_DELAY_MS:"5"},stdio:"pipe"});for(let i=0;i<100;i++){try{if((await fetch(`${base}/health`)).ok)break}catch{}await sleep(50)}run=await json(userA,`/runs/${fixture.id}`);assert.equal(run.release.activeApprovalId,replacementApproval);assert.equal(run.release.mediaVersions.length,2);const exportResponse=await fetch(`${base}/runs/${fixture.id}/approvals/${replacementApproval}/export`,{headers:headers(userA,false)});assert.equal(exportResponse.status,200);const reopened=await json(userA,`/runs/${fixture.id}/approval/reopen`,{approvalId:replacementApproval,expectedReleaseRevision:run.release.revision,confirmSupersession:true});assert.equal(reopened.release.activeApprovalId,undefined);assert.ok(reopened.release.supersessions.length>=2);
  assert.equal(reopened.currentStage,"approve");const editing=await json(userA,`/runs/${fixture.id}/release/edit`,{expectedReleaseRevision:reopened.release.revision});assert.equal(editing.currentStage,"pack");const corrupt=await fetch(`${base}/runs/${fixture.id}/final-media`,{method:"POST",headers:{...headers(userA,false),"Content-Type":"application/octet-stream","X-VPO-Filename":encodeURIComponent("fake.mp4"),"X-VPO-Release-Revision":String(editing.release.revision),"X-VPO-Storyboard-Lineage":lineage,"X-VPO-Active-Media-Version":editing.release.activeMediaVersionId},body:Buffer.from("not an mp4")});assert.equal(corrupt.status,422);let after=await json(userA,`/runs/${fixture.id}`);assert.equal(after.release.mediaVersions.length,2);const staleUpload=await fetch(`${base}/runs/${fixture.id}/final-media`,{method:"POST",headers:{...headers(userA,false),"Content-Type":"application/octet-stream","X-VPO-Filename":"stale.mp4","X-VPO-Release-Revision":String(after.release.revision),"X-VPO-Storyboard-Lineage":lineage,"X-VPO-Active-Media-Version":"none"},body:Buffer.from("body must not be probed")});assert.equal(staleUpload.status,409);const sharedHeaders={...headers(userA,false),"Content-Type":"application/octet-stream","X-VPO-Filename":"concurrent.mp4","X-VPO-Release-Revision":String(after.release.revision),"X-VPO-Storyboard-Lineage":lineage,"X-VPO-Active-Media-Version":after.release.activeMediaVersionId};const concurrent=await Promise.all([fetch(`${base}/runs/${fixture.id}/final-media`,{method:"POST",headers:sharedHeaders,body:bytes}),fetch(`${base}/runs/${fixture.id}/final-media`,{method:"POST",headers:sharedHeaders,body:bytes})]);assert.deepEqual(concurrent.map(item=>item.status).sort(),[201,409]);after=await json(userA,`/runs/${fixture.id}`);assert.equal(after.release.mediaVersions.length,3);const assetRecords=(await import("node:fs/promises")).readdir(dir).then(names=>names.filter(name=>name.startsWith("asset-")).length);assert.equal(await assetRecords,3,"failed concurrent activation cleans only its newly uploaded object metadata");
}finally{if(child&&child.exitCode===null){const stopped=new Promise(r=>child!.once("exit",r));child.kill("SIGKILL");await stopped}await rm(dir,{recursive:true,force:true})}});

test("Pack and media validators enforce deterministic hard rules",()=>{const r=approvedRun(""),pack=packFixture(r);assert.deepEqual(packFixture(r),pack,"TEST_MODE fixture must be deterministic");assert.equal(validatePack(pack).valid,true);pack.platforms.youtube_shorts.title="x".repeat(101);assert.equal(validatePack(pack).valid,false);const validRaw={format:{format_name:"mov,mp4,m4a,3gp,3g2,mj2",duration:"8"},streams:[{codec_type:"video",codec_name:"h264",width:720,height:1280},{codec_type:"audio",codec_name:"aac"}]};assert.equal(validateProbe(validRaw,100,Buffer.from("0000ftyp0000")).validation.valid,true,"an 8-second video has no artificial duration blocker");const longRaw=structuredClone(validRaw);longRaw.format.duration="3600";assert.equal(validateProbe(longRaw,100,Buffer.from("0000ftyp0000")).validation.valid,true,"duration has no upper product limit");for(const mutate of [(x:any)=>x.streams[0].codec_name="vp9",(x:any)=>x.streams[1].codec_name="mp3",(x:any)=>x.format.duration="0",(x:any)=>x.streams[0].width=640,(x:any)=>x.format.format_name="matroska,webm"]){const value=structuredClone(validRaw);mutate(value);assert.equal(validateProbe(value,100,Buffer.from("0000ftyp0000")).validation.valid,false)}assert.equal(validateProbe(validRaw,100,Buffer.from("not-an-mp4-header")).validation.valid,false,"spoofed extension/MIME cannot replace the byte signature");assert.equal(validateProbe(validRaw,100*1024*1024+1,Buffer.from("0000ftyp0000")).validation.valid,false);
  const notApproved=approvedRun("");delete notApproved.generation!.boardApprovedAt;const readiness=calculateReadiness(notApproved);assert.equal(readiness.valid,false);assert.ok(readiness.blockers.some(x=>x.code==="storyboard_missing"));assert.throws(()=>preparePackVersion(notApproved,packFixture(notApproved),"generated","blocked",notApproved.userId),/Approve the current Storyboard/);
  const legacy=approvedRun("");legacy.pack={...pack,title:pack.platforms.youtube_shorts.title,captions:[{platform:"youtube_shorts",caption:pack.platforms.youtube_shorts.description},{platform:"instagram_reels",caption:pack.platforms.instagram_reels.caption},{platform:"linkedin",caption:pack.platforms.linkedin.commentary}],hashtags:pack.platforms.instagram_reels.hashtags,postingNotes:pack.platforms.instagram_reels.postingNotes,approved:true};legacy.currentStage="done";const view=releaseReadView(legacy);assert.equal(view.release?.packVersions[0].origin,"legacy_sample");assert.equal(view.currentStage,"pack");assert.equal(legacy.release,undefined,"read compatibility must not rewrite the stored object");
});

test("an injected Pack provider result is not repeated by a storage conflict",async()=>{let providerCalls=0,revision=1,commits=0;const run=approvedRun(""),provider=async()=>{providerCalls++;return packFixture(run)},result=await provider();const saved=await optimisticRunUpdate(async()=>({run:structuredClone(run),revision}),async(next)=>{commits++;if(commits===1){revision++;return false}Object.assign(run,next);return true},next=>{next.job={id:"pack-job",kind:"pack",status:"running",checkpoint:"pack-result",startedAt:new Date().toISOString(),message:"",packDraft:result};});assert.equal(saved.job?.packDraft?.thumbnailText,result.thumbnailText);assert.equal(commits,2);assert.equal(providerCalls,1)});

function reverseKeys(value:unknown):unknown{if(Array.isArray(value))return value.map(reverseKeys);if(value&&typeof value==="object")return Object.fromEntries(Object.entries(value as Record<string,unknown>).reverse().map(([key,item])=>[key,reverseKeys(item)]));return value;}
test("Storyboard lineage hashes approved content canonically",()=>{const base=approvedRun(),baseline=storyboardLineage(base);assert.equal(fingerprint(base),fingerprint(reverseKeys(base)),"canonical fingerprints ignore object insertion order");assert.equal(storyboardLineage(reverseKeys(base) as Run),baseline);
  const changes:Array<(run:Run)=>void>=[
    run=>{run.effective!.summary+=" changed";},run=>{run.script!.beats[0].vo+=" changed";},run=>{run.directions[0].angle+=" changed";},run=>{run.generation!.prompts[0].prompt+=" changed";},run=>{run.generation!.keys[0].note="changed";},run=>{run.generation!.board[0].instruction+=" changed";},run=>{run.generation!.board[0].attempts[0].note="changed";},
  ];for(const change of changes){const run=structuredClone(base);change(run);assert.notEqual(storyboardLineage(run),baseline);}
  const facts=structuredClone(base);facts.facts=[{id:"fact-1",text:"Supported detail",label:"stated",sourceId:"source-1",removed:false}];facts.script!.beats[0].factIds=["fact-1"];const factLineage=storyboardLineage(facts);facts.facts[0].text="Changed supported detail";assert.notEqual(storyboardLineage(facts),factLineage);
});

test("Pack context, lineage, references and claim corpus share one canonical retained-fact set",()=>{const run=approvedRun();run.facts=[{id:"fact-z",text:"Unreferenced but retained fact",label:"stated",sourceId:"source-z",removed:false},{id:"fact-a",text:"Referenced retained fact",label:"stated",sourceId:"source-a",removed:false},{id:"fact-x",text:"Excluded removed fact",label:"stated",sourceId:"source-x",removed:true}];run.script!.beats[0].factIds=["fact-a"];const lineage=storyboardLineage(run),context=packContext(run),inputHash=fingerprint(context),refs=packInputReferences(run);assert.deepEqual(refs.retainedFactIds,["fact-a","fact-z"]);assert.equal(packContext(reverseKeys(run) as Run),context,"canonical context ignores object key insertion order");const sentChange=structuredClone(run);sentChange.facts.find(item=>item.id==="fact-z")!.text="Changed provider input";assert.notEqual(storyboardLineage(sentChange),lineage);assert.notEqual(fingerprint(packContext(sentChange)),inputHash);assert.notEqual(packInputReferences(sentChange).inputFingerprint,refs.inputFingerprint);const excludedChange=structuredClone(run);excludedChange.facts.find(item=>item.id==="fact-x")!.text="Changed excluded fact";assert.equal(storyboardLineage(excludedChange),lineage);assert.equal(fingerprint(packContext(excludedChange)),inputHash);assert.equal(packInputReferences(excludedChange).inputFingerprint,refs.inputFingerprint);const safe=packFixture(run);safe.platforms.linkedin.commentary="Unreferenced but retained fact";assert.equal(validatePack(safe,{run,checkedAt:"fixed"}).blockers.filter(item=>item.code.startsWith("novel_")).length,0);});

function readyRun(){const run=approvedRun(),lineage=storyboardLineage(run)!;const pack=preparePackVersion(run,packFixture(run),"generated","Generated",run.userId,{id:"10000000-0000-4000-8000-000000000001",createdAt:"2026-10-01T01:00:00.000Z",provenance:"test"});applyPackVersion(run,pack,0);const media:FinalMediaVersion={id:"20000000-0000-4000-8000-000000000001",version:1,assetId:"30000000-0000-4000-8000-000000000001",storyboardLineage:lineage,originalSafeFilename:"final.mp4",detectedMediaType:"video/mp4",byteSize:100,sha256:"a".repeat(64),probe:{container:"mp4",videoCodec:"h264",audioCodecs:["aac"],durationSeconds:15,codedWidth:720,codedHeight:1280,displayWidth:720,displayHeight:1280,rotation:0},validation:{valid:true,policyVersion:"test",blockers:[],warnings:[],checkedAt:"2026-10-01T01:01:00.000Z"},createdAt:"2026-10-01T01:01:00.000Z",createdBy:run.userId};applyMediaVersion(run,media,1,undefined);run.release!.selectedDestinations=["youtube_shorts"];run.release!.destinationRevision=1;run.release!.revision++;calculateReadiness(run,"2026-10-01T01:02:00.000Z");return run;}
async function forcedRetry(base:Run,update:(run:Run)=>void){let saved=structuredClone(base),revision=1,writes=0;const result=await optimisticRunUpdate(async()=>({run:structuredClone(saved),revision}),async(next)=>{writes++;if(writes===1){revision++;return false;}saved=structuredClone(next);return true;},update);return{result,writes};}

test("prepared release mutations remain identical under a forced CAS retry",async()=>{const intentRun=approvedRun(),release=ensureRelease(intentRun),lineage=storyboardLineage(intentRun)!;release.packQuotes.push(currentQuote(intentRun,"40000000-0000-4000-8000-000000000001"));const intent=preparePackIntent(intentRun,release.packQuotes[0].id),intentSupersession=prepareSupersession(intentRun,"Pack generation started",intent.createdAt);const intentRetry=await forcedRetry(intentRun,run=>{applyPackIntent(run,intent,{expectedStoryboardLineage:lineage,expectedReleaseRevision:0},intentSupersession);});assert.equal(intentRetry.writes,2);assert.deepEqual(intentRetry.result.release!.packIntents,[intent]);assert.equal(intentRetry.result.release!.packQuotes[0].usedByJobId,intent.jobId);
  const packBase=approvedRun(),version=preparePackVersion(packBase,packFixture(packBase),"generated","Generated",packBase.userId,{id:"50000000-0000-4000-8000-000000000001",createdAt:"2026-10-01T02:00:00.000Z"});const packRetry=await forcedRetry(packBase,run=>{applyPackVersion(run,version,0);});assert.deepEqual(packRetry.result.release!.packVersions,[version]);
  const mediaBase=structuredClone(packRetry.result),media:FinalMediaVersion={id:"60000000-0000-4000-8000-000000000001",version:1,assetId:"70000000-0000-4000-8000-000000000001",storyboardLineage:lineage,originalSafeFilename:"final.mp4",detectedMediaType:"video/mp4",byteSize:100,sha256:"b".repeat(64),probe:{container:"mp4",videoCodec:"h264",audioCodecs:[],durationSeconds:15,codedWidth:720,codedHeight:1280,displayWidth:720,displayHeight:1280,rotation:0},validation:{valid:true,policyVersion:"test",blockers:[],warnings:[],checkedAt:"2026-10-01T02:01:00.000Z"},createdAt:"2026-10-01T02:01:00.000Z",createdBy:mediaBase.userId};const mediaRetry=await forcedRetry(mediaBase,run=>{applyMediaVersion(run,media,1,undefined);});assert.deepEqual(mediaRetry.result.release!.mediaVersions,[media]);
  const approvalBase=readyRun(),approvalFingerprint=readinessFingerprint(approvalBase)!;const approval:ReleaseApproval={id:"80000000-0000-4000-8000-000000000001",version:1,ownerId:approvalBase.userId,runId:approvalBase.id,approvalEpoch:0,storyboardLineage:storyboardLineage(approvalBase)!,packVersionId:approvalBase.release!.activePackVersionId!,packProvenance:"test",policyFingerprint:RELEASE_POLICY_FINGERPRINT,mediaVersionId:approvalBase.release!.activeMediaVersionId!,mediaSha256:"a".repeat(64),destinations:["youtube_shorts"],readinessFingerprint:approvalFingerprint,approvedAt:"2026-10-01T02:02:00.000Z",approvedBy:approvalBase.userId};const approvalRetry=await forcedRetry(approvalBase,run=>{applyApproval(run,approval,3,approval.approvedAt);});assert.deepEqual(approvalRetry.result.release!.approvals,[approval]);
  const reopenBase=structuredClone(approvalRetry.result),supersession=prepareSupersession(reopenBase,"Release reopened for review","2026-10-01T02:03:00.000Z")!;const reopened=await forcedRetry(reopenBase,run=>{applyReopen(run,approval.id,3,supersession,"2026-10-01T02:03:00.000Z");});assert.equal(reopened.result.release!.supersessions.filter(item=>item.approvalId===approval.id).length,1);assert.equal(reopened.result.currentStage,"approve");
});

test("one Pack intent is consumed once and resumes only at safe checkpoints",()=>{const run=approvedRun(),release=ensureRelease(run),lineage=storyboardLineage(run)!;release.packQuotes.push(currentQuote(run,"41000000-0000-4000-8000-000000000001"));const intent=preparePackIntent(run,release.packQuotes[0].id);applyPackIntent(run,intent,{expectedStoryboardLineage:lineage,expectedReleaseRevision:0});assert.equal(release.packIntents.length,1);assert.equal(release.packQuotes[0].usedByJobId,intent.jobId);assert.equal(applyPackIntent(run,intent,{expectedStoryboardLineage:lineage,expectedReleaseRevision:0}).id,intent.id,"same confirmation is idempotent");
  release.packQuotes.push(currentQuote(run,"42000000-0000-4000-8000-000000000001"));const second=preparePackIntent(run,release.packQuotes[1].id);assert.throws(()=>applyPackIntent(run,second,{expectedStoryboardLineage:lineage,expectedReleaseRevision:1}),/already active/);
  run.jobStatus="interrupted";run.job!.status="interrupted";assert.equal(applyPackResume(run,intent.id).id,intent.id);assert.equal(run.jobStatus,"queued","pre-call checkpoint resumes the same intent");run.jobStatus="interrupted";run.job!.status="interrupted";run.job!.packDraft=packFixture(run);release.packIntents[0].status="draft_saved";applyPackResume(run,intent.id);assert.deepEqual(run.job!.packDraft,packFixture(run),"saved draft is retained for persistence-only resume");run.jobStatus="interrupted";run.job!.status="interrupted";release.packIntents[0].status="ambiguous";assert.throws(()=>applyPackResume(run,intent.id),/unknown and will not be repeated/);
});

test("Pack quote policy, provenance and confirmation time stay bound across CAS retries",async()=>{const run=approvedRun(),release=ensureRelease(run),lineage=storyboardLineage(run)!;const quote=currentQuote(run,"43000000-0000-4000-8000-000000000001","2026-10-01T00:00:10.000Z");release.packQuotes.push(quote);const intent=preparePackIntent(run,quote.id,"2026-10-01T00:00:09.000Z"),originalNow=Date.now;let crossed=false;try{Date.now=()=>Date.parse(crossed?"2026-10-01T00:00:11.000Z":"2026-10-01T00:00:09.000Z");let saved=structuredClone(run),revision=1,writes=0;const result=await optimisticRunUpdate(async()=>({run:structuredClone(saved),revision}),async(next)=>{writes++;if(writes===1){crossed=true;revision++;return false;}saved=structuredClone(next);return true;},next=>{applyPackIntent(next,intent,{expectedStoryboardLineage:lineage,expectedReleaseRevision:0});});assert.equal(writes,2);assert.equal(result.release!.packIntents[0].createdAt,"2026-10-01T00:00:09.000Z");assert.equal(result.release!.packIntents.length,1);}finally{Date.now=originalNow;}
  const expired=approvedRun(),expiredRelease=ensureRelease(expired),expiredQuote=currentQuote(expired,"44000000-0000-4000-8000-000000000001","2026-10-01T00:00:10.000Z");expiredRelease.packQuotes.push(expiredQuote);assert.throws(()=>preparePackIntent(expired,expiredQuote.id,"2026-10-01T00:00:11.000Z"),/stale/);
  const oldPolicy=approvedRun(),oldPolicyRelease=ensureRelease(oldPolicy),oldPolicyQuote=currentQuote(oldPolicy,"45000000-0000-4000-8000-000000000001");delete oldPolicyQuote.validationPolicyFingerprint;oldPolicyRelease.packQuotes.push(oldPolicyQuote);assert.throws(()=>preparePackIntent(oldPolicy,oldPolicyQuote.id,"2026-10-01T00:00:00.000Z"),/stale/);
  const changedMode=approvedRun(),changedRelease=ensureRelease(changedMode),changedQuote=currentQuote(changedMode,"46000000-0000-4000-8000-000000000001");changedRelease.packQuotes.push(changedQuote);changedMode.mode="live";assert.throws(()=>preparePackIntent(changedMode,changedQuote.id,"2026-10-01T00:00:00.000Z"),/stale/);
});

test("Pack provenance, legacy eligibility, references and claim safety are deterministic",()=>{const base=approvedRun(),generated=preparePackVersion(base,packFixture(base),"generated","Generated",base.userId,{createdAt:"2026-10-01T03:00:00.000Z"});assert.equal(generated.version,1);assert.equal(generated.provenance,"test");assert.equal(generated.validationPolicyFingerprint,RELEASE_POLICY_FINGERPRINT);assert.ok(generated.inputReferences?.inputFingerprint);
  const live=approvedRun();live.mode="live";assert.equal(preparePackVersion(live,packFixture(live),"generated","Generated",live.userId,{createdAt:"2026-10-01T03:00:00.000Z"}).provenance,"live");
  const legacy=approvedRun();legacy.pack={...packFixture(legacy),title:"Legacy",captions:[],hashtags:[],postingNotes:"",approved:true};const legacyRelease=ensureRelease(legacy);assert.equal(legacyRelease.packVersions[0].version,0);assert.equal(legacyRelease.packVersions[0].provenance,"legacy_sample");assert.ok(calculateReadiness(legacy).blockers.some(item=>item.code==="legacy_sample_ineligible"));
  const cases=[{code:"novel_url",value:"Learn at https://new.example/path"},{code:"novel_price",value:"Only $99"},{code:"novel_percentage",value:"Improves by 42%"},{code:"novel_numeric_claim",value:"Used by 700 customers"}];for(const item of cases){const content=packFixture(base);content.platforms.linkedin.commentary=item.value;assert.ok(validatePack(content,{run:base,checkedAt:"fixed"}).blockers.some(blocker=>blocker.code===item.code),item.code);}
  const allowed=approvedRun();allowed.brief.notes="See https://ok.example. Price $99, improves 42%, used by 700 customers.";for(const value of ["https://ok.example","$99","42%","700 customers"]){const content=packFixture(allowed);content.platforms.linkedin.commentary=value;assert.equal(validatePack(content,{run:allowed,checkedAt:"fixed"}).blockers.filter(item=>item.code.startsWith("novel_")).length,0,value);}
  const removed=approvedRun();removed.facts=[{id:"fact-x",text:"Removed fact",label:"stated",sourceId:"s",removed:true}];removed.script!.beats[0].factIds=["fact-x"];assert.throws(()=>storyboardLineage(removed),/removed or unknown fact/);const unknown=approvedRun();unknown.generation!.board[0].beatIds=["missing"];assert.throws(()=>storyboardLineage(unknown),/unknown beat/);
});

test("serialized pre-r2 Pack versions stay readable but stale and non-exportable",()=>{const original=readyRun(),fingerprintBefore=readinessFingerprint(original)!;const approval:ReleaseApproval={id:"47000000-0000-4000-8000-000000000001",version:1,ownerId:original.userId,runId:original.id,approvalEpoch:0,storyboardLineage:storyboardLineage(original)!,packVersionId:original.release!.activePackVersionId!,packProvenance:"test",policyFingerprint:RELEASE_POLICY_FINGERPRINT,mediaVersionId:original.release!.activeMediaVersionId!,mediaSha256:"a".repeat(64),destinations:["youtube_shorts"],readinessFingerprint:fingerprintBefore,approvedAt:"2026-10-01T04:00:00.000Z",approvedBy:original.userId};applyApproval(original,approval,3,approval.approvedAt);delete activePack(original)!.validationPolicyFingerprint;delete activePack(original)!.provenance;const serialized=JSON.stringify(original),loaded=JSON.parse(serialized) as Run,view=releaseReadView(loaded),loadedPack=activePack(loaded)!;assert.equal(loadedPack.content.platforms.youtube_shorts.title,packFixture(loaded).platforms.youtube_shorts.title,"old Pack remains readable");assert.equal(Object.hasOwn(loadedPack,"validationPolicyFingerprint"),false,"read projection must not bless the immutable old version");assert.equal(Object.hasOwn(loadedPack,"provenance"),false,"read projection must not rewrite old provenance");const blockers=calculateReadiness(loaded,"2026-10-01T04:01:00.000Z").blockers;assert.ok(blockers.some(item=>item.code==="pack_policy_stale"));assert.ok(blockers.some(item=>item.code==="pack_provenance_unknown"));assert.equal(approvalMatchesActive(loaded,loaded.release!.approvals[0]),false,"the approved export gate rejects the upgraded pre-r2 Pack");assert.equal(Object.hasOwn(activePack(view)!,"validationPolicyFingerprint"),false);const restored=preparePackVersion(loaded,loadedPack.content,"restored","Explicitly revalidated",loaded.userId,{createdAt:"2026-10-01T04:02:00.000Z"});assert.equal(restored.validationPolicyFingerprint,RELEASE_POLICY_FINGERPRINT);assert.equal(restored.provenance,"test");assert.equal(Object.hasOwn(loadedPack,"validationPolicyFingerprint"),false,"new eligible version does not rewrite the old immutable version");});

test("Pack restore guard rejects queued and running jobs before mutation",()=>{for(const status of ["queued","running"] as const){const run=readyRun(),before=JSON.stringify(run.release!.packVersions);run.jobStatus=status;run.job={id:`job-${status}`,kind:"pack",status,checkpoint:"provider-call",startedAt:"2026-10-01T05:00:00.000Z",message:"active"};assert.throws(()=>assertPackUserMutationIdle(run),/active Pack job/);assert.equal(JSON.stringify(run.release!.packVersions),before);}});

test("each release-readiness blocker is independently reported and exact approval binding detects tampering",()=>{const codes=(run:Run)=>calculateReadiness(run,"fixed").blockers.map(item=>item.code);const noBoard=approvedRun();delete noBoard.generation!.boardApprovedAt;assert.ok(codes(noBoard).includes("storyboard_missing"));const noPack=approvedRun();assert.ok(codes(noPack).includes("pack_missing"));const noMedia=structuredClone(readyRun());delete noMedia.release!.activeMediaVersionId;assert.ok(codes(noMedia).includes("media_missing"));const noDest=readyRun();noDest.release!.selectedDestinations=[];assert.ok(codes(noDest).includes("destinations_missing"));const badPack=readyRun();activePack(badPack)!.validation={valid:false,policyVersion:"x",blockers:[{code:"bad_pack",message:"bad"}],warnings:[],checkedAt:"x"};assert.ok(codes(badPack).includes("bad_pack"));const stalePack=readyRun();activePack(stalePack)!.storyboardLineage="x";assert.ok(codes(stalePack).includes("pack_stale"));const oldPolicy=readyRun();activePack(oldPolicy)!.validationPolicyFingerprint="old";assert.ok(codes(oldPolicy).includes("pack_policy_stale"));const badMedia=readyRun();badMedia.release!.mediaVersions[0].validation={valid:false,policyVersion:"x",blockers:[{code:"bad_media",message:"bad"}],warnings:[],checkedAt:"x"};assert.ok(codes(badMedia).includes("bad_media"));const staleMedia=readyRun();staleMedia.release!.mediaVersions[0].storyboardLineage="x";assert.ok(codes(staleMedia).includes("media_stale"));
  for(const blocked of [noBoard,noPack,noMedia,noDest,badPack,stalePack,oldPolicy,badMedia,staleMedia]){const release=ensureRelease(blocked),candidate:ReleaseApproval={id:"91000000-0000-4000-8000-000000000001",version:1,ownerId:blocked.userId,runId:blocked.id,approvalEpoch:release.approvalEpoch,storyboardLineage:storyboardLineage(blocked)??"missing",packVersionId:release.activePackVersionId??"missing",packProvenance:activePack(blocked)?.provenance??"test",policyFingerprint:RELEASE_POLICY_FINGERPRINT,mediaVersionId:release.activeMediaVersionId??"missing",mediaSha256:"a".repeat(64),destinations:release.selectedDestinations,readinessFingerprint:"invalid",approvedAt:"fixed",approvedBy:blocked.userId};assert.throws(()=>applyApproval(blocked,candidate,release.revision,"fixed"),/Release changed before approval/);}
  const approved=readyRun(),fp=readinessFingerprint(approved)!;const approval:ReleaseApproval={id:"90000000-0000-4000-8000-000000000001",version:1,ownerId:approved.userId,runId:approved.id,approvalEpoch:0,storyboardLineage:storyboardLineage(approved)!,packVersionId:approved.release!.activePackVersionId!,packProvenance:"test",policyFingerprint:RELEASE_POLICY_FINGERPRINT,mediaVersionId:approved.release!.activeMediaVersionId!,mediaSha256:"a".repeat(64),destinations:["youtube_shorts"],readinessFingerprint:fp,approvedAt:"fixed",approvedBy:approved.userId};applyApproval(approved,approval,3,"fixed");assert.equal(approved.currentStage,"done");approved.release!.mediaVersions[0].sha256="c".repeat(64);assert.notEqual(readinessFingerprint(approved),fp);
});
