import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { spawn, spawnSync, type ChildProcess } from "node:child_process";
import type { Run } from "../../frontend/lib/types.js";
import { calculateReadiness, releaseReadView, storyboardLineage, validatePack } from "../src/release.js";
import { packFixture } from "../src/pack.js";
import { validateProbe } from "../src/media.js";
import { optimisticRunUpdate } from "../src/supabase-storage.js";

const userA="11111111-1111-4111-8111-111111111111",userB="22222222-2222-4222-8222-222222222222";
function approvedRun(dir:string):Run { const now=new Date().toISOString(),asset="aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",attempt={id:"bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",assetId:asset,imageUrl:`/api/images/${asset}`,attempt:1,jobId:"fixture",note:"",origin:"user" as const,source:"uploaded" as const,mode:"test" as const,callIds:[],createdAt:now,approval:"approved" as const};
  return {id:"33333333-3333-4333-8333-333333333333",userId:userA,mode:"test",effective:{revision:1,subject:"Release test",objective:"explain",productDetails:"",visualPreferences:"",factualConstraints:"No unsupported claims",summary:"Explain release testing clearly.",confirmed:true,brandSelection:"none"},storyApproval:{scriptVersion:1,briefRevision:1,at:now},brief:{topic:"Release test",audience:"Class",platform:"youtube_shorts",aspectRatio:"9:16",durationSeconds:15,targetVideoModel:"Veo 3.1",sourceLinks:[],notes:"",pastedScript:"[0:00–0:15] VISUAL: Test card\nVO: Release test.\nON-SCREEN: Test"},currentStage:"storyboard",jobStatus:"completed",autopilot:false,runningCostUsd:0,createdAt:now,updatedAt:now,sources:[],facts:[],script:{version:1,beats:[{id:"beat-1",startSeconds:0,endSeconds:15,visual:"Test card",vo:"Release test.",onScreen:"Test",claimType:"creative",factIds:[]}],fullText:"Release test.",wordCount:2,estimatedSeconds:1,targetSeconds:15},directions:[{id:"direction-1",name:"Clear",hook:"Test",angle:"Explain",look:"Clean",mood:"Calm",summary:"Clear test"}],selectedDirectionId:"direction-1",directionNote:"",videoPrompt:null,frames:[],pack:null,aiCallLog:[],brandKit:{origin:"empty",brandName:"",palette:[],characterDescription:"",tone:"",constraints:"",preferredPlatforms:[]},generation:{revision:1,storyApproved:true,directionsReady:true,prompts:[{id:"prompt-1",revision:1,attempt:1,prompt:"Create a clear vertical release test video with a stable test card and simple motion.",negativePrompt:"Avoid unsupported claims.",visualBible:"Clean release test card",callIds:[],origin:"user",review:{dimensions:{clarity:{score:90,explanation:"clear"}},overall:90,threshold:75,passed:true,callIds:[]}}],activePromptId:"prompt-1",keys:[attempt],activeKeyId:attempt.id,approvedKeyId:attempt.id,board:[{id:"frame-1",order:0,beatIds:["beat-1"],instruction:"Test card",isKey:true,attempts:[attempt],selectedAttemptId:attempt.id,complete:true,retryLimitReached:false}],archivedBoards:[],boardApprovedAt:now,quotes:[],activities:[],manualRegenerations:0,limits:{promptThreshold:75,promptRewrites:2,frameThreshold:70,autoRegenerations:1,manualRegenerations:6,maxFrames:6,uploadBytes:5242880}},sampleStages:true}; }
const sleep=(n:number)=>new Promise(r=>setTimeout(r,n));
test("Step 5B release candidate is versioned, media-probed, owner-scoped, approved, exported and reopened",async()=>{const dir=await mkdtemp(path.join(tmpdir(),"vpo-step5b-")),port=4106,base=`http://127.0.0.1:${port}/api`;let child:ChildProcess|undefined;try{const fixture=approvedRun(dir),lineage=storyboardLineage(fixture)!;assert.equal(lineage.length,64);await writeFile(path.join(dir,`run-${fixture.id}.json`),JSON.stringify(fixture));
  const video=path.join(dir,"valid.mp4"),made=spawnSync("ffmpeg",["-y","-f","lavfi","-i","color=c=black:s=720x1280:r=1:d=15","-f","lavfi","-i","anullsrc=r=44100:cl=stereo","-c:v","libx264","-pix_fmt","yuv420p","-c:a","aac","-shortest","-movflags","+faststart",video],{encoding:"utf8"});assert.equal(made.status,0,made.stderr);
  child=spawn(process.execPath,["dist/backend/src/server.js"],{cwd:process.cwd(),env:{...process.env,NODE_ENV:"test",PORT:String(port),TEST_MODE:"true",AUTH_MODE:"local",STORAGE_MODE:"local_json",STORAGE_LOCAL_PATH:dir,TEST_DELAY_MS:"5"},stdio:"pipe"});for(let i=0;i<100;i++){try{if((await fetch(`${base}/health`)).ok)break}catch{}await sleep(50)}
  const headers=(u:string,json=true)=>({Authorization:`Bearer test-user:${u}`,...(json?{"Content-Type":"application/json"}:{})});const json=async(u:string,route:string,body?:unknown,method=body?"POST":"GET")=>{const response=await fetch(base+route,{method,headers:headers(u),body:body?JSON.stringify(body):undefined});const data=await response.json();assert.ok(response.ok,JSON.stringify(data));return data};
  const quote=await json(userA,`/runs/${fixture.id}/pack-quotes`,{expectedStoryboardLineage:lineage});assert.equal(quote.amountUsd,0);await json(userA,`/runs/${fixture.id}/pack`,{quoteId:quote.id,expectedStoryboardLineage:lineage,expectedReleaseRevision:quote.releaseRevision});let run:any;for(let i=0;i<100;i++){run=await json(userA,`/runs/${fixture.id}`);if(!["queued","running"].includes(run.jobStatus))break;await sleep(20)}assert.equal(run.release.packVersions.length,1);assert.equal(run.aiCallLog.filter((c:any)=>c.task==="pack-generation").length,1);
  const content={...run.release.packVersions[0].content,thumbnailText:"Edited test"};const edited=await json(userA,`/runs/${fixture.id}/pack`,{content,expectedReleaseRevision:run.release.revision,expectedActivePackVersionId:run.release.activePackVersionId,changeSummary:"Explicit edit"},"PATCH");assert.equal(edited.release.packVersions.length,2);const stale=await fetch(`${base}/runs/${fixture.id}/pack`,{method:"PATCH",headers:headers(userA),body:JSON.stringify({content,expectedReleaseRevision:run.release.revision,expectedActivePackVersionId:run.release.activePackVersionId,changeSummary:"stale"})});assert.equal(stale.status,409);const restored=await json(userA,`/runs/${fixture.id}/pack/restore`,{sourcePackVersionId:edited.release.packVersions[0].id,expectedActivePackVersionId:edited.release.activePackVersionId,expectedReleaseRevision:edited.release.revision,changeSummary:"Restore v1 as new"});assert.equal(restored.release.packVersions.length,3);
  const bytes=await readFile(video);const upload=await fetch(`${base}/runs/${fixture.id}/final-media`,{method:"POST",headers:{...headers(userA,false),"Content-Type":"application/octet-stream","X-VPO-Filename":encodeURIComponent("course.mp4"),"X-VPO-Release-Revision":String(restored.release.revision),"X-VPO-Storyboard-Lineage":lineage},body:bytes});const uploadText=await upload.text();assert.equal(upload.status,201,uploadText);run=JSON.parse(uploadText);assert.equal(run.release.mediaVersions[0].probe.videoCodec,"h264");assert.equal(run.release.mediaVersions[0].probe.audioCodecs[0],"aac");
  const media=run.release.mediaVersions[0],preview=await fetch(`${base}/runs/${fixture.id}/final-media/${media.id}/content`,{headers:headers(userA,false)});assert.equal(preview.status,200);assert.equal(preview.headers.get("cache-control"),"private, no-store");assert.match(preview.headers.get("vary")??"",/Authorization/i);assert.ok((await preview.arrayBuffer()).byteLength>100);assert.equal((await fetch(`${base}/runs/${fixture.id}/final-media/${media.id}/content`,{headers:headers(userB,false)})).status,404);assert.equal((await fetch(`${base}/runs/${fixture.id}/final-media`,{method:"POST",headers:{...headers(userB,false),"Content-Type":"application/octet-stream","X-VPO-Filename":encodeURIComponent("attack.mp4"),"X-VPO-Release-Revision":String(run.release.revision),"X-VPO-Storyboard-Lineage":lineage},body:bytes})).status,404);assert.equal((await fetch(`${base}/runs/${fixture.id}/pack`,{method:"PATCH",headers:headers(userB),body:JSON.stringify({content,expectedReleaseRevision:run.release.revision,expectedActivePackVersionId:run.release.activePackVersionId,changeSummary:"attack"})})).status,404);assert.notEqual((await fetch(`${base}/runs/${fixture.id}/approvals/00000000-0000-4000-8000-000000000000/export`,{headers:headers(userA,false)})).status,200);run=await json(userA,`/runs/${fixture.id}/destinations`,{destinations:["youtube_shorts","instagram_reels","linkedin"],expectedReleaseRevision:run.release.revision},"PUT");run=await json(userA,`/runs/${fixture.id}/release/review`,{expectedReleaseRevision:run.release.revision});let p=run.release.packVersions.find((x:any)=>x.id===run.release.activePackVersionId),m=run.release.mediaVersions.find((x:any)=>x.id===run.release.activeMediaVersionId),approvalBody={expectedReleaseRevision:run.release.revision,storyboardLineage:lineage,packVersionId:p.id,mediaVersionId:m.id,mediaSha256:m.sha256,destinations:run.release.selectedDestinations};assert.equal((await fetch(`${base}/runs/${fixture.id}/approve`,{method:"POST",headers:headers(userB),body:JSON.stringify(approvalBody)})).status,404);const first=await json(userA,`/runs/${fixture.id}/approve`,approvalBody),second=await json(userA,`/runs/${fixture.id}/approve`,approvalBody);assert.equal(first.release.activeApprovalId,second.release.activeApprovalId);const firstExport=await fetch(`${base}/runs/${fixture.id}/approvals/${first.release.activeApprovalId}/export`,{headers:headers(userA,false)});assert.equal(firstExport.status,200);assert.ok((await firstExport.arrayBuffer()).byteLength>100);assert.equal((await fetch(`${base}/runs/${fixture.id}/approvals/${first.release.activeApprovalId}/export`,{headers:headers(userB,false)})).status,404);assert.equal((await fetch(`${base}/runs/${fixture.id}/approvals/${first.release.activeApprovalId}/video`,{headers:headers(userB,false)})).status,404);
  run=await json(userA,`/runs/${fixture.id}/destinations`,{destinations:["youtube_shorts"],expectedReleaseRevision:first.release.revision},"PUT");assert.equal(run.release.activeApprovalId,undefined);assert.ok(run.release.supersessions.some((s:any)=>s.approvalId===first.release.approvals[0].id));run=await json(userA,`/runs/${fixture.id}/destinations`,{destinations:["youtube_shorts","instagram_reels","linkedin"],expectedReleaseRevision:run.release.revision},"PUT");p=run.release.packVersions.find((x:any)=>x.id===run.release.activePackVersionId);m=run.release.mediaVersions.find((x:any)=>x.id===run.release.activeMediaVersionId);approvalBody={expectedReleaseRevision:run.release.revision,storyboardLineage:lineage,packVersionId:p.id,mediaVersionId:m.id,mediaSha256:m.sha256,destinations:run.release.selectedDestinations};run=await json(userA,`/runs/${fixture.id}/approve`,approvalBody);assert.notEqual(run.release.activeApprovalId,first.release.activeApprovalId,"supersession requires a new approval record even when destinations return to the same set");
  const replacement=await fetch(`${base}/runs/${fixture.id}/final-media`,{method:"POST",headers:{...headers(userA,false),"Content-Type":"application/octet-stream","X-VPO-Filename":encodeURIComponent("replacement.mp4"),"X-VPO-Release-Revision":String(run.release.revision),"X-VPO-Storyboard-Lineage":lineage},body:bytes});const replacementText=await replacement.text();assert.equal(replacement.status,201,replacementText);run=JSON.parse(replacementText);assert.equal(run.release.mediaVersions.length,2);assert.equal(run.release.activeApprovalId,undefined);assert.ok(run.release.approvals.some((a:any)=>a.id===first.release.activeApprovalId));p=run.release.packVersions.find((x:any)=>x.id===run.release.activePackVersionId);m=run.release.mediaVersions.find((x:any)=>x.id===run.release.activeMediaVersionId);approvalBody={expectedReleaseRevision:run.release.revision,storyboardLineage:lineage,packVersionId:p.id,mediaVersionId:m.id,mediaSha256:m.sha256,destinations:run.release.selectedDestinations};run=await json(userA,`/runs/${fixture.id}/approve`,approvalBody);const replacementApproval=run.release.activeApprovalId;
  if(child&&child.exitCode===null){const stopped=new Promise(r=>child!.once("exit",r));child.kill("SIGKILL");await stopped}child=spawn(process.execPath,["dist/backend/src/server.js"],{cwd:process.cwd(),env:{...process.env,NODE_ENV:"test",PORT:String(port),TEST_MODE:"true",AUTH_MODE:"local",STORAGE_MODE:"local_json",STORAGE_LOCAL_PATH:dir,TEST_DELAY_MS:"5"},stdio:"pipe"});for(let i=0;i<100;i++){try{if((await fetch(`${base}/health`)).ok)break}catch{}await sleep(50)}run=await json(userA,`/runs/${fixture.id}`);assert.equal(run.release.activeApprovalId,replacementApproval);assert.equal(run.release.mediaVersions.length,2);const exportResponse=await fetch(`${base}/runs/${fixture.id}/approvals/${replacementApproval}/export`,{headers:headers(userA,false)});assert.equal(exportResponse.status,200);const reopened=await json(userA,`/runs/${fixture.id}/approval/reopen`,{approvalId:replacementApproval,expectedReleaseRevision:run.release.revision,confirmSupersession:true});assert.equal(reopened.release.activeApprovalId,undefined);assert.ok(reopened.release.supersessions.length>=2);
  const corrupt=await fetch(`${base}/runs/${fixture.id}/final-media`,{method:"POST",headers:{...headers(userA,false),"Content-Type":"application/octet-stream","X-VPO-Filename":encodeURIComponent("fake.mp4"),"X-VPO-Release-Revision":String(reopened.release.revision),"X-VPO-Storyboard-Lineage":lineage},body:Buffer.from("not an mp4")});assert.equal(corrupt.status,422);const after=await json(userA,`/runs/${fixture.id}`);assert.equal(after.release.mediaVersions.length,2);
}finally{if(child&&child.exitCode===null){const stopped=new Promise(r=>child!.once("exit",r));child.kill("SIGKILL");await stopped}await rm(dir,{recursive:true,force:true})}});

test("Pack and media validators enforce deterministic hard rules",()=>{const r=approvedRun(""),pack=packFixture(r);assert.deepEqual(packFixture(r),pack,"TEST_MODE fixture must be deterministic");assert.equal(validatePack(pack).valid,true);pack.platforms.youtube_shorts.title="x".repeat(101);assert.equal(validatePack(pack).valid,false);const validRaw={format:{format_name:"mov,mp4,m4a,3gp,3g2,mj2",duration:"15"},streams:[{codec_type:"video",codec_name:"h264",width:720,height:1280},{codec_type:"audio",codec_name:"aac"}]};assert.equal(validateProbe(validRaw,100,Buffer.from("0000ftyp0000")).validation.valid,true);for(const mutate of [(x:any)=>x.streams[0].codec_name="vp9",(x:any)=>x.streams[1].codec_name="mp3",(x:any)=>x.format.duration="2",(x:any)=>x.streams[0].width=640,(x:any)=>x.format.format_name="matroska,webm"]){const value=structuredClone(validRaw);mutate(value);assert.equal(validateProbe(value,100,Buffer.from("0000ftyp0000")).validation.valid,false)}assert.equal(validateProbe(validRaw,100,Buffer.from("not-an-mp4-header")).validation.valid,false,"spoofed extension/MIME cannot replace the byte signature");assert.equal(validateProbe(validRaw,100*1024*1024+1,Buffer.from("0000ftyp0000")).validation.valid,false);
  const notApproved=approvedRun("");delete notApproved.generation!.boardApprovedAt;const readiness=calculateReadiness(notApproved);assert.equal(readiness.valid,false);assert.ok(readiness.blockers.some(x=>x.code==="storyboard_missing"));
  const legacy=approvedRun("");legacy.pack={...pack,title:pack.platforms.youtube_shorts.title,captions:[{platform:"youtube_shorts",caption:pack.platforms.youtube_shorts.description},{platform:"instagram_reels",caption:pack.platforms.instagram_reels.caption},{platform:"linkedin",caption:pack.platforms.linkedin.commentary}],hashtags:pack.platforms.instagram_reels.hashtags,postingNotes:pack.platforms.instagram_reels.postingNotes,approved:true};legacy.currentStage="done";const view=releaseReadView(legacy);assert.equal(view.release?.packVersions[0].origin,"legacy_sample");assert.equal(view.currentStage,"pack");assert.equal(legacy.release,undefined,"read compatibility must not rewrite the stored object");
});

test("an injected Pack provider result is not repeated by a storage conflict",async()=>{let providerCalls=0,revision=1,commits=0;const run=approvedRun(""),provider=async()=>{providerCalls++;return packFixture(run)},result=await provider();const saved=await optimisticRunUpdate(async()=>({run:structuredClone(run),revision}),async(next)=>{commits++;if(commits===1){revision++;return false}Object.assign(run,next);return true},next=>{next.job={id:"pack-job",kind:"pack",status:"running",checkpoint:"pack-result",startedAt:new Date().toISOString(),message:"",packDraft:result};});assert.equal(saved.job?.packDraft?.thumbnailText,result.thumbnailText);assert.equal(commits,2);assert.equal(providerCalls,1)});
