import test from "node:test";
import assert from "node:assert/strict";
import { mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { tmpdir } from "node:os";
import { LocalPublicationStorage, SupabasePublicationStorage } from "../src/publication-storage.js";
import type { ConnectionSecret, PlatformConnection } from "../src/publication-types.js";

const envelope={version:1 as const,keyId:"key",nonce:"nonce",tag:"tag",ciphertext:"cipher"};
function connection(revision=1,status:PlatformConnection["status"]="connected"):PlatformConnection{return{id:"50000000-0000-4000-8000-000000000001",ownerId:"10000000-0000-4000-8000-000000000001",provider:"youtube",accountId:"account",accountLabel:"Account",status,grantedScopes:["scope"],targets:[],revision,createdAt:"2026-10-02T00:00:00.000Z",updatedAt:`2026-10-02T00:00:0${revision}.000Z`,provenance:"live"};}
function secret(revision=1):ConnectionSecret{return{ownerId:connection().ownerId,connectionId:connection().id,envelope:{...envelope,ciphertext:`cipher-${revision}`},updatedAt:`2026-10-02T00:00:0${revision}.000Z`};}

test("local authorization journal recovers a first connection and its secret together",async()=>{const dir=await mkdtemp(`${tmpdir()}/vpo-connection-journal-`),publication=path.join(dir,"publication"),value=connection(),authorization=secret();await mkdir(publication,{recursive:true});await writeFile(path.join(publication,`connection-tx-${value.ownerId}-${value.id}.json`),JSON.stringify({kind:"authorize",connection:value,secret:authorization}),{mode:0o600});const store=new LocalPublicationStorage(dir);await store.init();try{assert.deepEqual(await store.getConnection(value.ownerId,value.id),value);assert.deepEqual(await store.getConnectionSecret(value.ownerId,value.id),authorization);}finally{await store.close();await rm(dir,{recursive:true,force:true});}});

test("local reconnect and refresh conflicts preserve the old metadata and authorization",async()=>{const dir=await mkdtemp(`${tmpdir()}/vpo-connection-cas-`),store=new LocalPublicationStorage(dir);await store.init();try{const first=connection();await store.commitConnectionAuthorization(first,secret());for(const label of ["reconnect","refresh"]){await assert.rejects(()=>store.commitConnectionAuthorization({...first,revision:2,accountLabel:label},secret(2),99),/changed/);assert.equal((await store.getConnection(first.ownerId,first.id)).accountLabel,"Account");assert.equal((await store.getConnectionSecret(first.ownerId,first.id)).envelope.ciphertext,"cipher-1");}}finally{await store.close();await rm(dir,{recursive:true,force:true});}});

test("local disconnect conflict cannot remove a winning authorization",async()=>{const dir=await mkdtemp(`${tmpdir()}/vpo-disconnect-cas-`),store=new LocalPublicationStorage(dir);await store.init();try{const first=connection();await store.commitConnectionAuthorization(first,secret());await assert.rejects(()=>store.disconnectConnection({...first,status:"disconnected",revision:2},99),/changed/);assert.equal((await store.getConnection(first.ownerId,first.id)).status,"connected");assert.equal((await store.getConnectionSecret(first.ownerId,first.id)).envelope.ciphertext,"cipher-1");const disconnected=await store.disconnectConnection({...first,status:"disconnected",revision:2},1);assert.equal(disconnected.status,"disconnected");await assert.rejects(()=>store.getConnectionSecret(first.ownerId,first.id),/not found/);}finally{await store.close();await rm(dir,{recursive:true,force:true});}});

test("Supabase authorization and disconnect use service RPCs and surface CAS conflicts",async()=>{const calls:{name:string;args:Record<string,unknown>}[]=[],results=[true,false,false,false],client={rpc:async(name:string,args:Record<string,unknown>)=>{calls.push({name,args});return{data:results.shift(),error:null};}} as any,store=new SupabasePublicationStorage(client),first=connection();assert.equal((await store.commitConnectionAuthorization(first,secret())).id,first.id);for(const operation of ["reconnect","refresh"]){await assert.rejects(()=>store.commitConnectionAuthorization({...first,revision:2,accountLabel:operation},secret(2),1),/changed/);}await assert.rejects(()=>store.disconnectConnection({...first,status:"disconnected",revision:2},1),/changed/);assert.deepEqual(calls.map(value=>value.name),["commit_platform_connection_authorization","commit_platform_connection_authorization","commit_platform_connection_authorization","disconnect_platform_connection"]);assert.equal(calls[0].args.p_expected_revision,null);assert.equal(calls[1].args.p_expected_revision,1);assert.equal(calls[3].args.p_provider,"youtube");});
