import test from "node:test";
import assert from "node:assert/strict";
import { Readable } from "node:stream";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import type { FinalMediaVersion, ReleaseApproval, Run } from "../../frontend/lib/types.js";
import { approvedRun } from "./fixtures.js";
import { activePack, applyApproval, applyMediaVersion, applyPackVersion, calculateReadiness, ensureRelease, preparePackVersion, readinessFingerprint, RELEASE_POLICY_FINGERPRINT, storyboardLineage } from "../src/release.js";
import { packFixture } from "../src/pack.js";
import { approvalFingerprint, confirmationFor, connectionBlockers, prepareBatch, publicationHash, saveBinding } from "../src/publication.js";
import { emptyPublication, type PlatformConnection, type PublicationAggregate, type PublicationIntent, type PublicationJob } from "../src/publication-types.js";
import { TestPublishingAdapter } from "../src/provider-adapters.js";
import { decryptSecret, encryptSecret, parseKeyRing } from "../src/token-vault.js";
import { assertProviderUrl } from "../src/provider-http.js";
import { LocalPublicationStorage } from "../src/publication-storage.js";

function ready(destinations:Run["brief"]["platform"][]=["youtube_shorts","instagram_reels","linkedin"]){const run=approvedRun(),lineage=storyboardLineage(run)!,pack=preparePackVersion(run,packFixture(run),"generated","Generated",run.userId,{id:"10000000-0000-4000-8000-000000000001",createdAt:"2026-10-01T00:00:00.000Z",provenance:"test"});applyPackVersion(run,pack,0);const media:FinalMediaVersion={id:"20000000-0000-4000-8000-000000000001",version:1,assetId:"30000000-0000-4000-8000-000000000001",storyboardLineage:lineage,originalSafeFilename:"final.mp4",detectedMediaType:"video/mp4",byteSize:5,sha256:"a".repeat(64),probe:{container:"mp4",videoCodec:"h264",audioCodecs:["aac"],durationSeconds:15,codedWidth:720,codedHeight:1280,displayWidth:720,displayHeight:1280,rotation:0},validation:{valid:true,policyVersion:"test",blockers:[],warnings:[],checkedAt:"2026-10-01T00:01:00.000Z"},createdAt:"2026-10-01T00:01:00.000Z",createdBy:run.userId};applyMediaVersion(run,media,1,undefined);run.release!.selectedDestinations=destinations;run.release!.destinationRevision=1;run.release!.revision++;calculateReadiness(run,"2026-10-01T00:02:00.000Z");const fp=readinessFingerprint(run)!,approval:ReleaseApproval={id:"40000000-0000-4000-8000-000000000001",version:1,ownerId:run.userId,runId:run.id,approvalEpoch:0,storyboardLineage:lineage,packVersionId:pack.id,packProvenance:"test",policyFingerprint:RELEASE_POLICY_FINGERPRINT,mediaVersionId:media.id,mediaSha256:media.sha256,destinations,readinessFingerprint:fp,approvedAt:"2026-10-01T00:03:00.000Z",approvedBy:run.userId};applyApproval(run,approval,3,approval.approvedAt);return run;}
function connections(run:Run):PlatformConnection[]{return(["youtube","instagram","linkedin"] as const).map((provider,index)=>({id:`50000000-0000-4000-8000-00000000000${index+1}`,ownerId:run.userId,provider,accountId:"simulated:success",accountLabel:provider,status:"connected",grantedScopes:["simulated_publish"],targets:[{id:`${provider}-target`,type:provider==="youtube"?"channel":provider==="instagram"?"instagram_account":"member",label:provider,eligible:true,capabilityRevision:1}],revision:1,createdAt:"fixed",updatedAt:"fixed",provenance:"test"}));}
function bound(run:Run,all=connections(run)){let aggregate=emptyPublication(run.userId,run.id);for(const [platform,connection] of (["youtube_shorts","instagram_reels","linkedin"] as const).map((platform,index)=>[platform,all[index]] as const)){aggregate=saveBinding(aggregate,{platform,connectionId:connection.id,targetId:connection.targets[0].id,targetType:connection.targets[0].type,targetLabel:connection.targets[0].label,capabilityRevision:1},0,"fixed");}return aggregate;}

test("exact approval and canonical target bindings produce stable per-destination idempotency",()=>{const run=ready(),all=connections(run),aggregate=bound(run,all),confirmation=confirmationFor(run,aggregate)("private"),ids=["61000000-0000-4000-8000-000000000001","61000000-0000-4000-8000-000000000002","61000000-0000-4000-8000-000000000003"],jobs=["62000000-0000-4000-8000-000000000001","62000000-0000-4000-8000-000000000002","62000000-0000-4000-8000-000000000003"],input={approvalId:run.release!.activeApprovalId!,confirmationFingerprint:confirmation,bindingRevisions:Object.fromEntries(aggregate.bindings.map(v=>[v.platform,v.revision])),youtubePrivacy:"private" as const,now:"fixed",batchId:"60000000-0000-4000-8000-000000000001",intentIds:ids,jobIds:jobs},first=prepareBatch(run,aggregate,all,input),repeat=prepareBatch(run,first.aggregate,all,{...input,batchId:"different",intentIds:ids.map(v=>v.replace("61","71")),jobIds:jobs.map(v=>v.replace("62","72"))}),youtube=first.aggregate.intents.find(v=>v.platform==="youtube_shorts")!;assert.equal(first.jobs.length,3);assert.equal(new Set(first.aggregate.intents.map(v=>v.idempotencyFingerprint)).size,3);assert.equal(repeat.batch.id,first.batch.id);assert.equal(repeat.aggregate.intents.length,3);assert.equal(youtube.payload.title,activePack(run)!.content.platforms.youtube_shorts.title);});
test("every active approval mismatch blocks a fresh publication batch",()=>{for(const mutate of [(r:Run)=>{r.release!.approvalEpoch++;},(r:Run)=>{r.release!.mediaVersions[0].sha256="b".repeat(64);},(r:Run)=>{r.release!.activeApprovalId=undefined;},(r:Run)=>{r.release!.supersessions.push({approvalId:r.release!.activeApprovalId!,at:"later",reason:"reopened",releaseRevision:4});r.release!.activeApprovalId=undefined;}]){const run=ready(),all=connections(run),aggregate=bound(run,all);mutate(run);assert.throws(()=>approvalFingerprint(run),/exact current approved release/);assert.ok(connectionBlockers(run,aggregate,all).length);}});
test("target changes supersede only unstarted intent and reject retargeting after work starts",()=>{const run=ready(["youtube_shorts"]),all=connections(run),aggregate=saveBinding(emptyPublication(run.userId,run.id),{platform:"youtube_shorts",connectionId:all[0].id,targetId:all[0].targets[0].id,targetType:"channel",targetLabel:"old",capabilityRevision:1},0,"fixed"),confirmation=confirmationFor(run,aggregate)("private"),prepared=prepareBatch(run,aggregate,all,{approvalId:run.release!.activeApprovalId!,confirmationFingerprint:confirmation,bindingRevisions:{youtube_shorts:1},youtubePrivacy:"private",now:"fixed",batchId:"60000000-0000-4000-8000-000000000001",intentIds:["61000000-0000-4000-8000-000000000001"],jobIds:["62000000-0000-4000-8000-000000000001"]});const changed=saveBinding(prepared.aggregate,{platform:"youtube_shorts",connectionId:all[0].id,targetId:"new-target",targetType:"channel",targetLabel:"new",capabilityRevision:2},1,"later");assert.equal(changed.intents[0].status,"superseded");assert.equal(changed.jobs[0].state,"superseded");const started=structuredClone(prepared.aggregate);started.intents[0].status="started";assert.throws(()=>saveBinding(started,{platform:"youtube_shorts",connectionId:all[0].id,targetId:"new",targetType:"channel",targetLabel:"new",capabilityRevision:2},1,"later"),/cannot be changed/);});
test("TEST adapter uses the shared checkpoint machine and cannot call fetch",async()=>{const oldFetch=globalThis.fetch;let calls=0;globalThis.fetch=(async()=>{calls++;throw new Error("network denied");}) as typeof fetch;try{const run=ready(["youtube_shorts"]),all=connections(run),aggregate=saveBinding(emptyPublication(run.userId,run.id),{platform:"youtube_shorts",connectionId:all[0].id,targetId:all[0].targets[0].id,targetType:"channel",targetLabel:"youtube",capabilityRevision:1},0,"fixed"),confirmation=confirmationFor(run,aggregate)("private"),prepared=prepareBatch(run,aggregate,all,{approvalId:run.release!.activeApprovalId!,confirmationFingerprint:confirmation,bindingRevisions:{youtube_shorts:1},youtubePrivacy:"private",now:"fixed",batchId:"60000000-0000-4000-8000-000000000001",intentIds:["61000000-0000-4000-8000-000000000001"],jobIds:["62000000-0000-4000-8000-000000000001"]}),adapter=new TestPublishingAdapter(),intent=prepared.aggregate.intents[0];let job=prepared.jobs[0],out=await adapter.advance(job,intent,{connection:all[0],openMedia:async()=>({stream:Readable.from(Buffer.from("video")),byteSize:5,sha256:"a".repeat(64)})});assert.equal(out.state,"upload_session_created");job={...job,state:out.state,evidence:{...job.evidence,...out.evidence}};out=await adapter.advance(job,intent,{connection:all[0],openMedia:async()=>({stream:Readable.from(Buffer.from("video")),byteSize:5,sha256:"a".repeat(64)})});assert.equal(out.evidence?.uploadBytes,5);assert.equal(calls,0);}finally{globalThis.fetch=oldFetch;}});
test("simulated failure, reconnect, processing and ambiguous outcomes stay independent",async()=>{const baseJob={id:"j",ownerId:"o",runId:"r",intentId:"i",platform:"linkedin",state:"queued",checkpoint:"prepared",revision:0,attemptCount:0,evidence:{},attempts:[],createdAt:"x",updatedAt:"x"} as PublicationJob,intent={id:"i",platform:"linkedin",target:{targetType:"member"}} as unknown as PublicationIntent,adapter=new TestPublishingAdapter();for(const [scenario,state] of [["failure","failed"],["reconnect","needs_reconnect"],["ambiguous","unknown"]] as const){const result=await adapter.advance(baseJob,intent,{connection:{accountId:`simulated:${scenario}`} as PlatformConnection,openMedia:async()=>({stream:Readable.from([]),byteSize:0,sha256:""})});assert.equal(result.state,state);}const processing=await adapter.advance({...baseJob,state:"upload_complete"},intent,{connection:{accountId:"simulated:processing"} as PlatformConnection,openMedia:async()=>({stream:Readable.from([]),byteSize:0,sha256:""})});assert.equal(processing.state,"provider_processing");assert.equal(processing.reschedule,false);});
test("AES-256-GCM envelopes bind owner/connection and support key rotation",()=>{const one=Buffer.alloc(32,1).toString("base64"),two=Buffer.alloc(32,2).toString("base64"),ring=parseKeyRing(JSON.stringify({one,two}),"two"),envelope=encryptSecret({accessToken:"secret"},"owner:connection",ring,"two");assert.equal(decryptSecret<{accessToken:string}>(envelope,"owner:connection",ring).accessToken,"secret");assert.throws(()=>decryptSecret(envelope,"other",ring),/could not be decrypted/);assert.throws(()=>parseKeyRing(JSON.stringify({bad:Buffer.alloc(8).toString("base64")}),"bad"),/32 bytes/);assert.throws(()=>decryptSecret(envelope,"owner:connection",new Map([["one",Buffer.alloc(32,1)]])),/unavailable/);});
test("provider URL validation rejects private DNS, unsafe schemes and unapproved redirects",async()=>{const publicResolve=(async()=>[{address:"142.250.1.1",family:4}]) as any,privateResolve=(async()=>[{address:"127.0.0.1",family:4}]) as any;assert.equal((await assertProviderUrl("https://www.googleapis.com/upload",publicResolve)).hostname,"www.googleapis.com");await assert.rejects(()=>assertProviderUrl("http://www.googleapis.com/upload",publicResolve),/HTTPS/);await assert.rejects(()=>assertProviderUrl("https://evil.example/upload",publicResolve),/not allowed/);await assert.rejects(()=>assertProviderUrl("https://www.googleapis.com/upload",privateResolve),/unsafe/);});
test("OAuth state is owner-bound, expiring and consumed exactly once",async()=>{const dir=await mkdtemp(`${tmpdir()}/vpo-step5c-oauth-`),store=new LocalPublicationStorage(dir);await store.init();try{const record={id:"state-id",stateHash:"a".repeat(64),ownerId:"owner-a",provider:"youtube" as const,initiationId:"init",returnPath:"/runs/run",cookieHash:"b".repeat(64),expiresAt:"2026-10-02T01:00:00.000Z"};await store.createOAuthState(record);await assert.rejects(()=>store.consumeOAuthState(record.stateHash,"linkedin",record.cookieHash,"2026-10-02T00:00:00.000Z"),/invalid/);await assert.rejects(()=>store.consumeOAuthState(record.stateHash,"youtube","c".repeat(64),"2026-10-02T00:00:00.000Z"),/invalid/);assert.equal((await store.consumeOAuthState(record.stateHash,"youtube",record.cookieHash,"2026-10-02T00:00:00.000Z")).ownerId,"owner-a");await assert.rejects(()=>store.consumeOAuthState(record.stateHash,"youtube",record.cookieHash,"2026-10-02T00:00:01.000Z"),/already been used/);const expired={...record,id:"expired",stateHash:"d".repeat(64),expiresAt:"2026-10-01T00:00:00.000Z"};await store.createOAuthState(expired);await assert.rejects(()=>store.consumeOAuthState(expired.stateHash,"youtube",expired.cookieHash,"2026-10-02T00:00:00.000Z"),/expired/);}finally{await store.close();await rm(dir,{recursive:true,force:true});}});
test("publication storage rejects cross-owner connection and aggregate reads",async()=>{const dir=await mkdtemp(`${tmpdir()}/vpo-step5c-owner-`),store=new LocalPublicationStorage(dir);await store.init();try{const item=connections(ready())[0];await store.putConnection(item);await assert.rejects(()=>store.getConnection("22222222-2222-4222-8222-222222222222",item.id),/not found/);const aggregate=emptyPublication(item.ownerId,"run-a"),saved=await store.putAggregate(aggregate,0);assert.equal(saved.ownerId,item.ownerId);assert.equal((await store.getAggregate("22222222-2222-4222-8222-222222222222","run-a")).jobs.length,0);await assert.rejects(()=>store.putAggregate({...saved,ownerId:"22222222-2222-4222-8222-222222222222"},saved.revision),/changed/);}finally{await store.close();await rm(dir,{recursive:true,force:true});}});
test("canonical publication hashes ignore object insertion order",()=>{assert.equal(publicationHash({a:1,b:{c:2,d:3}}),publicationHash({b:{d:3,c:2},a:1}));});
