begin;
create extension if not exists pgtap with schema extensions;
select plan(14);
select has_table('public','platform_connections','connection metadata exists');
select has_table('public','platform_connection_secrets','connection secret store exists');
select has_table('public','oauth_states','OAuth state store exists');
select has_table('public','publication_runs','publication aggregate exists');
select has_table('public','publication_idempotency','idempotency registry exists');
select has_table('public','publication_job_secrets','job secret store exists');
select ok((select relrowsecurity from pg_class where oid='public.platform_connections'::regclass),'connections use RLS');
select ok((select relrowsecurity from pg_class where oid='public.publication_runs'::regclass),'publication records use RLS');
select isnt(has_table_privilege('authenticated','public.platform_connections','select'),true,'browser cannot read connections directly');
select isnt(has_table_privilege('authenticated','public.platform_connection_secrets','select'),true,'browser cannot read tokens');
select isnt(has_table_privilege('authenticated','public.oauth_states','select'),true,'browser cannot read OAuth state');
select isnt(has_table_privilege('authenticated','public.publication_idempotency','select'),true,'browser cannot read idempotency records');
select isnt(has_table_privilege('authenticated','public.publication_job_secrets','select'),true,'browser cannot read upload secrets');
select isnt(has_function_privilege('authenticated','public.consume_oauth_state(text,text,text,timestamp with time zone)','execute'),true,'browser cannot consume OAuth state');
select * from finish();
rollback;
