import test,{afterEach,before}from"node:test";
import assert from"node:assert/strict";
import{JSDOM}from"jsdom";
import React from"react";
import type{PublicationView,Run}from"../lib/types";
let render:typeof import("@testing-library/react")["render"],fireEvent:typeof import("@testing-library/react")["fireEvent"],screen:typeof import("@testing-library/react")["screen"],waitFor:typeof import("@testing-library/react")["waitFor"],cleanup:typeof import("@testing-library/react")["cleanup"];
before(async()=>{const dom=new JSDOM("<!doctype html><html><body></body></html>",{url:"http://localhost"});for(const[name,value]of Object.entries({window:dom.window,document:dom.window.document,navigator:dom.window.navigator,HTMLElement:dom.window.HTMLElement,Node:dom.window.Node,Event:dom.window.Event,MouseEvent:dom.window.MouseEvent}))Object.defineProperty(globalThis,name,{configurable:true,value});({render,fireEvent,screen,waitFor,cleanup}=await import("@testing-library/react"));});afterEach(()=>cleanup());
const run={id:"run",userId:"user",mode:"test",currentStage:"done",release:{activeApprovalId:"approval",selectedDestinations:["youtube_shorts"],packVersions:[],mediaVersions:[],approvals:[]}}as unknown as Run;
const connection={id:"connection",ownerId:"user",provider:"youtube"as const,accountId:"simulated:success",accountLabel:"Simulated YouTube",status:"connected"as const,grantedScopes:["simulated_publish"],targets:[{id:"target",type:"channel"as const,label:"Channel",eligible:true,capabilityRevision:1}],revision:1,createdAt:"fixed",updatedAt:"fixed",provenance:"test"as const};
const capabilities=[{provider:"youtube"as const,configured:true,available:true,status:"available"as const},{provider:"instagram"as const,configured:false,available:false,status:"not_configured"as const},{provider:"linkedin"as const,configured:false,available:false,status:"not_configured"as const}];
function view(overrides:Partial<PublicationView>={}):PublicationView{return{publishingMode:"test",aiProvenance:"test",providerCapabilities:capabilities,approvalId:"approval",approvalFingerprint:"a".repeat(64),confirmationFingerprint:"b".repeat(64),connections:[connection],aggregate:{revision:1,bindings:[{platform:"youtube_shorts",connectionId:"connection",targetId:"target",targetType:"channel",targetLabel:"Channel",capabilityRevision:1,revision:1,updatedAt:"fixed"}],batches:[],jobs:[]},blockers:[],...overrides};}
function requests(initial:PublicationView,spies:{published?:()=>void;saved?:()=>void;retried?:(id:string)=>void;reconciled?:(id:string)=>void;reconnected?:(id:string)=>void}={}){const current=initial;return{load:async()=>current,simulate:async()=>connection,reconnectSimulated:async(id:string)=>{spies.reconnected?.(id);return connection;},oauth:async()=>({authorizationUrl:"https://accounts.google.com/"}),saveTarget:async()=>{spies.saved?.();return current.aggregate;},publish:async()=>{spies.published?.();return{batch:{},jobs:[],publicationRevision:2};},retry:async(_run:string,id:string)=>{spies.retried?.(id);return current.aggregate;},reconcile:async(_run:string,id:string)=>{spies.reconciled?.(id);return current.aggregate;},retryFailed:async()=>current.aggregate,disconnect:async()=>connection};}
test("publishing requires an explicit confirmation and unsaved targets block it",async()=>{const{default:PublishingPanel}=await import("../components/PublishingPanel");let published=0,saved=0;render(<PublishingPanel run={run} requests={requests(view(),{published:()=>published++,saved:()=>saved++}) as never}/>);await screen.findByText(/SIMULATED publishing only/);const button=screen.getByRole("button",{name:"Publish approved release"})as HTMLButtonElement;assert.equal(button.disabled,true);fireEvent.click(screen.getByLabelText(/I confirm these exact targets/));assert.equal(button.disabled,false);const select=screen.getByLabelText("Publishing target");fireEvent.change(select,{target:{value:"connection:target"}});assert.equal(button.disabled,true);assert.match(screen.getByRole("alert").textContent??"",/Save target changes/);fireEvent.click(screen.getByRole("button",{name:"Save target"}));await waitFor(()=>assert.equal(saved,1));});
test("one confirmed click calls publication once while the action is busy",async()=>{const{default:PublishingPanel}=await import("../components/PublishingPanel");let resolve!:()=>void,calls=0;const mock=requests(view());mock.publish=async()=>{calls++;await new Promise<void>(value=>{resolve=value;});return{batch:{},jobs:[],publicationRevision:2};};render(<PublishingPanel run={run} requests={mock as never}/>);await screen.findByText(/SIMULATED publishing only/);fireEvent.click(screen.getByLabelText(/I confirm these exact targets/));const button=screen.getByRole("button",{name:"Publish approved release"})as HTMLButtonElement;fireEvent.click(button);fireEvent.click(button);assert.equal(calls,1);assert.equal(button.disabled,true);resolve();});
test("partial success renders independently and unknown is reconciled rather than retried",async()=>{const{default:PublishingPanel}=await import("../components/PublishingPanel");const base={ownerId:"user",runId:"run",intentId:"intent",revision:1,attemptCount:1,backoffAttempt:0,evidence:{},attempts:[],createdAt:"fixed",updatedAt:"fixed"},jobs=[{...base,id:"published",platform:"youtube_shorts"as const,state:"externally_published"as const,checkpoint:"created",retrySafety:"none"as const,allowedAction:"none"as const,evidence:{videoId:"video",visibility:"private",inspectionUrl:"https://www.linkedin.com/feed/"}},{...base,id:"failed",platform:"instagram_reels"as const,state:"failed"as const,checkpoint:"rejected",retrySafety:"user_safe"as const,allowedAction:"retry"as const,sanitizedError:"Rejected"},{...base,id:"unknown",platform:"linkedin"as const,state:"unknown"as const,checkpoint:"response_lost",retrySafety:"reconcile_only"as const,allowedAction:"reconcile"as const,sanitizedError:"Unknown"}],item=view({aggregate:{...view().aggregate,jobs}}),retried:string[]=[],reconciled:string[]=[];run.release!.selectedDestinations=["youtube_shorts","instagram_reels","linkedin"];render(<PublishingPanel run={run} requests={requests(item,{retried:id=>retried.push(id),reconciled:id=>reconciled.push(id)})as never}/>);const inspection=await screen.findByRole("link",{name:"Inspect on provider"});assert.equal(inspection.getAttribute("href"),"https://www.linkedin.com/feed/");assert.equal(screen.getAllByRole("button",{name:"Retry this destination"}).length,1);assert.equal(screen.getAllByRole("button",{name:"Reconcile provider state"}).length,1);fireEvent.click(screen.getByRole("button",{name:"Retry this destination"}));await waitFor(()=>assert.deepEqual(retried,["failed"]));fireEvent.click(screen.getByRole("button",{name:"Reconcile provider state"}));await waitFor(()=>assert.deepEqual(reconciled,["unknown"]));});
test("reconnect acts on the exact bound connection while attention-only jobs expose no retry",async()=>{const{default:PublishingPanel}=await import("../components/PublishingPanel"),blockedConnection={...connection,status:"needs_reconnect"as const,revision:4},base={id:"reconnect-job",ownerId:"user",runId:"run",intentId:"bound-intent",platform:"youtube_shorts"as const,state:"needs_reconnect"as const,checkpoint:"authorization_rejected",revision:2,attemptCount:1,retrySafety:"reconnect_only"as const,allowedAction:"reconnect"as const,backoffAttempt:0,evidence:{},attempts:[],createdAt:"fixed",updatedAt:"fixed"},attention={...base,id:"attention-job",intentId:"attention-intent",state:"needs_attention"as const,retrySafety:"attention_only"as const,allowedAction:"inspect"as const},item=view({connections:[blockedConnection],aggregate:{...view().aggregate,intents:[{id:"bound-intent",connectionId:"connection",platform:"youtube_shorts"},{id:"attention-intent",connectionId:"connection",platform:"youtube_shorts"}],jobs:[base,attention]}}),reconnected:string[]=[];run.release!.selectedDestinations=["youtube_shorts"];render(<PublishingPanel run={run} requests={requests(item,{reconnected:id=>reconnected.push(id)})as never}/>);await screen.findByText(/Manual review is required/);assert.equal(screen.queryByRole("button",{name:"Retry this destination"}),null);fireEvent.click(screen.getByRole("button",{name:"Reconnect bound account"}));await waitFor(()=>assert.deepEqual(reconnected,["connection"]));});

test("provider capability gates Connect without hiding configured providers",async()=>{const{default:PublishingPanel}=await import("../components/PublishingPanel");run.release!.selectedDestinations=["youtube_shorts","instagram_reels","linkedin"];let simulated=0,oauth=0;const item=view({connections:[],aggregate:{...view().aggregate,bindings:[]}}),mock=requests(item);mock.simulate=async()=>{simulated++;return connection;};mock.oauth=async()=>{oauth++;return{authorizationUrl:"https://provider.invalid/"};};render(<PublishingPanel run={run} requests={mock as never}/>);const connect=await screen.findByRole("button",{name:"Connect YouTube Shorts"});assert.equal(screen.getAllByText("Not configured").length,2);assert.equal(screen.queryByRole("button",{name:/Connect Instagram|Connect LinkedIn/}),null);fireEvent.click(connect);await waitFor(()=>assert.equal(simulated,1));assert.equal(oauth,0);assert.doesNotMatch(document.body.textContent??"",/google-secret|meta-secret|linkedin-secret/i);});

test("provider controls stay inert while capability data is delayed or unavailable",async()=>{const{default:PublishingPanel}=await import("../components/PublishingPanel");run.release!.selectedDestinations=["youtube_shorts"];let resolve!:(value:PublicationView)=>void,oauth=0;const pending=new Promise<PublicationView>(value=>{resolve=value;}),mock=requests(view());mock.load=async()=>pending;mock.oauth=async()=>{oauth++;return{authorizationUrl:"https://provider.invalid/"};};render(<PublishingPanel run={run} requests={mock as never}/>);await screen.findByText("Loading provider availability…");assert.equal(screen.queryByRole("button",{name:/Connect/}),null);resolve(view({providerCapabilities:[]}));await screen.findByText("Availability unavailable");assert.equal(screen.queryByRole("button",{name:/Connect/}),null);assert.equal(oauth,0);});
