import test from "node:test";
import assert from "node:assert/strict";
import JSZip from "jszip";
import type {Run} from "../lib/types";
import {buildStoryboardZip,canExportStoryboard,storyboardExportFrames} from "../lib/export";

const pixel="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=";
function run():Run{return{id:"run-export",brief:{topic:"Export test",audience:"",platform:"youtube_shorts",aspectRatio:"16:9",durationSeconds:8,targetVideoModel:"Veo",sourceLinks:[],notes:"",pastedScript:null},frames:[],generation:{boardApprovedAt:"2026-10-02T00:00:00.000Z",revision:1,storyApproved:true,directionsReady:true,prompts:[],keys:[],archivedBoards:[],quotes:[],activities:[],manualRegenerations:0,limits:{promptThreshold:75,promptRewrites:2,frameThreshold:70,autoRegenerations:1,manualRegenerations:6,maxFrames:6,uploadBytes:1},board:[{id:"frame-2",order:1,beatIds:["beat-2"],instruction:"Second frame",isKey:false,complete:true,retryLimitReached:false,selectedAttemptId:"attempt-2",attempts:[{id:"discarded",assetId:"asset-old",imageUrl:"/api/images/old",attempt:1,jobId:"job",note:"",origin:"user",source:"generated",callIds:[],createdAt:"now"},{id:"attempt-2",assetId:"asset-2",imageUrl:"/api/images/2",attempt:2,jobId:"job",note:"",origin:"user",source:"generated",callIds:[],createdAt:"now"}]},{id:"frame-1",order:0,beatIds:["beat-1"],instruction:"Opening frame",isKey:true,complete:true,retryLimitReached:false,selectedAttemptId:"attempt-1",attempts:[{id:"attempt-1",assetId:"asset-1",imageUrl:pixel,attempt:1,jobId:"job",note:"",origin:"user",source:"uploaded",callIds:[],createdAt:"now"}]}]},userId:"user",currentStage:"pack",jobStatus:"needs_review",autopilot:false,runningCostUsd:0,createdAt:"now",updatedAt:"now",sources:[],facts:[],script:null,directions:[],selectedDirectionId:null,directionNote:"",videoPrompt:null,pack:null,aiCallLog:[]} as Run;}

test("Storyboard export contains only the ordered selected attempts and a manifest",async()=>{const value=run(),requested:string[]=[];assert.equal(canExportStoryboard(value),true);assert.deepEqual(storyboardExportFrames(value).map(frame=>frame.attemptId),["attempt-1","attempt-2"]);const blob=await buildStoryboardZip(value,async(path)=>{requested.push(path);return new Blob(["protected-image"],{type:"image/png"});});assert.deepEqual(requested,["/api/images/2"]);const zip=await JSZip.loadAsync(await blob.arrayBuffer());assert.ok(zip.file("frames/01-key-frame.png"));assert.ok(zip.file("frames/02-storyboard-frame.png"));assert.equal(zip.file("frames/old.png"),null);const manifest=JSON.parse(await zip.file("storyboard-manifest.json")!.async("string"));assert.deepEqual(manifest.frames.map((frame:{attemptId:string})=>frame.attemptId),["attempt-1","attempt-2"]);assert.equal(JSON.stringify(manifest).includes("/api/images/"),false,"manifest omits protected URLs");});
