"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { PublicationView, ReleaseDestination, Run } from "@/lib/types";
import { disconnectConnection, getPublications, publishApproved, reconcilePublication, reconnectSimulatedConnection, retryFailedPublications, retryPublication, savePublicationTarget, simulateConnection, startOAuth } from "@/lib/api";

const entries:[ReleaseDestination,"youtube"|"instagram"|"linkedin",string][]=[["youtube_shorts","youtube","YouTube Shorts"],["instagram_reels","instagram","Instagram Reels"],["linkedin","linkedin","LinkedIn"]];
const terminal=new Set(["externally_published","failed","needs_reconnect","needs_attention","unknown","superseded"]);
type Requests={load:typeof getPublications;simulate:typeof simulateConnection;reconnectSimulated:typeof reconnectSimulatedConnection;oauth:typeof startOAuth;saveTarget:typeof savePublicationTarget;publish:typeof publishApproved;retry:typeof retryPublication;reconcile:typeof reconcilePublication;retryFailed:typeof retryFailedPublications;disconnect:typeof disconnectConnection};
const defaults:Requests={load:getPublications,simulate:simulateConnection,reconnectSimulated:reconnectSimulatedConnection,oauth:startOAuth,saveTarget:savePublicationTarget,publish:publishApproved,retry:retryPublication,reconcile:reconcilePublication,retryFailed:retryFailedPublications,disconnect:disconnectConnection};
export default function PublishingPanel({run,requests=defaults}:{run:Run;requests?:Requests}){
  const[view,setView]=useState<PublicationView|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[dirty,setDirty]=useState<Record<string,string>>({}),[confirmed,setConfirmed]=useState(false),polling=useRef(false),privacy="private" as const;
  const refresh=useCallback(async()=>{if(polling.current)return;polling.current=true;try{setView(await requests.load(run.id));}catch(cause){setError((cause as Error).message);}finally{polling.current=false;}},[run.id,requests]);
  useEffect(()=>{const timer=setTimeout(()=>void refresh(),0);return()=>clearTimeout(timer);},[refresh,run.release?.activeApprovalId]);
  useEffect(()=>{if(!view?.aggregate.jobs.some(job=>!terminal.has(job.state)))return;const timer=setInterval(()=>void refresh(),1200);return()=>clearInterval(timer);},[view,refresh]);
  const selected=useMemo(()=>Object.fromEntries((view?.aggregate.bindings??[]).map(v=>[v.platform,`${v.connectionId}:${v.targetId}`])),[view]);
  async function action(work:()=>Promise<unknown>){setBusy(true);setError("");try{await work();await refresh();}catch(cause){setError((cause as Error).message);}finally{setBusy(false);}}
  async function connect(provider:"youtube"|"instagram"|"linkedin",connectionId?:string){const existing=view?.connections.find(v=>v.id===connectionId);if(view?.publishingMode==="test")await action(()=>existing?requests.reconnectSimulated(existing.id,existing.revision):requests.simulate(provider,provider==="youtube"?"success":provider==="instagram"?"processing":"failure"));else await action(async()=>{const result=await requests.oauth(provider,`/runs/${run.id}`,existing?.id,existing?.revision);window.location.assign(result.authorizationUrl);});}
  async function saveTarget(platform:ReleaseDestination,value:string){const[connectionId,targetId]=value.split(":"),prior=view?.aggregate.bindings.find(v=>v.platform===platform);await action(()=>requests.saveTarget(run.id,platform,connectionId,targetId,prior?.revision??0,view!.aggregate.revision));setDirty(current=>{const copy={...current};delete copy[platform];return copy;});setConfirmed(false);}
  async function publish(){if(!view?.approvalId||!view.confirmationFingerprint)return;const bindingRevisions=Object.fromEntries(view.aggregate.bindings.map(v=>[v.platform,v.revision]));await action(()=>requests.publish(run.id,{approvalId:view.approvalId!,confirmationFingerprint:view.confirmationFingerprint!,expectedPublicationRevision:view.aggregate.revision,bindingRevisions,youtubePrivacy:privacy,confirmExternalPublication:true}));setConfirmed(false);}
  const destinations=run.release?.selectedDestinations??[],hasDirty=Object.keys(dirty).length>0,canPublish=!!view?.approvalId&&!view.blockers.length&&!hasDirty&&confirmed&&!busy;
  return <section className="rounded-2xl border border-border bg-surface p-5 sm:p-6 space-y-5 min-w-0"><div><h2 className="text-lg font-semibold">Connections and publishing</h2><p className="text-sm text-muted">Publishing is {view?.publishingMode?.toUpperCase()??"loading"}. AI output is {(view?.aiProvenance??run.mode??"unknown").toUpperCase()}.</p>{view?.publishingMode==="test"&&<p className="text-sm text-warning">SIMULATED publishing only — no platform request or real post will be made.</p>}</div>
  <div className="grid gap-3 lg:grid-cols-3">{entries.filter(([platform])=>destinations.includes(platform)).map(([platform,provider,label])=>{const providerConnections=(view?.connections??[]).filter(v=>v.provider===provider),connections=providerConnections.filter(v=>v.status==="connected"),attentionConnection=providerConnections.find(v=>v.status!=="connected"),value=dirty[platform]??selected[platform]??"";return <article className="rounded-xl border border-border p-4 min-w-0" key={platform}><h3 className="font-semibold">{label}</h3>{connections.length?<><label className="block text-sm mt-3">Publishing target<select className="mt-1 w-full rounded-lg border border-border bg-background p-2" value={value} onChange={event=>setDirty(current=>({...current,[platform]:event.target.value}))}><option value="">Choose a target</option>{connections.flatMap(connection=>connection.targets.filter(t=>t.eligible).map(target=><option key={`${connection.id}:${target.id}`} value={`${connection.id}:${target.id}`}>{connection.accountLabel} · {target.label}</option>))}</select></label><button className="mt-2 rounded-lg border border-border px-3 py-2" disabled={busy||!dirty[platform]} onClick={()=>void saveTarget(platform,value)}>Save target</button>{connections.map(connection=><button key={connection.id} className="mt-2 ml-2 text-sm underline" disabled={busy} onClick={()=>void action(()=>requests.disconnect(connection.id,connection.revision))}>Disconnect</button>)}</>:<button className="mt-3 rounded-lg border border-border px-3 py-2" disabled={busy} onClick={()=>void connect(provider,attentionConnection?.id)}>{attentionConnection?"Reconnect":"Connect"} {label}</button>}</article>;})}</div>
  {hasDirty&&<p role="alert" className="text-warning">Save target changes before publishing.</p>}{view?.blockers.map(item=><p role="alert" className="text-warning" key={item}>{item}</p>)}{error&&<p role="alert" className="text-warning">{error}</p>}
  {!!view?.approvalId&&<div className="rounded-xl border border-border p-4 space-y-3"><h3 className="font-semibold">Final publishing confirmation</h3><p className="text-sm">Approval <span className="break-all">{view.approvalId}</span> · {destinations.length} destination(s) · YouTube privacy: private.</p><p className="text-sm">In LIVE mode this creates external posts and they may not be reversible from VPO Studio.</p><label className="flex gap-2 items-start"><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/><span>I confirm these exact targets and want to publish this approved release.</span></label><button className="rounded-lg bg-accent px-4 py-3 font-medium" disabled={!canPublish} onClick={()=>void publish()}>Publish approved release</button></div>}
  <div className="space-y-3"><h3 className="font-semibold">Destination jobs</h3>{view?.aggregate.jobs.map(job=>{const intent=view.aggregate.intents?.find(v=>v.id===job.intentId),connection=view.connections.find(v=>v.id===intent?.connectionId),provider=entries.find(v=>v[0]===job.platform)?.[1]??"youtube";return <article className="rounded-xl border border-border p-4 min-w-0" key={job.id}><div className="flex flex-wrap justify-between gap-2"><strong>{entries.find(v=>v[0]===job.platform)?.[2]}</strong><span>{job.state.replaceAll("_"," ")}</span></div><p className="text-sm text-muted break-words">{job.checkpoint} · attempt {job.attemptCount}</p>{job.nextAttemptAt&&<p className="text-sm">Next safe check: {new Date(job.nextAttemptAt).toLocaleTimeString()}</p>}{job.evidence.processingState&&<p className="text-sm">Provider processing: {job.evidence.processingState}</p>}{job.evidence.visibility&&<p className="text-sm">Visibility: {job.evidence.visibility}</p>}{job.sanitizedError&&<p role="alert" className="text-warning">{job.sanitizedError} {job.nextAction}</p>}{job.state==="externally_published"&&(job.evidence.resultUrl?<a className="underline break-all" href={job.evidence.resultUrl} target="_blank" rel="noreferrer">Open provider result</a>:<p className="text-sm">Provider creation confirmed; no public result URL is available.</p>)}{job.allowedAction==="retry"&&<button className="mt-2 rounded-lg border border-border px-3 py-2" disabled={busy} onClick={()=>void action(()=>requests.retry(run.id,job.id,job.revision))}>Retry this destination</button>}{job.allowedAction==="reconcile"&&<button className="mt-2 rounded-lg border border-border px-3 py-2" disabled={busy} onClick={()=>void action(()=>requests.reconcile(run.id,job.id,job.revision))}>Reconcile provider state</button>}{job.allowedAction==="reconnect"&&<button className="mt-2 rounded-lg border border-border px-3 py-2" disabled={busy||!connection} onClick={()=>void connect(provider,connection?.id)}>Reconnect bound account</button>}{job.allowedAction==="inspect"&&<p className="mt-2 text-sm font-medium">Manual review is required; repeating this checkpoint is disabled.</p>}<details className="mt-2"><summary>Attempt history</summary>{job.attempts.map(item=><p className="text-xs mt-1" key={item.id}>{new Date(item.at).toLocaleString()} · {item.message}</p>)}</details></article>})}{view?.aggregate.jobs.some(job=>job.allowedAction==="retry"&&job.retrySafety==="user_safe")&&<button className="rounded-lg border border-border px-3 py-2" disabled={busy} onClick={()=>void action(()=>requests.retryFailed(run.id,view.aggregate.revision))}>Retry safe failed destinations only</button>}</div></section>;
}
