import { createHash } from "node:crypto";
import { mkdtemp, open, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { spawn } from "node:child_process";
import type { IncomingMessage } from "node:http";
import type { MediaProbeResult, ValidationIssue, ValidationResult } from "../../frontend/lib/types.js";
import { RELEASE_POLICY_VERSION } from "./release.js";
import { settings } from "./settings.js";

export const MAX_VIDEO_BYTES = settings.mediaUploadMaxBytes;
const maxVideoMegabytes = Math.floor(MAX_VIDEO_BYTES / (1024 * 1024));
const issue = (code:string,message:string,nextAction?:string):ValidationIssue=>({code,message,nextAction});
const statusError=(message:string,status:number)=>Object.assign(new Error(message),{status});

export function assertUploadLength(value:string|number|undefined){if(value===undefined)return;const size=Number(value);if(!Number.isFinite(size)||size<0)throw statusError("The upload size header is invalid.",400);if(size>MAX_VIDEO_BYTES)throw statusError(`The video is larger than the ${maxVideoMegabytes} MB deployment limit. Export a smaller MP4 and try again.`,413);}
export async function receiveUpload(req:IncomingMessage){assertUploadLength(req.headers["content-length"]);const dir=await mkdtemp(path.join(tmpdir(),"vpo-video-")),filePath=path.join(dir,"upload.bin"),handle=await open(filePath,"wx",0o600);let byteSize=0;const digest=createHash("sha256");try{for await(const value of req){const chunk=Buffer.isBuffer(value)?value:Buffer.from(value);byteSize+=chunk.length;if(byteSize>MAX_VIDEO_BYTES)throw statusError(`The video is larger than the ${maxVideoMegabytes} MB deployment limit. Export a smaller MP4 and try again.`,413);digest.update(chunk);await handle.write(chunk);}if(!byteSize)throw statusError("The uploaded video was empty.",422);await handle.close();return{dir,filePath,byteSize,sha256:digest.digest("hex")};}catch(error){await handle.close().catch(()=>{});await rm(dir,{recursive:true,force:true});throw error;}}
export async function cleanupUpload(dir:string){await rm(dir,{recursive:true,force:true});}

class ProbeGate{active=0;private waiting:(()=>void)[]=[];constructor(private limit:number){}async enter(){if(this.active>=this.limit)await new Promise<void>((resolve)=>this.waiting.push(resolve));this.active++;}leave(){this.active--;this.waiting.shift()?.();}}
export interface ProbeRunnerOptions{command?:string;timeoutMs?:number;stdoutLimit?:number;stderrLimit?:number;concurrency?:number;spawnProcess?:typeof spawn;}
export function createProbeRunner(options:ProbeRunnerOptions={}){const gate=new ProbeGate(options.concurrency??settings.mediaProbeConcurrency);return async(filePath:string):Promise<any>=>{await gate.enter();try{return await new Promise((resolve,reject)=>{const child=(options.spawnProcess??spawn)(options.command??settings.ffprobePath,["-v","error","-show_format","-show_streams","-of","json",filePath],{shell:false,stdio:["ignore","pipe","pipe"]});let stdout="",stderr="",settled=false;const finish=(action:()=>void)=>{if(settled)return;settled=true;clearTimeout(timer);action();};const fail=(message:string,status:number)=>finish(()=>{child.kill("SIGKILL");reject(statusError(message,status));});const timer=setTimeout(()=>fail("Video inspection timed out. Check ffprobe and try again.",503),options.timeoutMs??settings.mediaProbeTimeoutMs);child.stdout?.on("data",(value)=>{if(settled)return;stdout+=value;if(Buffer.byteLength(stdout)> (options.stdoutLimit??settings.mediaProbeStdoutBytes))fail("Video inspection returned too much metadata. Export a standard MP4 and try again.",422);});child.stderr?.on("data",(value)=>{if(settled)return;stderr+=value;if(Buffer.byteLength(stderr)>(options.stderrLimit??settings.mediaProbeStderrBytes))fail("Video inspection returned excessive error output. The file may be invalid.",422);});child.on("error",(error)=>finish(()=>reject(statusError(`Video inspection is unavailable: ${error.message}`,503))));child.on("close",(code)=>{if(settled)return;if(code!==0)return finish(()=>reject(statusError(`The file is corrupt or incomplete. Export a fresh MP4 and try again.${stderr?` (${stderr.trim().slice(0,160)})`:""}`,422)));try{const parsed=JSON.parse(stdout);finish(()=>resolve(parsed));}catch{finish(()=>reject(statusError("The video inspector returned unreadable metadata.",422)));}});});}finally{gate.leave();}};}
const defaultProbeRunner=createProbeRunner();

export function validateProbe(raw:any,byteSize:number,header?:Buffer,checkedAt=new Date().toISOString()):{probe:MediaProbeResult;validation:ValidationResult}{const blockers:ValidationIssue[]=[],warnings:ValidationIssue[]=[],streams=Array.isArray(raw?.streams)?raw.streams:[],video=streams.find((stream:any)=>stream.codec_type==="video"),audios=streams.filter((stream:any)=>stream.codec_type==="audio"),formatNames=String(raw?.format?.format_name??"").split(",");if(!header||header.length<12||header.subarray(4,8).toString("ascii")!=="ftyp"||!formatNames.includes("mp4"))blockers.push(issue("container","The file is not a detected MP4 container.","Export an MP4 file."));if(!video)blockers.push(issue("video_stream","The MP4 has no video track."));if(video&&video.codec_name!=="h264")blockers.push(issue("video_codec",`Video codec ${video.codec_name??"unknown"} is not H.264.`,"Export using H.264."));const audioCodecs=audios.map((stream:any)=>String(stream.codec_name??"unknown"));if(audioCodecs.some((codec:string)=>codec!=="aac"))blockers.push(issue("audio_codec",`Audio must be AAC when present; detected ${audioCodecs.join(", ")}.`,"Export audio as AAC."));const rotation=Number(video?.tags?.rotate??video?.side_data_list?.find((item:any)=>Number.isFinite(Number(item.rotation)))?.rotation??0),codedWidth=Number(video?.width??0),codedHeight=Number(video?.height??0),sideways=Math.abs(rotation)%180===90,displayWidth=sideways?codedHeight:codedWidth,displayHeight=sideways?codedWidth:codedHeight;if(video&&(displayWidth<=0||displayHeight<=0))blockers.push(issue("dimensions","The video dimensions could not be read.","Export a complete MP4 with valid dimensions."));else if(video&&![[1080,1920],[720,1280]].some(([width,height])=>displayWidth===width&&displayHeight===height))warnings.push(issue("dimensions_compatibility",`Detected ${displayWidth}×${displayHeight}. This is accepted by VPO, but each destination may apply its own aspect-ratio or resolution rules.`,"Review destination requirements before live publishing."));const durationSeconds=Number(raw?.format?.duration??video?.duration??0);if(!Number.isFinite(durationSeconds)||durationSeconds<=0)blockers.push(issue("duration","The video duration could not be read.","Export a complete MP4 with valid duration metadata."));if(byteSize>MAX_VIDEO_BYTES)blockers.push(issue("size",`The video is larger than ${maxVideoMegabytes} MB.`));const probe:MediaProbeResult={container:formatNames.includes("mp4")?"mp4":(formatNames[0]||"unknown"),videoCodec:String(video?.codec_name??"unknown"),audioCodecs,durationSeconds,codedWidth,codedHeight,displayWidth,displayHeight,rotation};return{probe,validation:{valid:blockers.length===0,policyVersion:RELEASE_POLICY_VERSION,blockers,warnings,checkedAt}};}
export async function probeVideo(filePath:string,byteSize:number,runner=defaultProbeRunner){const header=Buffer.alloc(32),handle=await open(filePath,"r"),checkedAt=new Date().toISOString();try{const[raw,read]=await Promise.all([runner(filePath),handle.read(header,0,32,0)]);return validateProbe(raw,byteSize,header.subarray(0,read.bytesRead),checkedAt);}finally{await handle.close().catch(()=>{});}}
export function safeFilename(value:string){const decoded=(()=>{try{return decodeURIComponent(value);}catch{return value;}})();return path.basename(decoded).replace(/[\x00-\x1f\x7f]/g,"").slice(0,180)||"finished-video.mp4";}
