import { lookup } from "node:dns/promises";
import { isIP } from "node:net";
import { settings } from "./settings.js";

const allowedExact=new Set(["accounts.google.com","oauth2.googleapis.com","www.googleapis.com","graph.instagram.com","api.instagram.com","rupload.facebook.com","www.linkedin.com","api.linkedin.com"]);
const signedSuffixes=[".googleusercontent.com",".linkedin-ei.com"];
function privateAddress(address:string){if(address==="::1"||address.startsWith("fc")||address.startsWith("fd")||address.startsWith("fe80:"))return true;const p=address.split(".").map(Number);return p.length===4&&(p[0]===10||p[0]===127||p[0]===0||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168));}
export async function assertProviderUrl(raw:string,resolve=lookup){const url=new URL(raw);if(url.protocol!=="https:"||url.username||url.password||url.port)throw new Error("Provider URL must use HTTPS without embedded credentials or a custom port.");const host=url.hostname.toLowerCase();if(!allowedExact.has(host)&&!signedSuffixes.some(suffix=>host.endsWith(suffix)))throw new Error("Provider URL host is not allowed.");const addresses=await resolve(host,{all:true});if(!addresses.length||addresses.some(item=>!isIP(item.address)||privateAddress(item.address)))throw new Error("Provider URL resolved to an unsafe address.");return url;}
async function bounded(response:Response){const reader=response.body?.getReader();if(!reader)return"";let size=0;const parts:Uint8Array[]=[];while(true){const item=await reader.read();if(item.done)break;size+=item.value.byteLength;if(size>settings.providerResponseLimitBytes){await reader.cancel();throw new Error("Provider response exceeded the safe size limit.");}parts.push(item.value);}return Buffer.concat(parts).toString("utf8");}
export async function providerFetch(url:string,init:RequestInit={},options:{allowAuthorization?:boolean;resolve?:typeof lookup;fetchImpl?:typeof fetch}={}){const checked=await assertProviderUrl(url,options.resolve);const headers=new Headers(init.headers);if(headers.has("authorization")&&!options.allowAuthorization)throw new Error("Authorization cannot be forwarded to this upload host.");const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),settings.providerTimeoutMs);try{const request:Record<string,unknown>={...init,headers,redirect:"manual",signal:controller.signal};if(init.body&&typeof(init.body as {pipe?:unknown}).pipe==="function")request.duplex="half";const response=await(options.fetchImpl??fetch)(checked,request as RequestInit);if(response.status>=300&&response.status<400)throw new Error("Provider redirects are not followed automatically.");const body=await bounded(response);return{status:response.status,ok:response.ok,headers:response.headers,body,json:<T>()=>{try{return JSON.parse(body) as T;}catch{throw new Error("Provider returned malformed JSON.");}}};}finally{clearTimeout(timer);}}
export function sanitizedProviderError(provider:string,status:number,requestId?:string){return`${provider} returned ${status}.${requestId?` Reference ${requestId}.`:""}`;}
