import type { Readable } from "node:stream";
import { settings } from "./settings.js";
import type { PlatformConnection, PublicationIntent, PublicationJob, PublicationState, ProviderEvidence, PublicationAction, RetrySafety } from "./publication-types.js";
import { providerFetch, sanitizedProviderError } from "./provider-http.js";

export type ProviderResponse = Awaited<ReturnType<typeof providerFetch>>;
export type ProviderTransport = (url:string,init?:RequestInit,options?:{allowAuthorization?:boolean})=>Promise<ProviderResponse>;
export interface AdapterContext { connection:PlatformConnection; token?:string; getMediaMetadata:()=>Promise<{byteSize:number;sha256:string}>; openMedia:(range?:{start:number;end:number})=>Promise<{stream:Readable;byteSize:number;sha256:string}>; jobSecret?:Record<string,unknown>; beforeEffect:(kind:"write"|"read")=>Promise<void>; }
export interface AdapterOutcome { state:PublicationState; checkpoint:string; evidence?:ProviderEvidence; jobSecret?:Record<string,unknown>; error?:string; nextAction?:string; retryClass?:PublicationJob["retryClass"]; retrySafety?:RetrySafety; allowedAction?:PublicationAction; reschedule?:boolean; retryAfterMs?:number; }
export interface PublishingAdapter { advance(job:PublicationJob,intent:PublicationIntent,context:AdapterContext):Promise<AdapterOutcome>; reconcile(job:PublicationJob,intent:PublicationIntent,context:AdapterContext):Promise<AdapterOutcome>; }

type Json=Record<string,any>;
const authFailure=(provider:string,status:number):AdapterOutcome=>({state:"needs_reconnect",checkpoint:"authorization_rejected",error:sanitizedProviderError(provider,status),nextAction:"Reconnect the exact account used by this publication.",retryClass:"auth",retrySafety:"reconnect_only",allowedAction:"reconnect"});
const retryAfter=(response:ProviderResponse)=>{const raw=response.headers.get("retry-after"),seconds=raw?Number(raw):NaN;return Number.isFinite(seconds)&&seconds>=0?Math.min(seconds*1000,300_000):undefined;};
const safeFailure=(provider:string,response:ProviderResponse,checkpoint:string):AdapterOutcome=>response.status===401||response.status===403?authFailure(provider,response.status):response.status===429||response.status>=500?{state:"failed",checkpoint,error:sanitizedProviderError(provider,response.status),nextAction:"Retry this saved checkpoint after the provider delay.",retryClass:response.status===429?"rate_limit":"transport",retrySafety:"user_safe",allowedAction:"retry",retryAfterMs:retryAfter(response)}:{state:"failed",checkpoint,error:sanitizedProviderError(provider,response.status),nextAction:"Review the account and approved payload before trying again.",retryClass:"payload",retrySafety:"attention_only",allowedAction:"inspect"};
function youtubeUploadUrl(raw:string){const value=new URL(raw);if(value.protocol!=="https:"||value.hostname!=="www.googleapis.com"||value.port||value.username||value.password)throw new Error("The saved YouTube upload session host is invalid.");return value.toString();}
async function consume(stream:Readable){for await(const _chunk of stream){} }
const before=(context:AdapterContext,kind:"write"|"read")=>(context as Partial<AdapterContext>).beforeEffect?.(kind)??Promise.resolve();

export class TestPublishingAdapter implements PublishingAdapter{
  async advance(job:PublicationJob,intent:PublicationIntent,context:AdapterContext):Promise<AdapterOutcome>{
    const scenario=context.connection.accountId.replace(/^simulated:/,"");
    if(scenario==="reconnect")return{state:"needs_reconnect",checkpoint:"authorization_rejected",error:"The simulated authorization expired.",nextAction:"Reconnect this simulated account.",retrySafety:"reconnect_only",allowedAction:"reconnect"};
    if(scenario==="failure")return{state:"failed",checkpoint:"provider_rejected",error:"The simulated provider rejected this publication.",nextAction:"Retry this destination after reviewing its test fixture.",retryClass:"transport",retrySafety:"user_safe",allowedAction:"retry"};
    if(scenario==="ambiguous")return{state:"unknown",checkpoint:"creation_outcome_unknown",error:"The simulated final response was lost.",nextAction:"Reconcile this destination; do not retry it blindly.",retryClass:"ambiguous",retrySafety:"reconcile_only",allowedAction:"reconcile"};
    if(job.state==="queued"){await before(context,"write");return{state:"upload_session_created",checkpoint:"simulated_upload_session_saved",evidence:{uploadSessionId:`SIM-${intent.platform}-${intent.id}`},reschedule:true,retrySafety:"automatic",allowedAction:"none"};}
    if(job.state==="upload_session_created"){await before(context,"write");const media=await context.openMedia();await consume(media.stream);return{state:"upload_complete",checkpoint:"simulated_bytes_accepted",evidence:{uploadBytes:media.byteSize,videoId:intent.platform==="youtube_shorts"?`SIM-VIDEO-${intent.id}`:undefined,containerId:intent.platform==="instagram_reels"?`SIM-CONTAINER-${intent.id}`:undefined,videoUrn:intent.platform==="linkedin"?`urn:li:video:SIM-${intent.id}`:undefined},reschedule:true,retrySafety:"automatic",allowedAction:"none"};}
    if(job.state==="upload_complete")return{state:"provider_processing",checkpoint:"simulated_provider_processing",evidence:{processingState:"PROCESSING"},reschedule:scenario!=="processing",retryAfterMs:25,retrySafety:"automatic",allowedAction:"reconcile"};
    if(job.state==="provider_processing"){await before(context,"read");return{state:"creation_pending",checkpoint:"simulated_content_ready",evidence:{processingState:"READY"},reschedule:true,retrySafety:"automatic",allowedAction:"none"};}
    await before(context,"write");return{state:"externally_published",checkpoint:"simulated_external_creation_confirmed",evidence:{mediaId:intent.platform==="instagram_reels"?`SIM-MEDIA-${intent.id}`:undefined,postId:intent.platform==="linkedin"?`SIM-POST-${intent.id}`:undefined,processingState:"COMPLETE",resultUrl:undefined,visibility:intent.youtubePrivacy,audience:intent.target.targetType},retrySafety:"none",allowedAction:"none"};
  }
  async reconcile(job:PublicationJob,intent:PublicationIntent,context:AdapterContext){await context.beforeEffect("read");if(job.state==="unknown")return{state:"externally_published" as const,checkpoint:"simulated_reconciliation_confirmed",evidence:{postId:`SIM-RECONCILED-${intent.id}`,processingState:"COMPLETE"},retrySafety:"none" as const,allowedAction:"none" as const};if(job.state==="provider_processing")return this.advance(job,intent,{...context,connection:{...context.connection,accountId:"simulated:success"}});return{state:job.state,checkpoint:job.checkpoint,retrySafety:job.retrySafety,allowedAction:job.allowedAction};}
}

export class YouTubeAdapter implements PublishingAdapter{
  constructor(private transport:ProviderTransport=providerFetch){}
  async advance(job:PublicationJob,intent:PublicationIntent,context:AdapterContext):Promise<AdapterOutcome>{
    const auth={Authorization:`Bearer ${context.token}`};
    if(job.state==="queued"){
      const media=await context.getMediaMetadata();await context.beforeEffect("write");
      const response=await this.transport("https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status",{method:"POST",headers:{...auth,"Content-Type":"application/json","X-Upload-Content-Type":"video/mp4","X-Upload-Content-Length":String(media.byteSize)},body:JSON.stringify({snippet:{title:intent.payload.title,description:intent.payload.description,tags:intent.payload.tags},status:{privacyStatus:intent.youtubePrivacy??"private"}})},{allowAuthorization:true});
      if(!response.ok)return safeFailure("YouTube",response,"session_rejected");const location=response.headers.get("location");if(!location)return{state:"unknown",checkpoint:"session_response_invalid",error:"YouTube did not return a resumable upload session.",retrySafety:"reconcile_only",allowedAction:"reconcile"};
      return{state:"upload_session_created",checkpoint:"resumable_session_saved",jobSecret:{uploadUrl:location,offset:0,totalBytes:media.byteSize},reschedule:true,retrySafety:"automatic",allowedAction:"none"};
    }
    if(job.state==="upload_session_created"||job.state==="uploading"){
      const uploadUrl=youtubeUploadUrl(String(context.jobSecret?.uploadUrl??"")),metadata=await context.getMediaMetadata(),offset=Number(context.jobSecret?.offset??0);if(offset<0||offset>metadata.byteSize)throw new Error("The saved YouTube upload offset is invalid.");const media=await context.openMedia(offset?{start:offset,end:metadata.byteSize-1}:undefined);await context.beforeEffect("write");
      const response=await this.transport(uploadUrl,{method:"PUT",headers:{...auth,"Content-Type":"video/mp4","Content-Length":String(media.byteSize),"Content-Range":`bytes ${offset}-${metadata.byteSize-1}/${metadata.byteSize}`},body:media.stream as any},{allowAuthorization:true});
      if(response.status===308){const match=response.headers.get("range")?.match(/^bytes=0-(\d+)$/),next=match?Number(match[1])+1:offset;return{state:"uploading",checkpoint:"youtube_bytes_committed",evidence:{uploadBytes:next},jobSecret:{...context.jobSecret,offset:next,totalBytes:metadata.byteSize},reschedule:true,retrySafety:"automatic",allowedAction:"reconcile"};}
      if(!response.ok){if(response.status===401||response.status===403)return authFailure("YouTube",response.status);return{state:"unknown",checkpoint:"upload_response_uncertain",error:sanitizedProviderError("YouTube",response.status),nextAction:"Reconcile the saved resumable session before any retry.",retryClass:"ambiguous",retrySafety:"reconcile_only",allowedAction:"reconcile"};}
      const data=response.json<Json>();if(!data.id)return{state:"unknown",checkpoint:"upload_result_unknown",error:"YouTube accepted the upload without a video ID.",retrySafety:"reconcile_only",allowedAction:"reconcile"};return{state:"upload_complete",checkpoint:"private_video_created",evidence:{videoId:String(data.id),uploadBytes:metadata.byteSize,visibility:intent.youtubePrivacy??"private"},reschedule:true,retrySafety:"automatic",allowedAction:"reconcile"};
    }
    const id=job.evidence.videoId;if(!id)return{state:"unknown",checkpoint:"video_id_missing",error:"The YouTube video ID is unavailable.",retrySafety:"reconcile_only",allowedAction:"reconcile"};await context.beforeEffect("read");const response=await this.transport(`https://www.googleapis.com/youtube/v3/videos?part=status,processingDetails&id=${encodeURIComponent(id)}`,{headers:auth},{allowAuthorization:true});if(!response.ok)return safeFailure("YouTube",response,"status_unavailable");const item=response.json<Json>().items?.[0],processing=String(item?.processingDetails?.processingStatus??"unknown");if(processing!=="succeeded")return{state:"provider_processing",checkpoint:"youtube_processing",evidence:{processingState:processing},reschedule:processing==="processing",retryAfterMs:retryAfter(response)??2000,retrySafety:"automatic",allowedAction:"reconcile"};return{state:"externally_published",checkpoint:"youtube_video_processed",evidence:{processingState:processing,videoId:id,visibility:String(item?.status?.privacyStatus??intent.youtubePrivacy??"private"),resultUrl:`https://www.youtube.com/watch?v=${encodeURIComponent(id)}`},retrySafety:"none",allowedAction:"none"};
  }
  async reconcile(job:PublicationJob,intent:PublicationIntent,context:AdapterContext){
    if((job.state==="upload_session_created"||job.state==="uploading"||job.state==="unknown")&&context.jobSecret?.uploadUrl){const metadata=await context.getMediaMetadata();await context.beforeEffect("read");const response=await this.transport(youtubeUploadUrl(String(context.jobSecret.uploadUrl)),{method:"PUT",headers:{Authorization:`Bearer ${context.token}`,"Content-Length":"0","Content-Range":`bytes */${metadata.byteSize}`}}, {allowAuthorization:true});if(response.status===308){const match=response.headers.get("range")?.match(/^bytes=0-(\d+)$/),offset=match?Number(match[1])+1:0;return{state:"uploading" as const,checkpoint:"youtube_session_reconciled",evidence:{uploadBytes:offset},jobSecret:{...context.jobSecret,offset,totalBytes:metadata.byteSize},reschedule:true,retrySafety:"automatic" as const,allowedAction:"reconcile" as const};}if(response.status===404)return{state:"needs_attention" as const,checkpoint:"youtube_session_expired",error:"The saved YouTube upload session expired.",nextAction:"Inspect the channel before authorizing a fresh upload.",retrySafety:"attention_only" as const,allowedAction:"inspect" as const};if(response.ok){const data=response.json<Json>();if(data.id)return{state:"upload_complete" as const,checkpoint:"private_video_reconciled",evidence:{videoId:String(data.id),visibility:intent.youtubePrivacy??"private"},reschedule:true,retrySafety:"automatic" as const,allowedAction:"reconcile" as const};}return{state:"unknown" as const,checkpoint:"youtube_reconciliation_inconclusive",error:"YouTube could not confirm the saved upload outcome.",nextAction:"Inspect the channel before starting another upload.",retrySafety:"reconcile_only" as const,allowedAction:"reconcile" as const};}if(job.state==="queued"||job.state==="upload_session_created"||job.state==="uploading")return{state:"unknown" as const,checkpoint:"expired_claim_without_session_evidence",error:"The previous YouTube worker may have created an upload session without saving its URL.",nextAction:"Inspect the channel before authorizing a new upload.",retrySafety:"attention_only" as const,allowedAction:"inspect" as const};return this.advance(job,intent,context);
  }
}

export class InstagramAdapter implements PublishingAdapter{async advance(){return{state:"needs_attention" as const,checkpoint:"live_binary_upload_unverified",error:"LIVE Instagram publishing is capability-blocked until the current Instagram Login private binary upload flow is verified from official documentation.",nextAction:"Verify the official private binary flow before enabling LIVE Instagram publication.",retrySafety:"attention_only" as const,allowedAction:"inspect" as const};}async reconcile(){return this.advance();}}

function linkedinCommentary(payload:Record<string,unknown>){const commentary=String(payload.commentary??"").trim(),hashtags=Array.isArray(payload.hashtags)?payload.hashtags.map(String).join(" "):"";return[commentary,hashtags].filter(Boolean).join("\n\n");}
function linkedinResultUrl(id:string){return/^urn:li:activity:\d+$/.test(id)?`https://www.linkedin.com/feed/update/${id}`:undefined;}
function validateInstructions(value:Json[],size:number){let expected=0;return value.map(item=>{const start=Number(item.firstByte),end=Number(item.lastByte),uploadUrl=String(item.uploadUrl??"");if(!Number.isInteger(start)||!Number.isInteger(end)||start!==expected||end<start||end>=size||!uploadUrl)throw new Error("LinkedIn returned invalid upload byte ranges.");expected=end+1;return{firstByte:start,lastByte:end,uploadUrl};}).map((item,index,array)=>{if(index===array.length-1&&item.lastByte!==size-1)throw new Error("LinkedIn upload instructions do not cover the approved file.");return item;});}
export class LinkedInAdapter implements PublishingAdapter{
  constructor(private transport:ProviderTransport=providerFetch){}
  private headers(token:string){return{Authorization:`Bearer ${token}`,"Linkedin-Version":settings.linkedinApiVersion,"X-Restli-Protocol-Version":"2.0.0","Content-Type":"application/json"};}
  async advance(job:PublicationJob,intent:PublicationIntent,context:AdapterContext):Promise<AdapterOutcome>{
    const headers=this.headers(context.token??"");
    if(job.state==="queued"){const media=await context.getMediaMetadata();await context.beforeEffect("write");const response=await this.transport("https://api.linkedin.com/rest/videos?action=initializeUpload",{method:"POST",headers,body:JSON.stringify({initializeUploadRequest:{owner:intent.target.targetId,fileSizeBytes:media.byteSize,uploadCaptions:false,uploadThumbnail:false}})},{allowAuthorization:true});if(!response.ok)return safeFailure("LinkedIn",response,"initialize_rejected");const value=response.json<Json>().value,videoUrn=String(value?.video??""),uploadToken=String(value?.uploadToken??"");let uploadInstructions;try{uploadInstructions=validateInstructions(value?.uploadInstructions??[],media.byteSize);}catch(error){return{state:"needs_attention",checkpoint:"initialize_response_invalid",error:(error as Error).message,retrySafety:"attention_only",allowedAction:"inspect"};}if(!videoUrn||!uploadToken||!uploadInstructions.length)return{state:"needs_attention",checkpoint:"initialize_response_invalid",error:"LinkedIn returned incomplete upload instructions.",retrySafety:"attention_only",allowedAction:"inspect"};return{state:"upload_session_created",checkpoint:"linkedin_instructions_saved",evidence:{videoUrn},jobSecret:{uploadInstructions,uploaded:[],uploadToken},reschedule:true,retrySafety:"automatic",allowedAction:"reconcile"};}
    if(job.state==="upload_session_created"||job.state==="uploading"){const instructions=(context.jobSecret?.uploadInstructions as Json[]|undefined)??[],uploaded=(context.jobSecret?.uploaded as Json[]|undefined)??[],instruction=instructions[uploaded.length];if(!instruction)return{state:"upload_complete",checkpoint:"linkedin_ranges_uploaded",reschedule:true,retrySafety:"automatic",allowedAction:"reconcile"};const start=Number(instruction.firstByte),end=Number(instruction.lastByte),media=await context.openMedia({start,end});await context.beforeEffect("write");const response=await this.transport(String(instruction.uploadUrl),{method:"PUT",headers:{"Content-Type":"application/octet-stream","Content-Length":String(media.byteSize)},body:media.stream as any});if(!response.ok)return{state:"unknown",checkpoint:"range_upload_uncertain",error:sanitizedProviderError("LinkedIn",response.status),nextAction:"Reconcile the instructed range before another upload.",retryClass:"ambiguous",retrySafety:"reconcile_only",allowedAction:"reconcile"};const etag=response.headers.get("etag");if(!etag)return{state:"needs_attention",checkpoint:"range_etag_missing",error:"LinkedIn accepted a part without returning its required ETag.",nextAction:"Inspect the upload before continuing; it cannot be finalized safely.",retrySafety:"attention_only",allowedAction:"inspect"};const nextUploaded=[...uploaded,{etag,firstByte:start,lastByte:end}],complete=nextUploaded.length===instructions.length;return{state:complete?"upload_complete":"uploading",checkpoint:complete?"linkedin_ranges_uploaded":"linkedin_range_uploaded",evidence:{uploadBytes:nextUploaded.reduce((n,item)=>n+Number(item.lastByte)-Number(item.firstByte)+1,0),videoUrn:job.evidence.videoUrn},jobSecret:{...context.jobSecret,uploaded:nextUploaded},reschedule:true,retrySafety:"automatic",allowedAction:"reconcile"};}
    if(job.state==="upload_complete"){const instructions=(context.jobSecret?.uploadInstructions as Json[]|undefined)??[],uploaded=(context.jobSecret?.uploaded as Json[]|undefined)??[];if(!instructions.length||uploaded.length!==instructions.length||uploaded.some((v,index)=>!v.etag||v.firstByte!==instructions[index].firstByte||v.lastByte!==instructions[index].lastByte))return{state:"needs_attention",checkpoint:"parts_incomplete",error:"LinkedIn upload parts are incomplete and cannot be finalized.",retrySafety:"attention_only",allowedAction:"inspect"};await context.beforeEffect("write");const response=await this.transport("https://api.linkedin.com/rest/videos?action=finalizeUpload",{method:"POST",headers,body:JSON.stringify({finalizeUploadRequest:{video:job.evidence.videoUrn,uploadToken:context.jobSecret?.uploadToken,uploadedPartIds:uploaded.map(v=>v.etag)}})},{allowAuthorization:true});if(!response.ok)return{state:"unknown",checkpoint:"finalize_uncertain",error:sanitizedProviderError("LinkedIn",response.status),retryClass:"ambiguous",retrySafety:"reconcile_only",allowedAction:"reconcile"};return{state:"provider_processing",checkpoint:"linkedin_video_processing",evidence:{processingState:"PROCESSING"},reschedule:true,retryAfterMs:retryAfter(response)??2000,retrySafety:"automatic",allowedAction:"reconcile"};}
    if(job.state==="provider_processing"){await context.beforeEffect("read");const urn=encodeURIComponent(job.evidence.videoUrn??""),response=await this.transport(`https://api.linkedin.com/rest/videos/${urn}`,{headers},{allowAuthorization:true});if(!response.ok)return safeFailure("LinkedIn",response,"video_status_unavailable");const status=String(response.json<Json>().status??"UNKNOWN");if(status!=="AVAILABLE")return{state:status==="PROCESSING_FAILED"?"failed":"provider_processing",checkpoint:"linkedin_video_processing",evidence:{processingState:status},reschedule:status!=="PROCESSING_FAILED",retryAfterMs:retryAfter(response)??2000,retrySafety:status==="PROCESSING_FAILED"?"attention_only":"automatic",allowedAction:status==="PROCESSING_FAILED"?"inspect":"reconcile"};return{state:"creation_pending",checkpoint:"linkedin_video_available",evidence:{processingState:status},reschedule:true,retrySafety:"automatic",allowedAction:"none"};}
    await context.beforeEffect("write");const response=await this.transport("https://api.linkedin.com/rest/posts",{method:"POST",headers,body:JSON.stringify({author:intent.target.targetId,commentary:linkedinCommentary(intent.payload),visibility:"PUBLIC",distribution:{feedDistribution:"MAIN_FEED",targetEntities:[],thirdPartyDistributionChannels:[]},content:{media:{id:job.evidence.videoUrn}},lifecycleState:"PUBLISHED",isReshareDisabledByAuthor:false})},{allowAuthorization:true});if(!response.ok){if(response.status===401||response.status===403)return authFailure("LinkedIn",response.status);return{state:response.status>=500?"unknown":"failed",checkpoint:response.status>=500?"linkedin_post_outcome_unknown":"linkedin_post_rejected",error:sanitizedProviderError("LinkedIn",response.status),retryClass:response.status>=500?"ambiguous":"payload",retrySafety:response.status>=500?"reconcile_only":"attention_only",allowedAction:response.status>=500?"reconcile":"inspect"};}const id=response.headers.get("x-restli-id");if(!id)return{state:"unknown",checkpoint:"linkedin_post_outcome_unknown",error:"LinkedIn did not return a post ID.",retrySafety:"reconcile_only",allowedAction:"reconcile"};return{state:"externally_published",checkpoint:"linkedin_post_created",evidence:{postId:id,audience:intent.target.targetType,resultUrl:linkedinResultUrl(id)},retrySafety:"none",allowedAction:"none"};
  }
  async reconcile(job:PublicationJob,_intent:PublicationIntent,context:AdapterContext){await context.beforeEffect("read");return{state:job.state,checkpoint:job.checkpoint,error:"LinkedIn cannot authoritatively reconcile this ambiguous post from the available saved evidence.",nextAction:"Inspect the selected LinkedIn account before deciding whether a new approval is required.",retrySafety:"attention_only" as const,allowedAction:"inspect" as const};}
}
export function adapterFor(platform:PublicationIntent["platform"]):PublishingAdapter{if(settings.publishMode==="test")return new TestPublishingAdapter();return platform==="youtube_shorts"?new YouTubeAdapter():platform==="instagram_reels"?new InstagramAdapter():new LinkedInAdapter();}
