import type { Readable } from "node:stream";
import { settings } from "./settings.js";
import type { PlatformConnection, PublicationIntent, PublicationJob, PublicationState, ProviderEvidence } from "./publication-types.js";
import { providerFetch, sanitizedProviderError } from "./provider-http.js";

export interface AdapterContext { connection:PlatformConnection; token?:string; openMedia:(range?:{start:number;end:number})=>Promise<{stream:Readable;byteSize:number;sha256:string}>; jobSecret?:Record<string,unknown>; }
export interface AdapterOutcome { state:PublicationState; checkpoint:string; evidence?:ProviderEvidence; jobSecret?:Record<string,unknown>; error?:string; nextAction?:string; retryClass?:PublicationJob["retryClass"]; reschedule?:boolean; }
export interface PublishingAdapter { advance(job:PublicationJob,intent:PublicationIntent,context:AdapterContext):Promise<AdapterOutcome>; reconcile(job:PublicationJob,intent:PublicationIntent,context:AdapterContext):Promise<AdapterOutcome>; revoke?(context:AdapterContext):Promise<void>; }

async function consume(stream:Readable){for await(const _chunk of stream){} }
export class TestPublishingAdapter implements PublishingAdapter{
  async advance(job:PublicationJob,intent:PublicationIntent,context:AdapterContext):Promise<AdapterOutcome>{const scenario=context.connection.accountId.replace(/^simulated:/,"");if(scenario==="reconnect")return{state:"needs_reconnect",checkpoint:"authorization_rejected",error:"The simulated authorization expired.",nextAction:"Reconnect this simulated account."};if(scenario==="failure")return{state:"failed",checkpoint:"provider_rejected",error:"The simulated provider rejected this publication.",nextAction:"Retry this destination after reviewing its test fixture.",retryClass:"payload"};if(scenario==="ambiguous")return{state:"unknown",checkpoint:"creation_outcome_unknown",error:"The simulated final response was lost.",nextAction:"Reconcile this destination; do not retry it blindly.",retryClass:"ambiguous"};if(job.state==="queued"){return{state:"upload_session_created",checkpoint:"simulated_upload_session_saved",evidence:{uploadSessionId:`SIM-${intent.platform}-${intent.id}`},reschedule:true};}if(job.state==="upload_session_created"){const media=await context.openMedia();await consume(media.stream);return{state:"upload_complete",checkpoint:"simulated_bytes_accepted",evidence:{uploadBytes:media.byteSize,videoId:intent.platform==="youtube_shorts"?`SIM-VIDEO-${intent.id}`:undefined,containerId:intent.platform==="instagram_reels"?`SIM-CONTAINER-${intent.id}`:undefined,videoUrn:intent.platform==="linkedin"?`urn:li:video:SIM-${intent.id}`:undefined},reschedule:true};}if(job.state==="upload_complete")return{state:"provider_processing",checkpoint:"simulated_provider_processing",evidence:{processingState:"PROCESSING"},reschedule:scenario!=="processing"};if(job.state==="provider_processing")return{state:"creation_pending",checkpoint:"simulated_content_ready",evidence:{processingState:"READY"},reschedule:true};return{state:"externally_published",checkpoint:"simulated_external_creation_confirmed",evidence:{mediaId:intent.platform==="instagram_reels"?`SIM-MEDIA-${intent.id}`:undefined,postId:intent.platform==="linkedin"?`SIM-POST-${intent.id}`:undefined,processingState:"COMPLETE",resultUrl:undefined,visibility:intent.youtubePrivacy,audience:intent.target.targetType}};}
  async reconcile(job:PublicationJob,intent:PublicationIntent,context:AdapterContext){if(job.state==="unknown")return{state:"externally_published" as const,checkpoint:"simulated_reconciliation_confirmed",evidence:{postId:`SIM-RECONCILED-${intent.id}`,processingState:"COMPLETE"}};if(job.state==="provider_processing")return this.advance(job,intent,{...context,connection:{...context.connection,accountId:"simulated:success"}});return{state:job.state,checkpoint:job.checkpoint};}
}

type Json=Record<string,any>;
export class YouTubeAdapter implements PublishingAdapter{
  async advance(job:PublicationJob,intent:PublicationIntent,context:AdapterContext):Promise<AdapterOutcome>{
    const auth={Authorization:`Bearer ${context.token}`};
    if(job.state==="queued"){
      const response=await providerFetch("https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status",{method:"POST",headers:{...auth,"Content-Type":"application/json","X-Upload-Content-Type":"video/mp4"},body:JSON.stringify({snippet:intent.payload,status:{privacyStatus:intent.youtubePrivacy??"private"}})},{allowAuthorization:true});
      if(!response.ok)return{state:response.status===401?"needs_reconnect":"failed",checkpoint:"session_rejected",error:sanitizedProviderError("YouTube",response.status),retryClass:response.status===401?"auth":"payload"};
      const location=response.headers.get("location");if(!location)return{state:"unknown",checkpoint:"session_response_invalid",error:"YouTube did not return a resumable upload session."};
      return{state:"upload_session_created",checkpoint:"resumable_session_saved",jobSecret:{uploadUrl:location,offset:0},reschedule:true};
    }
    if(job.state==="upload_session_created"||job.state==="uploading"){
      const uploadUrl=String(context.jobSecret?.uploadUrl??""),full=await context.openMedia(),offset=Number(context.jobSecret?.offset??0),media=offset?await context.openMedia({start:offset,end:full.byteSize-1}):full,response=await providerFetch(uploadUrl,{method:"PUT",headers:{"Content-Type":"video/mp4","Content-Length":String(media.byteSize),"Content-Range":`bytes ${offset}-${full.byteSize-1}/${full.byteSize}`},body:media.stream as any},{allowAuthorization:false});
      if(response.status===308){const match=response.headers.get("range")?.match(/bytes=0-(\d+)/),next=match?Number(match[1])+1:offset+media.byteSize;return{state:"uploading",checkpoint:"youtube_bytes_committed",evidence:{uploadBytes:next},jobSecret:{...context.jobSecret,offset:next},reschedule:true};}
      if(!response.ok)return{state:"unknown",checkpoint:"upload_response_uncertain",error:sanitizedProviderError("YouTube",response.status),retryClass:"ambiguous"};
      const data=response.json<Json>();if(!data.id)return{state:"unknown",checkpoint:"upload_result_unknown",error:"YouTube accepted the upload without a video ID."};return{state:"upload_complete",checkpoint:"private_video_created",evidence:{videoId:String(data.id),uploadBytes:full.byteSize,visibility:intent.youtubePrivacy??"private"},reschedule:true};
    }
    const id=job.evidence.videoId;if(!id)return{state:"unknown",checkpoint:"video_id_missing",error:"The YouTube video ID is unavailable."};const response=await providerFetch(`https://www.googleapis.com/youtube/v3/videos?part=status,processingDetails&id=${encodeURIComponent(id)}`,{headers:auth},{allowAuthorization:true});if(!response.ok)return{state:response.status===401?"needs_reconnect":"needs_attention",checkpoint:"status_unavailable",error:sanitizedProviderError("YouTube",response.status)};const item=response.json<Json>().items?.[0],processing=String(item?.processingDetails?.processingStatus??"unknown");if(processing!=="succeeded")return{state:"provider_processing",checkpoint:"youtube_processing",evidence:{processingState:processing},reschedule:processing==="processing"};return{state:"externally_published",checkpoint:"youtube_video_processed",evidence:{processingState:processing,videoId:id,visibility:String(item?.status?.privacyStatus??intent.youtubePrivacy??"private"),resultUrl:`https://www.youtube.com/watch?v=${encodeURIComponent(id)}`}};
  }
  async reconcile(job:PublicationJob,intent:PublicationIntent,context:AdapterContext){if((job.state==="upload_session_created"||job.state==="uploading"||job.state==="unknown")&&context.jobSecret?.uploadUrl){const media=await context.openMedia(),response=await providerFetch(String(context.jobSecret.uploadUrl),{method:"PUT",headers:{"Content-Length":"0","Content-Range":`bytes */${media.byteSize}`}});if(response.status===308){const match=response.headers.get("range")?.match(/bytes=0-(\d+)/),offset=match?Number(match[1])+1:0;return{state:"uploading" as const,checkpoint:"youtube_session_reconciled",evidence:{uploadBytes:offset},jobSecret:{...context.jobSecret,offset},reschedule:true};}if(response.status===404)return{state:"needs_attention" as const,checkpoint:"youtube_session_expired",error:"The saved YouTube upload session expired.",nextAction:"Retry this destination to create a new upload session only after confirming no video ID exists."};if(response.ok){const data=response.json<Json>();if(data.id)return{state:"upload_complete" as const,checkpoint:"private_video_reconciled",evidence:{videoId:String(data.id),visibility:intent.youtubePrivacy??"private"},reschedule:true};}return{state:"unknown" as const,checkpoint:"youtube_reconciliation_inconclusive",error:"YouTube could not confirm the saved upload outcome.",nextAction:"Inspect the channel before starting another upload."};}return this.advance(job,intent,context);}
}
export class InstagramAdapter implements PublishingAdapter{async advance(){return{state:"needs_attention" as const,checkpoint:"live_binary_upload_unverified",error:"LIVE Instagram publishing is capability-blocked until the current Instagram Login private binary upload flow is verified from official documentation.",nextAction:"Verify the current official upload flow and app permissions before enabling LIVE Instagram publication."};}async reconcile(){return this.advance();}}

export class LinkedInAdapter implements PublishingAdapter{
  private headers(token:string){return{Authorization:`Bearer ${token}`,"Linkedin-Version":settings.linkedinApiVersion,"X-Restli-Protocol-Version":"2.0.0","Content-Type":"application/json"};}
  async advance(job:PublicationJob,intent:PublicationIntent,context:AdapterContext):Promise<AdapterOutcome>{
    const headers=this.headers(context.token??"");
    if(job.state==="queued"){
      const media=await context.openMedia(),response=await providerFetch("https://api.linkedin.com/rest/videos?action=initializeUpload",{method:"POST",headers,body:JSON.stringify({initializeUploadRequest:{owner:intent.target.targetId,fileSizeBytes:media.byteSize,uploadCaptions:false,uploadThumbnail:false}})},{allowAuthorization:true});
      if(!response.ok)return{state:response.status===401?"needs_reconnect":"failed",checkpoint:"initialize_rejected",error:sanitizedProviderError("LinkedIn",response.status)};
      const value=response.json<Json>().value,videoUrn=value?.video,uploadInstructions=value?.uploadInstructions;
      if(!videoUrn||!Array.isArray(uploadInstructions))return{state:"unknown",checkpoint:"initialize_response_invalid",error:"LinkedIn returned incomplete upload instructions."};
      return{state:"upload_session_created",checkpoint:"linkedin_instructions_saved",evidence:{videoUrn},jobSecret:{uploadInstructions,uploaded:[],uploadToken:value.uploadToken??""},reschedule:true};
    }
    if(job.state==="upload_session_created"||job.state==="uploading"){
      const instructions=(context.jobSecret?.uploadInstructions as Json[]|undefined)??[],uploaded=(context.jobSecret?.uploaded as Json[]|undefined)??[],instruction=instructions[uploaded.length];
      if(!instruction)return{state:"upload_complete",checkpoint:"linkedin_ranges_uploaded",reschedule:true};
      const start=Number(instruction.firstByte??0),end=Number(instruction.lastByte??start),media=await context.openMedia({start,end}),response=await providerFetch(String(instruction.uploadUrl),{method:"PUT",headers:{"Content-Type":"application/octet-stream","Content-Length":String(media.byteSize)},body:media.stream as any});
      if(!response.ok)return{state:"unknown",checkpoint:"range_upload_uncertain",error:sanitizedProviderError("LinkedIn",response.status),retryClass:"ambiguous"};
      const nextUploaded=[...uploaded,{etag:response.headers.get("etag"),firstByte:start,lastByte:end}],complete=nextUploaded.length===instructions.length;
      return{state:complete?"upload_complete":"uploading",checkpoint:complete?"linkedin_ranges_uploaded":"linkedin_range_uploaded",evidence:{uploadBytes:nextUploaded.reduce((n,item)=>n+Number(item.lastByte)-Number(item.firstByte)+1,0),videoUrn:job.evidence.videoUrn},jobSecret:{...context.jobSecret,uploaded:nextUploaded},reschedule:true};
    }
    if(job.state==="upload_complete"){
      const uploaded=(context.jobSecret?.uploaded as Json[]|undefined)??[],response=await providerFetch("https://api.linkedin.com/rest/videos?action=finalizeUpload",{method:"POST",headers,body:JSON.stringify({finalizeUploadRequest:{video:job.evidence.videoUrn,uploadToken:context.jobSecret?.uploadToken??"",uploadedPartIds:uploaded.map(v=>v.etag).filter(Boolean)}})},{allowAuthorization:true});
      if(!response.ok)return{state:"unknown",checkpoint:"finalize_uncertain",error:sanitizedProviderError("LinkedIn",response.status),retryClass:"ambiguous"};
      return{state:"provider_processing",checkpoint:"linkedin_video_processing",evidence:{processingState:"PROCESSING"},reschedule:true};
    }
    if(job.state==="provider_processing"){
      const urn=encodeURIComponent(job.evidence.videoUrn??""),response=await providerFetch(`https://api.linkedin.com/rest/videos/${urn}`,{headers},{allowAuthorization:true});if(!response.ok)return{state:"needs_attention",checkpoint:"video_status_unavailable",error:sanitizedProviderError("LinkedIn",response.status)};const status=String(response.json<Json>().status??"UNKNOWN");if(status!=="AVAILABLE")return{state:status==="PROCESSING_FAILED"?"failed":"provider_processing",checkpoint:"linkedin_video_processing",evidence:{processingState:status},reschedule:status!=="PROCESSING_FAILED"};return{state:"creation_pending",checkpoint:"linkedin_video_available",evidence:{processingState:status},reschedule:true};
    }
    const response=await providerFetch("https://api.linkedin.com/rest/posts",{method:"POST",headers,body:JSON.stringify({author:intent.target.targetId,commentary:intent.payload.commentary,visibility:"PUBLIC",distribution:{feedDistribution:"MAIN_FEED",targetEntities:[],thirdPartyDistributionChannels:[]},content:{media:{id:job.evidence.videoUrn}},lifecycleState:"PUBLISHED",isReshareDisabledByAuthor:false})},{allowAuthorization:true});
    if(!response.ok)return{state:response.status>=500?"unknown":"failed",checkpoint:response.status>=500?"linkedin_post_outcome_unknown":"linkedin_post_rejected",error:sanitizedProviderError("LinkedIn",response.status),retryClass:response.status>=500?"ambiguous":"payload"};const id=response.headers.get("x-restli-id");if(!id)return{state:"unknown",checkpoint:"linkedin_post_outcome_unknown",error:"LinkedIn did not return a post ID."};return{state:"externally_published",checkpoint:"linkedin_post_created",evidence:{postId:id,audience:intent.target.targetType,resultUrl:`https://www.linkedin.com/feed/update/${encodeURIComponent(id)}`}};
  }
  async reconcile(job:PublicationJob){return{state:job.state,checkpoint:job.checkpoint,error:"LinkedIn cannot authoritatively reconcile this ambiguous post from the available saved evidence.",nextAction:"Inspect the selected LinkedIn account before deciding whether to create a new approved publication."};}
}
export function adapterFor(platform:PublicationIntent["platform"]):PublishingAdapter{if(settings.publishMode==="test")return new TestPublishingAdapter();return platform==="youtube_shorts"?new YouTubeAdapter():platform==="instagram_reels"?new InstagramAdapter():new LinkedInAdapter();}
