import { randomUUID } from "node:crypto";
import { storage } from "./storage.js";
import { publicationStorage, type PublicationStorage } from "./publication-storage.js";
import { adapterFor, type AdapterOutcome } from "./provider-adapters.js";
import { activeApproval, approvalFingerprint } from "./publication.js";
import { connectionAad, decryptSecret, encryptSecret } from "./token-vault.js";
import type { JobSecretRecord, PlatformConnection, PublicationAggregate, PublicationAttempt, PublicationJob } from "./publication-types.js";
import { settings } from "./settings.js";
import { providerFetch } from "./provider-http.js";
import { StorageConflictError } from "./storage-types.js";

const terminal=new Set(["externally_published","failed","needs_reconnect","needs_attention","unknown","superseded"]);
class SupersededApprovalError extends Error{constructor(readonly afterEffect:boolean){super("The approved release changed after this publication intent was prepared.");}}
class NeedsReconnectError extends Error{}

async function mutate(ownerId:string,runId:string,fn:(value:PublicationAggregate)=>PublicationAggregate,store:PublicationStorage=publicationStorage){for(let attempt=0;attempt<5;attempt++){const current=await store.getAggregate(ownerId,runId),next=fn(structuredClone(current));try{return await store.putAggregate(next,current.revision);}catch(error){if(!(error instanceof StorageConflictError)||attempt===4)throw error;}}throw new Error("Publication state could not be saved.");}
export function preparedAttempt(kind:PublicationAttempt["kind"],message:string,at=new Date().toISOString()){return{id:randomUUID(),at,kind,message};}

export async function claimPublicationJob(ownerId:string,runId:string,jobId:string,reconcile=false,store:PublicationStorage=publicationStorage){
  const id=randomUUID(),at=new Date().toISOString(),expiresAt=new Date(Date.parse(at)+60_000).toISOString(),event=preparedAttempt(reconcile?"reconcile":"claim",reconcile?"Claimed for reconciliation.":"Claimed for the next provider checkpoint.",at);
  for(let attempt=0;attempt<5;attempt++){const current=await store.getAggregate(ownerId,runId),job=current.jobs.find(v=>v.id===jobId);if(!job)throw new Error("Publication job was not found.");if(terminal.has(job.state)&&!(reconcile&&(job.allowedAction==="reconcile"||job.state==="provider_processing")))throw new Error("This publication job cannot run from its current state.");if(job.activeClaim&&Date.parse(job.activeClaim.expiresAt)>Date.parse(at))throw new Error("This publication job is already running.");const forceReconcile=reconcile||!!job.activeClaim,fence=(job.activeClaim?.fence??0)+1,next=structuredClone(current),item=next.jobs.find(v=>v.id===jobId)!;item.activeClaim={id,fence,expiresAt};item.revision++;item.attemptCount++;item.updatedAt=at;item.nextAttemptAt=undefined;item.attempts.push(event);const intent=next.intents.find(v=>v.id===item.intentId);if(intent)intent.status="started";try{await store.putAggregate(next,current.revision);return{claimId:id,fence,reconcile:forceReconcile};}catch(error){if(!(error instanceof StorageConflictError)||attempt===4)throw error;}}
  throw new Error("Publication job could not be claimed.");
}
async function verifyOrRenew(ownerId:string,runId:string,jobId:string,claimId:string,fence:number){const current=await publicationStorage.getAggregate(ownerId,runId),job=current.jobs.find(v=>v.id===jobId);if(!job||job.activeClaim?.id!==claimId||job.activeClaim.fence!==fence)throw new Error("A newer worker owns this publication job.");const now=Date.now();if(Date.parse(job.activeClaim.expiresAt)>now+20_000)return;const at=new Date(now).toISOString(),expiresAt=new Date(now+60_000).toISOString();await mutate(ownerId,runId,value=>{const item=value.jobs.find(v=>v.id===jobId);if(!item||item.activeClaim?.id!==claimId||item.activeClaim.fence!==fence)throw new Error("A newer worker owns this publication job.");item.activeClaim={id:claimId,fence,expiresAt};item.updatedAt=at;return value;});}

function outcomePolicy(outcome:AdapterOutcome){return{retrySafety:outcome.retrySafety??(outcome.state==="unknown"?"reconcile_only":outcome.state==="needs_reconnect"?"reconnect_only":outcome.state==="needs_attention"?"attention_only":outcome.state==="failed"?"user_safe":outcome.reschedule?"automatic":"none"),allowedAction:outcome.allowedAction??(outcome.state==="unknown"?"reconcile":outcome.state==="needs_reconnect"?"reconnect":outcome.state==="needs_attention"?"inspect":outcome.state==="failed"?"retry":"none")};}
async function saveOutcome(ownerId:string,runId:string,jobId:string,claimId:string,fence:number,outcome:AdapterOutcome,priorBackoffAttempt=0){
  const at=new Date().toISOString(),eventId=randomUUID(),policy=outcomePolicy(outcome),backoff=outcome.retryAfterMs!==undefined?Math.min(outcome.retryAfterMs,settings.providerPollMaxMs):outcome.reschedule?Math.min(Math.max(250,settings.providerPollBaseMs*2**priorBackoffAttempt),settings.providerPollMaxMs):undefined,nextAttemptAt=backoff!==undefined?new Date(Date.parse(at)+backoff).toISOString():undefined;
  let encrypted:JobSecretRecord|undefined;
  if(outcome.jobSecret){if(settings.publishMode!=="live")throw new Error("Simulated providers cannot create secret upload checkpoints.");encrypted={ownerId,runId,jobId,claimId,fence,envelope:encryptSecret(outcome.jobSecret,`vpo:job:${ownerId}:${jobId}`),updatedAt:at};}
  for(let attempt=0;attempt<5;attempt++){
    const current=await publicationStorage.getAggregate(ownerId,runId),job=current.jobs.find(v=>v.id===jobId);if(!job||job.activeClaim?.id!==claimId||job.activeClaim.fence!==fence)throw new Error("A newer worker owns this publication job.");const next=structuredClone(current),item=next.jobs.find(v=>v.id===jobId)!,from=item.state;item.state=outcome.state;item.checkpoint=outcome.checkpoint;item.evidence={...item.evidence,...outcome.evidence};item.sanitizedError=outcome.error;item.nextAction=outcome.nextAction;item.retryClass=outcome.retryClass;item.retrySafety=policy.retrySafety;item.allowedAction=policy.allowedAction;item.updatedAt=at;item.revision++;item.backoffAttempt=outcome.reschedule?item.backoffAttempt+1:0;item.nextAttemptAt=nextAttemptAt;delete item.activeClaim;item.attempts.push({id:eventId,at,kind:outcome.error?"error":"checkpoint",message:outcome.error??outcome.checkpoint,from,to:outcome.state});
    try{return await publicationStorage.commitJobCheckpoint(next,current.revision,jobId,claimId,encrypted);}catch(error){if(!(error instanceof StorageConflictError)||attempt===4)throw error;}
  }
  throw new Error("Publication checkpoint could not be saved.");
}

async function markReconnect(ownerId:string,connection:PlatformConnection){const at=new Date().toISOString();try{await publicationStorage.putConnection({...connection,status:"needs_reconnect",updatedAt:at,revision:connection.revision+1},connection.revision);}catch{/* A concurrent capability refresh wins; the job still remains reconnect-blocked. */}}
async function liveAccessToken(ownerId:string,connection:PlatformConnection,beforeEffect:()=>Promise<void>){
  const saved=await publicationStorage.getConnectionSecret(ownerId,connection.id),aad=connectionAad(ownerId,connection.provider,connection.id),secret=decryptSecret<{accessToken:string;refreshToken?:string}>(saved.envelope,aad);if(!connection.expiresAt||Date.parse(connection.expiresAt)>Date.now()+60_000)return secret.accessToken;
  if(!secret.refreshToken||connection.provider==="instagram"){await markReconnect(ownerId,connection);throw new NeedsReconnectError("This platform authorization expired. Reconnect the account.");}
  await beforeEffect();const endpoint=connection.provider==="youtube"?"https://oauth2.googleapis.com/token":"https://www.linkedin.com/oauth/v2/accessToken",clientId=connection.provider==="youtube"?settings.googleClientId:settings.linkedinClientId,clientSecret=connection.provider==="youtube"?settings.googleClientSecret:settings.linkedinClientSecret,response=await providerFetch(endpoint,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"refresh_token",refresh_token:secret.refreshToken,client_id:clientId,client_secret:clientSecret}).toString()});
  if(!response.ok){await markReconnect(ownerId,connection);throw new NeedsReconnectError("This platform authorization could not be refreshed. Reconnect the account.");}const value=response.json<{access_token?:string;refresh_token?:string;expires_in?:number}>();if(!value.access_token){await markReconnect(ownerId,connection);throw new NeedsReconnectError("The refreshed platform authorization was incomplete. Reconnect the account.");}
  const updatedAt=new Date().toISOString(),updated={...connection,expiresAt:new Date(Date.parse(updatedAt)+(value.expires_in??3600)*1000).toISOString(),updatedAt,revision:connection.revision+1},authorization={ownerId,connectionId:connection.id,envelope:encryptSecret({accessToken:value.access_token,refreshToken:value.refresh_token??secret.refreshToken},aad),updatedAt};await publicationStorage.commitConnectionAuthorization(updated,authorization,connection.revision);return value.access_token;
}
function authorizationEffect(job:PublicationJob,reconciling:boolean):"read"|"write"{if(reconciling)return"read";if(job.platform==="youtube_shorts"&&!!job.evidence.videoId)return"read";if(job.platform==="linkedin"&&job.state==="provider_processing"&&!!job.evidence.videoUrn)return"read";return"write";}
export function approvalAllowsEffect(job:PublicationJob,active:boolean,kind:"write"|"read"){const hasEffect=!!(job.evidence.uploadSessionId||job.evidence.uploadBytes||job.evidence.videoId||job.evidence.videoUrn||job.evidence.containerId||job.evidence.mediaId||job.evidence.postId);return active||(kind==="read"&&hasEffect);}
async function context(ownerId:string,aggregate:PublicationAggregate,job:PublicationJob,claimId:string,fence:number,reconciling:boolean){
  const intent=aggregate.intents.find(v=>v.id===job.intentId);if(!intent)throw new Error("Publication intent was not found.");const run=await storage.getRun(ownerId,job.runId),approval=run.release?.approvals.find(v=>v.id===intent.approvalId);if(!approval)throw new SupersededApprovalError(false);const media=run.release!.mediaVersions.find(v=>v.id===approval.mediaVersionId);if(!media||media.sha256!==approval.mediaSha256)throw new SupersededApprovalError(false);const hasEffect=!!(job.evidence.uploadSessionId||job.evidence.uploadBytes||job.evidence.videoId||job.evidence.videoUrn||job.evidence.containerId||job.evidence.mediaId||job.evidence.postId);const stillActive=()=>{try{return activeApproval(run).id===intent.approvalId&&approvalFingerprint(run,approval)===intent.approvalFingerprint;}catch{return false;}};
  const beforeEffect=async(kind:"write"|"read")=>{await verifyOrRenew(ownerId,job.runId,job.id,claimId,fence);const latest=await storage.getRun(ownerId,job.runId);let active=false;try{active=activeApproval(latest).id===intent.approvalId&&approvalFingerprint(latest,approval)===intent.approvalFingerprint;}catch{}if(!approvalAllowsEffect(job,active,kind))throw new SupersededApprovalError(hasEffect);};
  if(!stillActive()&&!hasEffect)throw new SupersededApprovalError(false);const connection=await publicationStorage.getConnection(ownerId,intent.connectionId);if(connection.status!=="connected")throw new NeedsReconnectError("Reconnect this platform before continuing.");const token=settings.publishMode==="live"?await liveAccessToken(ownerId,connection,()=>beforeEffect(authorizationEffect(job,reconciling))):undefined;let jobSecret:Record<string,unknown>|undefined;const encrypted=await publicationStorage.getJobSecret(ownerId,job.id);if(encrypted){if(encrypted.runId!==job.runId||encrypted.fence>fence)throw new Error("A newer private checkpoint owns this publication job.");jobSecret=decryptSecret(encrypted.envelope,`vpo:job:${ownerId}:${job.id}`);}const getMediaMetadata=async()=>{const asset=await storage.getAssetRecord(ownerId,media.assetId);if(asset.runId!==run.id||asset.sha256!==media.sha256)throw new Error("The approved asset record does not match the approval.");return{byteSize:asset.byteSize,sha256:asset.sha256};};return{intent,connection,jobSecret,token,beforeEffect,getMediaMetadata,openMedia:async(range?:{start:number;end:number})=>{const asset=await storage.openAsset(ownerId,media.assetId,range);if(asset.record.runId!==run.id||asset.record.sha256!==media.sha256)throw new Error("The approved asset record does not match the approval.");return{stream:asset.stream,byteSize:range?range.end-range.start+1:asset.record.byteSize,sha256:asset.record.sha256};}};
}
export interface PublicationContinuation{at:string;reconcile?:boolean}
export async function executePublicationJob(ownerId:string,runId:string,jobId:string,reconcile=false):Promise<PublicationContinuation|undefined>{
  const claimed=await claimPublicationJob(ownerId,runId,jobId,reconcile),aggregate=await publicationStorage.getAggregate(ownerId,runId),job=aggregate.jobs.find(v=>v.id===jobId)!;
  try{
    const reconciling=reconcile||claimed.reconcile,ctx=await context(ownerId,aggregate,job,claimed.claimId,claimed.fence,reconciling),adapter=adapterFor(ctx.intent.platform),outcome=reconciling?await adapter.reconcile(job,ctx.intent,ctx):await adapter.advance(job,ctx.intent,ctx);
    if(outcome.state==="needs_reconnect")await markReconnect(ownerId,ctx.connection);
    const saved=await saveOutcome(ownerId,runId,jobId,claimed.claimId,claimed.fence,outcome,job.backoffAttempt),next=saved.jobs.find(v=>v.id===jobId);
    if(outcome.reschedule&&next?.nextAttemptAt)return{at:next.nextAttemptAt};
  }catch(error){
    const outcome:AdapterOutcome=error instanceof SupersededApprovalError?{state:error.afterEffect?"needs_attention":"superseded",checkpoint:error.afterEffect?"approval_superseded_after_provider_effect":"approval_superseded_before_provider_effect",error:error.message,nextAction:error.afterEffect?"Inspect or reconcile the saved external artifact; no later publish action will run.":undefined,retrySafety:error.afterEffect?"attention_only":"none",allowedAction:error.afterEffect?"inspect":"none"}:error instanceof NeedsReconnectError?{state:"needs_reconnect",checkpoint:"authorization_refresh_failed",error:error.message,nextAction:"Reconnect the exact bound account.",retrySafety:"reconnect_only",allowedAction:"reconnect"}:{state:"needs_attention",checkpoint:"worker_stopped",error:error instanceof Error?error.message:"Publication worker stopped.",nextAction:"Review the saved checkpoint before continuing.",retrySafety:"attention_only",allowedAction:"inspect"};
    await saveOutcome(ownerId,runId,jobId,claimed.claimId,claimed.fence,outcome,job.backoffAttempt).catch(()=>{});
  }
}
type TimerHandle=ReturnType<typeof setTimeout>;
interface SchedulerClock{now:()=>number;setTimer:(fn:()=>void,delayMs:number)=>TimerHandle;clearTimer:(timer:TimerHandle)=>void;}
interface ScheduledEntry{timer:TimerHandle;dueAt:number;reconcile:boolean;running:boolean;}
export function createPublicationScheduler(execute=executePublicationJob,clock:SchedulerClock={now:Date.now,setTimer:(fn,delay)=>setTimeout(fn,delay),clearTimer:timer=>clearTimeout(timer)}){
  const entries=new Map<string,ScheduledEntry>(),key=(ownerId:string,runId:string,jobId:string)=>`${ownerId}:${runId}:${jobId}`;
  const schedule=(ownerId:string,runId:string,jobId:string,reconcile=false,delayMs=0)=>{const id=key(ownerId,runId,jobId),dueAt=clock.now()+Math.max(0,delayMs),current=entries.get(id);if(current?.running)return;if(current&&current.dueAt<=dueAt&&(!reconcile||current.reconcile))return;if(current)clock.clearTimer(current.timer);const entry={} as ScheduledEntry;entry.dueAt=dueAt;entry.reconcile=reconcile||(current?.reconcile??false);entry.running=false;entry.timer=clock.setTimer(()=>{if(entries.get(id)!==entry)return;entry.running=true;void execute(ownerId,runId,jobId,entry.reconcile).then(continuation=>{if(entries.get(id)===entry)entries.delete(id);if(continuation)schedule(ownerId,runId,jobId,continuation.reconcile??false,Math.max(0,Date.parse(continuation.at)-clock.now()));},()=>{if(entries.get(id)===entry)entries.delete(id);});},Math.max(0,dueAt-clock.now()));entries.set(id,entry);};
  return{schedule,pending:()=>entries.size,cancelAll:()=>{for(const entry of entries.values())clock.clearTimer(entry.timer);entries.clear();}};
}
const scheduler=createPublicationScheduler();
export function schedulePublicationJob(ownerId:string,runId:string,jobId:string,reconcile=false,delayMs=0){scheduler.schedule(ownerId,runId,jobId,reconcile,delayMs);}
export async function recoverPublicationJobs(){for(const aggregate of await publicationStorage.listRecoverableAggregates())for(const job of aggregate.jobs){if(terminal.has(job.state))continue;const uncertain=!!job.activeClaim,event=preparedAttempt("reconcile",uncertain?"Recovered a worker claim; reconciliation will begin only after its fence expires.":"Recovered a safe saved checkpoint."),at=event.at;await mutate(aggregate.ownerId,aggregate.runId,current=>{const item=current.jobs.find(v=>v.id===job.id)!;item.updatedAt=at;item.attempts.push(event);return current;});const eligibleAt=Math.max(Date.parse(job.nextAttemptAt??at),Date.parse(job.activeClaim?.expiresAt??at)+1),delay=Math.max(0,eligibleAt-Date.now());schedulePublicationJob(aggregate.ownerId,aggregate.runId,job.id,uncertain,delay);}}
export async function retryJob(ownerId:string,runId:string,jobId:string,expectedRevision:number){const at=new Date().toISOString(),event=preparedAttempt("retry","User requested a safe retry under the same logical intent.",at);const saved=await mutate(ownerId,runId,current=>{const job=current.jobs.find(v=>v.id===jobId);if(!job)throw new Error("Publication job was not found.");if(job.revision!==expectedRevision)throw new Error("Publication status changed. Refresh first.");if(job.allowedAction!=="retry"||job.retrySafety!=="user_safe")throw new Error("This checkpoint cannot be retried safely. Follow its displayed action instead.");if(job.nextAttemptAt&&Date.parse(job.nextAttemptAt)>Date.parse(at))throw new Error("The provider asked VPO Studio to wait before retrying this checkpoint.");job.state="queued";job.checkpoint="retry_requested";job.updatedAt=at;job.revision++;job.sanitizedError=undefined;job.nextAction=undefined;job.allowedAction="none";job.retrySafety="automatic";job.nextAttemptAt=undefined;job.attempts.push(event);return current;});schedulePublicationJob(ownerId,runId,jobId);return saved;}
export async function reconcileJob(ownerId:string,runId:string,jobId:string,expectedRevision:number){const current=await publicationStorage.getAggregate(ownerId,runId),job=current.jobs.find(v=>v.id===jobId);if(!job||job.revision!==expectedRevision)throw new Error("Publication status changed. Refresh first.");if(job.allowedAction!=="reconcile")throw new Error("This destination does not have a safe reconciliation action.");schedulePublicationJob(ownerId,runId,jobId,true);return current;}
