import { randomUUID } from "node:crypto";
import { storage } from "./storage.js";
import { publicationStorage } from "./publication-storage.js";
import { adapterFor, type AdapterOutcome } from "./provider-adapters.js";
import { activeApproval, approvalFingerprint } from "./publication.js";
import { connectionAad, decryptSecret, encryptSecret } from "./token-vault.js";
import type { PublicationAggregate, PublicationJob } from "./publication-types.js";
import { settings } from "./settings.js";
import { providerFetch } from "./provider-http.js";

const scheduled=new Set<string>(),terminal=new Set(["externally_published","failed","needs_reconnect","needs_attention","unknown","superseded"]);
async function mutate(ownerId:string,runId:string,fn:(value:PublicationAggregate)=>PublicationAggregate){for(let attempt=0;attempt<5;attempt++){const current=await publicationStorage.getAggregate(ownerId,runId),next=fn(structuredClone(current));try{return await publicationStorage.putAggregate(next,current.revision);}catch(error){if(attempt===4)throw error;}}throw new Error("Publication state could not be saved.");}
async function claim(ownerId:string,runId:string,jobId:string,reconcile=false){const id=randomUUID(),now=new Date(),expiresAt=new Date(now.getTime()+60_000).toISOString();const saved=await mutate(ownerId,runId,current=>{const job=current.jobs.find(v=>v.id===jobId);if(!job)throw new Error("Publication job was not found.");if(terminal.has(job.state)&&!(reconcile&&(job.state==="unknown"||job.state==="provider_processing")))throw new Error("This publication job cannot run from its current state.");if(job.activeClaim&&Date.parse(job.activeClaim.expiresAt)>now.getTime())throw new Error("This publication job is already running.");job.activeClaim={id,revision:job.revision+1,expiresAt};job.revision++;job.attemptCount++;job.updatedAt=now.toISOString();job.attempts.push({id:randomUUID(),at:now.toISOString(),kind:reconcile?"reconcile":"claim",message:reconcile?"Claimed for reconciliation.":"Claimed for the next provider checkpoint."});const intent=current.intents.find(v=>v.id===job.intentId);if(intent)intent.status="started";return current;});return{claimId:id,job:saved.jobs.find(v=>v.id===jobId)!};}
async function saveOutcome(ownerId:string,runId:string,jobId:string,claimId:string,outcome:AdapterOutcome){const at=new Date().toISOString();return mutate(ownerId,runId,current=>{const job=current.jobs.find(v=>v.id===jobId);if(!job||job.activeClaim?.id!==claimId)throw new Error("A newer worker owns this publication job.");const from=job.state;job.state=outcome.state;job.checkpoint=outcome.checkpoint;job.evidence={...job.evidence,...outcome.evidence};job.sanitizedError=outcome.error;job.nextAction=outcome.nextAction;job.retryClass=outcome.retryClass;job.updatedAt=at;job.revision++;delete job.activeClaim;job.attempts.push({id:randomUUID(),at,kind:outcome.error?"error":"checkpoint",message:outcome.error??outcome.checkpoint,from,to:outcome.state});return current;});}
async function liveAccessToken(ownerId:string,connection:Awaited<ReturnType<typeof publicationStorage.getConnection>>){const saved=await publicationStorage.getConnectionSecret(ownerId,connection.id),aad=connectionAad(ownerId,connection.provider,connection.id),secret=decryptSecret<{accessToken:string;refreshToken?:string}>(saved.envelope,aad);if(!connection.expiresAt||Date.parse(connection.expiresAt)>Date.now()+60_000)return secret.accessToken;if(!secret.refreshToken||connection.provider==="instagram")throw new Error("This platform authorization expired. Reconnect the account.");const endpoint=connection.provider==="youtube"?"https://oauth2.googleapis.com/token":"https://www.linkedin.com/oauth/v2/accessToken",clientId=connection.provider==="youtube"?settings.googleClientId:settings.linkedinClientId,clientSecret=connection.provider==="youtube"?settings.googleClientSecret:settings.linkedinClientSecret,response=await providerFetch(endpoint,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"refresh_token",refresh_token:secret.refreshToken,client_id:clientId,client_secret:clientSecret}).toString()});if(!response.ok)throw new Error("This platform authorization could not be refreshed. Reconnect the account.");const value=response.json<{access_token?:string;refresh_token?:string;expires_in?:number}>();if(!value.access_token)throw new Error("The refreshed platform authorization was incomplete. Reconnect the account.");const updatedAt=new Date().toISOString();await publicationStorage.putConnectionSecret({ownerId,connectionId:connection.id,envelope:encryptSecret({accessToken:value.access_token,refreshToken:value.refresh_token??secret.refreshToken},aad),updatedAt});await publicationStorage.putConnection({...connection,expiresAt:new Date(Date.now()+(value.expires_in??3600)*1000).toISOString(),updatedAt,revision:connection.revision+1},connection.revision);return value.access_token;}
async function context(ownerId:string,aggregate:PublicationAggregate,job:PublicationJob){const intent=aggregate.intents.find(v=>v.id===job.intentId);if(!intent)throw new Error("Publication intent was not found.");const run=await storage.getRun(ownerId,job.runId),approval=activeApproval(run);if(approval.id!==intent.approvalId||approvalFingerprint(run,approval)!==intent.approvalFingerprint)throw new Error("The approved release changed before the provider action.");const connection=await publicationStorage.getConnection(ownerId,intent.connectionId);if(connection.status!=="connected")throw new Error("Reconnect this platform before continuing.");const media=run.release!.mediaVersions.find(v=>v.id===approval.mediaVersionId);if(!media||media.sha256!==approval.mediaSha256)throw new Error("The approved media changed before publication.");const token=settings.publishMode==="live"?await liveAccessToken(ownerId,connection):undefined;let jobSecret:Record<string,unknown>|undefined;const encrypted=await publicationStorage.getJobSecret(ownerId,job.id);if(encrypted)jobSecret=decryptSecret(encrypted,`vpo:job:${ownerId}:${job.id}`);return{intent,connection,jobSecret,token,openMedia:async(range?:{start:number;end:number})=>{const asset=await storage.openAsset(ownerId,media.assetId,range);if(asset.record.runId!==run.id||asset.record.sha256!==media.sha256)throw new Error("The approved asset record does not match the approval.");return{stream:asset.stream,byteSize:range?range.end-range.start+1:asset.record.byteSize,sha256:asset.record.sha256};}};}
export async function executePublicationJob(ownerId:string,runId:string,jobId:string,reconcile=false){const claimed=await claim(ownerId,runId,jobId,reconcile),aggregate=await publicationStorage.getAggregate(ownerId,runId),job=aggregate.jobs.find(v=>v.id===jobId)!;try{const ctx=await context(ownerId,aggregate,job),adapter=adapterFor(ctx.intent.platform),outcome=reconcile?await adapter.reconcile(job,ctx.intent,ctx):await adapter.advance(job,ctx.intent,ctx);if(outcome.jobSecret){if(settings.publishMode!=="live")throw new Error("Simulated providers cannot create secret upload checkpoints.");await publicationStorage.putJobSecret(ownerId,jobId,encryptSecret(outcome.jobSecret,`vpo:job:${ownerId}:${jobId}`));}await saveOutcome(ownerId,runId,jobId,claimed.claimId,outcome);if(outcome.reschedule)setTimeout(()=>schedulePublicationJob(ownerId,runId,jobId),0);}catch(error){await saveOutcome(ownerId,runId,jobId,claimed.claimId,{state:"needs_attention",checkpoint:"worker_stopped",error:error instanceof Error?error.message:"Publication worker stopped.",nextAction:"Review the saved checkpoint before continuing."}).catch(()=>{});}}
export function schedulePublicationJob(ownerId:string,runId:string,jobId:string,reconcile=false){if(scheduled.has(jobId))return;scheduled.add(jobId);setTimeout(()=>void executePublicationJob(ownerId,runId,jobId,reconcile).finally(()=>scheduled.delete(jobId)),0);}
export async function recoverPublicationJobs(){for(const aggregate of await publicationStorage.listRecoverableAggregates())for(const job of aggregate.jobs){if(terminal.has(job.state))continue;const uncertain=!!job.activeClaim;await mutate(aggregate.ownerId,aggregate.runId,current=>{const item=current.jobs.find(v=>v.id===job.id)!;delete item.activeClaim;item.updatedAt=new Date().toISOString();item.attempts.push({id:randomUUID(),at:item.updatedAt,kind:"reconcile",message:uncertain?"Recovered an uncertain worker claim; provider reconciliation is required.":"Recovered a safe saved checkpoint."});return current;});schedulePublicationJob(aggregate.ownerId,aggregate.runId,job.id,uncertain);}}
export async function retryJob(ownerId:string,runId:string,jobId:string,expectedRevision:number){const at=new Date().toISOString();const saved=await mutate(ownerId,runId,current=>{const job=current.jobs.find(v=>v.id===jobId);if(!job)throw new Error("Publication job was not found.");if(job.revision!==expectedRevision)throw new Error("Publication status changed. Refresh first.");if(job.state!=="failed"&&job.state!=="needs_reconnect"&&job.state!=="needs_attention")throw new Error("Only a failed or attention-required destination can be retried.");job.state="queued";job.checkpoint="retry_requested";job.updatedAt=at;job.revision++;job.sanitizedError=undefined;job.nextAction=undefined;job.attempts.push({id:randomUUID(),at,kind:"retry",message:"User requested a retry under the same logical intent."});return current;});schedulePublicationJob(ownerId,runId,jobId);return saved;}
export async function reconcileJob(ownerId:string,runId:string,jobId:string,expectedRevision:number){const current=await publicationStorage.getAggregate(ownerId,runId),job=current.jobs.find(v=>v.id===jobId);if(!job||job.revision!==expectedRevision)throw new Error("Publication status changed. Refresh first.");if(job.state!=="unknown"&&job.state!=="provider_processing")throw new Error("This destination does not need reconciliation.");schedulePublicationJob(ownerId,runId,jobId,true);return current;}
