import { createHash, randomUUID } from "node:crypto";
import { Router } from "express";
import { z } from "zod";
import { owner } from "./auth.js";
import { settings } from "./settings.js";
import { storage } from "./storage.js";
import { publicationStorage } from "./publication-storage.js";
import { activeApproval, approvalFingerprint, confirmationFor, connectionBlockers, oauthMaterial, prepareBatch, publicationHash, saveBinding } from "./publication.js";
import { providerForDestination, type PlatformConnection, type Provider } from "./publication-types.js";
import { schedulePublicationJob, retryJob, reconcileJob } from "./publication-runner.js";
import { connectionAad, encryptSecret } from "./token-vault.js";
import { providerFetch } from "./provider-http.js";

export const publicationRouter=Router(),oauthCallbackRouter=Router();
const provider=z.enum(["youtube","instagram","linkedin"]),destination=z.enum(["youtube_shorts","instagram_reels","linkedin"]),uuid=z.string().uuid();
const now=()=>new Date().toISOString(),hash=(value:string)=>createHash("sha256").update(value).digest("hex"),notFound=()=>Object.assign(new Error("Publication item was not found."),{status:404});
function returnPath(value:string){if(!/^\/runs\/[A-Za-z0-9-]+(?:\?connected=[a-z]+)?$/.test(value))throw new Error("Return location is not allowed.");return value;}
export function oauthConfig(value:Provider){if(value==="youtube")return{clientId:settings.googleClientId,secret:settings.googleClientSecret,authorize:"https://accounts.google.com/o/oauth2/v2/auth",token:"https://oauth2.googleapis.com/token",scopes:["https://www.googleapis.com/auth/youtube.upload"]};if(value==="instagram")return{clientId:settings.metaClientId,secret:settings.metaClientSecret,authorize:"https://www.instagram.com/oauth/authorize",token:"https://api.instagram.com/oauth/access_token",scopes:["instagram_business_basic","instagram_business_content_publish"]};return{clientId:settings.linkedinClientId,secret:settings.linkedinClientSecret,authorize:"https://www.linkedin.com/oauth/v2/authorization",token:"https://www.linkedin.com/oauth/v2/accessToken",scopes:["openid","profile","w_member_social"]};}
export function parseGrantedScopes(token:Record<string,unknown>){return typeof token.scope==="string"?token.scope.split(/[ ,]+/).filter(Boolean):[];}
export function hasRequiredScopes(value:Provider,granted:string[]){return oauthConfig(value).scopes.every(scope=>granted.includes(scope));}
export function buildAuthorizedConnection(value:Provider,ownerId:string,token:Record<string,unknown>,targets:PlatformConnection["targets"],at:string,existing?:PlatformConnection):PlatformConnection{const grantedScopes=parseGrantedScopes(token),scopesOkay=hasRequiredScopes(value,grantedScopes),connectionId=existing?.id??randomUUID();return{id:connectionId,ownerId,provider:value,accountId:String(token.user_id??token.id??existing?.accountId??connectionId),accountLabel:targets[0]?.label??existing?.accountLabel??`Connected ${value} account`,status:scopesOkay&&targets.some(item=>item.eligible)?"connected":"needs_attention",grantedScopes,expiresAt:typeof token.expires_in==="number"?new Date(Date.parse(at)+token.expires_in*1000).toISOString():undefined,targets:targets.length?targets:existing?.targets??[],revision:(existing?.revision??0)+1,createdAt:existing?.createdAt??at,updatedAt:at,provenance:"live",disconnectNote:scopesOkay?undefined:"The provider did not grant every required publishing scope."};}
const redirectUri=(value:Provider)=>`${settings.publicOAuthCallbackBaseUrl.replace(/\/$/,"")}/oauth/${value}/callback`;
function authUrl(value:Provider,state:string){const config=oauthConfig(value),url=new URL(config.authorize);url.searchParams.set("response_type","code");url.searchParams.set("client_id",config.clientId);url.searchParams.set("redirect_uri",redirectUri(value));url.searchParams.set("scope",config.scopes.join(value==="instagram"?",":" "));url.searchParams.set("state",state);if(value==="youtube"){url.searchParams.set("access_type","offline");url.searchParams.set("include_granted_scopes","true");url.searchParams.set("prompt","consent");}return url.toString();}
async function discover(value:Provider,accessToken:string){const headers={Authorization:`Bearer ${accessToken}`};if(value==="youtube"){const response=await providerFetch("https://www.googleapis.com/youtube/v3/channels?part=snippet&mine=true",{headers},{allowAuthorization:true});if(!response.ok)return[];return(response.json<{items?:{id:string;snippet?:{title?:string}}[]}>().items??[]).map(item=>({id:item.id,type:"channel" as const,label:item.snippet?.title??"YouTube channel",eligible:true,capabilityRevision:1}));}if(value==="instagram"){const response=await providerFetch("https://graph.instagram.com/me?fields=user_id,username,account_type",{headers},{allowAuthorization:true});if(!response.ok)return[];const item=response.json<{user_id?:string;id?:string;username?:string;account_type?:string}>(),eligible=["BUSINESS","MEDIA_CREATOR","CREATOR"].includes(String(item.account_type??"").toUpperCase());return[{id:String(item.user_id??item.id??""),type:"instagram_account" as const,label:item.username??"Instagram professional account",eligible,capabilityRevision:1,reason:eligible?undefined:"Instagram publishing requires a professional Business or Creator account."}].filter(item=>item.id);}const response=await providerFetch("https://api.linkedin.com/v2/userinfo",{headers},{allowAuthorization:true});if(!response.ok)return[];const item=response.json<{sub?:string;name?:string}>();return item.sub?[{id:`urn:li:person:${item.sub}`,type:"member" as const,label:item.name??"LinkedIn member",eligible:true,capabilityRevision:1}]:[];}

publicationRouter.get("/api/connections",async(req,res)=>res.json(await publicationStorage.listConnections(owner(req))));
publicationRouter.post("/api/connections/:provider/simulate",async(req,res)=>{if(settings.publishMode!=="test")throw notFound();const ownerId=owner(req),value=provider.parse(req.params.provider),body=z.object({scenario:z.enum(["success","processing","failure","reconnect","ambiguous"]).default("success")}).parse(req.body??{}),createdAt=now(),connection:PlatformConnection={id:randomUUID(),ownerId,provider:value,accountId:`simulated:${body.scenario}`,accountLabel:`Simulated ${value} (${body.scenario})`,status:"connected",grantedScopes:["simulated_publish"],targets:[{id:`simulated-${value}-target`,type:value==="youtube"?"channel":value==="instagram"?"instagram_account":"member",label:`Simulated ${value} target`,eligible:true,capabilityRevision:1}],revision:1,createdAt,updatedAt:createdAt,provenance:"test"};res.status(201).json(await publicationStorage.putConnection(connection));});
publicationRouter.post("/api/connections/:id/simulate-reconnect",async(req,res)=>{if(settings.publishMode!=="test")throw notFound();const ownerId=owner(req),id=String(req.params.id),body=z.object({expectedRevision:z.number().int().positive()}).parse(req.body),connection=await publicationStorage.getConnection(ownerId,id);if(connection.revision!==body.expectedRevision)throw new Error("The connection changed. Refresh first.");const updated={...connection,accountId:"simulated:success",accountLabel:`Simulated ${connection.provider} (reauthorized)`,status:"connected" as const,revision:connection.revision+1,updatedAt:now()};res.json(await publicationStorage.putConnection(updated,connection.revision));});
publicationRouter.post("/api/connections/:provider/oauth/start",async(req,res)=>{if(settings.publishMode!=="live")throw Object.assign(new Error("Real OAuth is disabled while PUBLISH_MODE=test."),{status:422});const ownerId=owner(req),value=provider.parse(req.params.provider),body=z.object({returnPath:z.string(),reconnectConnectionId:uuid.optional(),expectedConnectionRevision:z.number().int().positive().optional()}).refine(v=>(v.reconnectConnectionId===undefined)===(v.expectedConnectionRevision===undefined),"Reconnect ID and revision are required together.").parse(req.body),config=oauthConfig(value);if(!config.clientId||!config.secret)throw Object.assign(new Error(`${value} OAuth is not configured.`),{status:503});if(body.reconnectConnectionId){const connection=await publicationStorage.getConnection(ownerId,body.reconnectConnectionId);if(connection.provider!==value||connection.revision!==body.expectedConnectionRevision)throw new Error("The connection changed. Refresh before reconnecting.");}const material=oauthMaterial(),created=Date.now(),record={id:randomUUID(),stateHash:hash(material.state),ownerId,provider:value,initiationId:randomUUID(),returnPath:returnPath(body.returnPath),cookieHash:hash(material.cookie),expiresAt:new Date(created+10*60_000).toISOString(),reconnectConnectionId:body.reconnectConnectionId,expectedConnectionRevision:body.expectedConnectionRevision};await publicationStorage.createOAuthState(record);const secure=!settings.publicOAuthCallbackBaseUrl.startsWith("http://localhost")&&!settings.publicOAuthCallbackBaseUrl.startsWith("http://127.0.0.1");res.set({"Cache-Control":"no-store","Referrer-Policy":"no-referrer"});res.cookie("vpo_oauth",material.cookie,{httpOnly:true,sameSite:"lax",secure,maxAge:10*60_000,path:`/oauth/${value}/callback`});res.json({authorizationUrl:authUrl(value,material.state),initiationId:record.initiationId,expiresAt:record.expiresAt,localDevelopmentCookie:!secure});});
publicationRouter.put("/api/runs/:id/publication-targets/:platform",async(req,res)=>{const ownerId=owner(req),runId=String(req.params.id),platform=destination.parse(req.params.platform),body=z.object({connectionId:uuid,targetId:z.string().min(1),expectedBindingRevision:z.number().int().nonnegative(),expectedPublicationRevision:z.number().int().nonnegative()}).parse(req.body);await storage.getRun(ownerId,runId);const connection=await publicationStorage.getConnection(ownerId,body.connectionId),providerName=providerForDestination(platform),target=connection.targets.find(v=>v.id===body.targetId);if(connection.provider!==providerName||connection.status!=="connected"||!target?.eligible)throw new Error("The selected publishing target is unavailable.");const current=await publicationStorage.getAggregate(ownerId,runId);if(current.revision!==body.expectedPublicationRevision)throw new Error("Publication state changed. Refresh first.");const updated=saveBinding(current,{platform,connectionId:connection.id,targetId:target.id,targetType:target.type,targetLabel:target.label,capabilityRevision:target.capabilityRevision},body.expectedBindingRevision,now());res.json(await publicationStorage.putAggregate(updated,current.revision));});
publicationRouter.get("/api/runs/:id/publications",async(req,res)=>{const ownerId=owner(req),run=await storage.getRun(ownerId,String(req.params.id)),aggregate=await publicationStorage.getAggregate(ownerId,run.id),connections=await publicationStorage.listConnections(ownerId);let confirmationFingerprint:string|undefined,approvalId:string|undefined;try{const approval=activeApproval(run);approvalId=approval.id;confirmationFingerprint=confirmationFor(run,aggregate)("private");}catch{}res.json({publishingMode:settings.publishMode,aiProvenance:run.mode??"unknown",approvalId,approvalFingerprint:approvalId?approvalFingerprint(run):undefined,confirmationFingerprint,connections,aggregate,blockers:connectionBlockers(run,aggregate,connections)});});
publicationRouter.get("/api/runs/:id/publications/jobs/:jobId",async(req,res)=>{const ownerId=owner(req),runId=String(req.params.id);await storage.getRun(ownerId,runId);const aggregate=await publicationStorage.getAggregate(ownerId,runId),job=aggregate.jobs.find(v=>v.id===String(req.params.jobId));if(!job)throw notFound();res.json(job);});
publicationRouter.get("/api/runs/:id/publications/jobs/:jobId/evidence",async(req,res)=>{const ownerId=owner(req),runId=String(req.params.id);await storage.getRun(ownerId,runId);const aggregate=await publicationStorage.getAggregate(ownerId,runId),job=aggregate.jobs.find(v=>v.id===String(req.params.jobId));if(!job)throw notFound();res.json({jobId:job.id,platform:job.platform,state:job.state,checkpoint:job.checkpoint,evidence:job.evidence,attempts:job.attempts,createdAt:job.createdAt,updatedAt:job.updatedAt});});
publicationRouter.post("/api/runs/:id/publications",async(req,res)=>{const ownerId=owner(req),run=await storage.getRun(ownerId,String(req.params.id)),current=await publicationStorage.getAggregate(ownerId,run.id),connections=await publicationStorage.listConnections(ownerId),body=z.object({approvalId:uuid,confirmationFingerprint:z.string().length(64),expectedPublicationRevision:z.number().int().nonnegative(),bindingRevisions:z.record(z.string(),z.number().int().nonnegative()),youtubePrivacy:z.enum(["private","unlisted","public"]).optional(),confirmExternalPublication:z.literal(true)}).parse(req.body);if(current.revision!==body.expectedPublicationRevision)throw new Error("Publication state changed. Refresh first.");const prepared=prepareBatch(run,current,connections,{...body,now:now(),batchId:randomUUID(),intentIds:activeApproval(run).destinations.map(()=>randomUUID()),jobIds:activeApproval(run).destinations.map(()=>randomUUID())});let saved=current,batch=prepared.batch;if(prepared.aggregate!==current){try{saved=await publicationStorage.putAggregate(prepared.aggregate,current.revision);}catch{const latest=await publicationStorage.getAggregate(ownerId,run.id),existing=latest.batches.find(v=>v.confirmationFingerprint===prepared.batch.confirmationFingerprint);if(!existing)throw new Error("Publication state changed. Refresh first.");saved=latest;batch=existing;}}const jobs=saved.jobs.filter(v=>batch.jobIds.includes(v.id));for(const job of jobs)if(job.state==="queued")schedulePublicationJob(ownerId,run.id,job.id);res.status(202).json({batch,jobs,publicationRevision:saved.revision});});
publicationRouter.post("/api/runs/:id/publications/jobs/:jobId/retry",async(req,res)=>{const ownerId=owner(req),runId=String(req.params.id),body=z.object({expectedJobRevision:z.number().int().nonnegative()}).parse(req.body);await storage.getRun(ownerId,runId);res.status(202).json(await retryJob(ownerId,runId,String(req.params.jobId),body.expectedJobRevision));});
publicationRouter.post("/api/runs/:id/publications/jobs/:jobId/reconcile",async(req,res)=>{const ownerId=owner(req),runId=String(req.params.id),body=z.object({expectedJobRevision:z.number().int().nonnegative()}).parse(req.body);await storage.getRun(ownerId,runId);res.status(202).json(await reconcileJob(ownerId,runId,String(req.params.jobId),body.expectedJobRevision));});
publicationRouter.post("/api/runs/:id/publications/retry-failed",async(req,res)=>{const ownerId=owner(req),runId=String(req.params.id),body=z.object({expectedPublicationRevision:z.number().int().nonnegative()}).parse(req.body);await storage.getRun(ownerId,runId);const current=await publicationStorage.getAggregate(ownerId,runId);if(current.revision!==body.expectedPublicationRevision)throw new Error("Publication state changed. Refresh first.");for(const job of current.jobs.filter(v=>v.allowedAction==="retry"&&v.retrySafety==="user_safe"))await retryJob(ownerId,runId,job.id,job.revision);res.status(202).json(await publicationStorage.getAggregate(ownerId,runId));});
publicationRouter.post("/api/connections/:id/refresh",async(req,res)=>{const ownerId=owner(req),id=String(req.params.id),body=z.object({expectedRevision:z.number().int().positive()}).parse(req.body),connection=await publicationStorage.getConnection(ownerId,id);if(connection.revision!==body.expectedRevision)throw new Error("The connection changed. Refresh first.");if(settings.publishMode!=="live")return res.json(connection);const secret=await publicationStorage.getConnectionSecret(ownerId,id),token=(await import("./token-vault.js")).decryptSecret<{accessToken:string}>(secret.envelope,connectionAad(ownerId,connection.provider,id)),targets=await discover(connection.provider,token.accessToken),updated={...connection,targets,status:connection.grantedScopes.length&&hasRequiredScopes(connection.provider,connection.grantedScopes)&&targets.some(v=>v.eligible)?"connected" as const:"needs_attention" as const,revision:connection.revision+1,updatedAt:now()};res.json(await publicationStorage.putConnection(updated,connection.revision));});
publicationRouter.delete("/api/connections/:id",async(req,res)=>{const ownerId=owner(req),id=String(req.params.id),body=z.object({expectedRevision:z.number().int().positive(),confirm:z.literal(true)}).parse(req.body??{}),connection=await publicationStorage.getConnection(ownerId,id);if(connection.revision!==body.expectedRevision)throw new Error("The connection changed. Refresh first.");let disconnectNote=settings.publishMode==="test"?"Simulated authorization removed locally.":"This provider does not expose a verified revocation operation in the configured flow; local authorization was removed.";if(settings.publishMode==="live"&&connection.provider==="youtube"){try{const secret=await publicationStorage.getConnectionSecret(ownerId,id);const token=(await import("./token-vault.js")).decryptSecret<{accessToken:string}>(secret.envelope,connectionAad(ownerId,connection.provider,id)).accessToken,response=await providerFetch("https://oauth2.googleapis.com/revoke",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({token}).toString()},{allowAuthorization:false});disconnectNote=response.ok?"Google authorization was revoked and removed locally.":"Google revocation was not confirmed; local authorization was removed.";}catch{disconnectNote="Google revocation failed; local authorization was removed.";}}await publicationStorage.deleteConnectionSecret(ownerId,id).catch(()=>{});const updated={...connection,status:"disconnected" as const,disconnectNote,revision:connection.revision+1,updatedAt:now()};res.json(await publicationStorage.putConnection(updated,connection.revision));});

oauthCallbackRouter.get("/oauth/:provider/callback",async(req,res)=>{res.set({"Cache-Control":"no-store","Referrer-Policy":"no-referrer"});let target="/?connection=failed";try{if(settings.publishMode!=="live")throw new Error("Real OAuth is disabled.");const value=provider.parse(req.params.provider),state=typeof req.query.state==="string"?req.query.state:"",code=typeof req.query.code==="string"?req.query.code:"",cookie=(req.headers.cookie??"").split(";").map(v=>v.trim()).find(v=>v.startsWith("vpo_oauth="))?.slice(10)??"";if(!state||!code||!cookie)throw new Error("The connection callback is incomplete.");const record=await publicationStorage.consumeOAuthState(hash(state),value,hash(cookie),now()),config=oauthConfig(value),form=new URLSearchParams({grant_type:"authorization_code",code,client_id:config.clientId,client_secret:config.secret,redirect_uri:redirectUri(value)}),response=await providerFetch(config.token,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:form.toString()},{allowAuthorization:false});if(!response.ok)throw new Error("The provider did not authorize this connection.");const token=response.json<Record<string,unknown>>(),accessToken=String(token.access_token??"");if(!accessToken)throw new Error("The provider did not return an access token.");const at=now(),grantedScopes=parseGrantedScopes(token),scopesOkay=hasRequiredScopes(value,grantedScopes),existing=record.reconnectConnectionId?await publicationStorage.getConnection(record.ownerId,record.reconnectConnectionId):undefined;if(existing&&(existing.provider!==value||existing.revision!==record.expectedConnectionRevision))throw new Error("The connection changed during reauthorization.");const targets=scopesOkay?await discover(value,accessToken):[],connection=buildAuthorizedConnection(value,record.ownerId,token,targets,at,existing),connectionId=connection.id;await publicationStorage.putConnectionSecret({ownerId:record.ownerId,connectionId,envelope:encryptSecret({accessToken,refreshToken:token.refresh_token,tokenType:token.token_type,scope:token.scope},connectionAad(record.ownerId,value,connectionId)),updatedAt:at});await publicationStorage.putConnection(connection,existing?.revision);target=`${record.returnPath}${record.returnPath.includes("?")?"&":"?"}${scopesOkay?"connected":"connection_attention"}=${value}`;}catch{target="/?connection=failed";}res.clearCookie("vpo_oauth",{path:`/oauth/${String(req.params.provider)}/callback`,httpOnly:true,sameSite:"lax"});res.redirect(303,target);});
