import { Router } from "express";
import { createHash, randomUUID } from "node:crypto";
import JSZip from "jszip";
import { z } from "zod";
import { owner } from "./auth.js";
import { storage } from "./storage.js";
import { createPackQuote, packSchema } from "./pack.js";
import { startPackJob, isBusy } from "./jobs.js";
import { activeMedia, activePack, appendPack, calculateReadiness, ensureRelease, fingerprint, storyboardLineage, supersedeApproval } from "./release.js";
import { cleanupUpload, probeVideo, receiveUpload, safeFilename } from "./media.js";
import type { ReleaseDestination } from "../../frontend/lib/types.js";

export const releaseRouter = Router();
const uuid = z.string().uuid(), destination = z.enum(["youtube_shorts", "instagram_reels", "linkedin"]);
releaseRouter.post("/api/runs/:id/pack-quotes", async (req, res) => { const b = z.object({ expectedStoryboardLineage: z.string().length(64) }).parse(req.body); res.json(await createPackQuote(owner(req), String(req.params.id), b.expectedStoryboardLineage)); });
releaseRouter.post("/api/runs/:id/pack", async (req, res) => { const b = z.object({ quoteId: uuid, expectedStoryboardLineage: z.string().length(64), expectedReleaseRevision: z.number().int().nonnegative() }).parse(req.body); res.status(202).json(await startPackJob(owner(req), String(req.params.id), b)); });
releaseRouter.patch("/api/runs/:id/pack", async (req, res) => { const b = z.object({ expectedReleaseRevision: z.number().int(), expectedActivePackVersionId: uuid, changeSummary: z.string().trim().min(1).max(500), content: packSchema }).parse(req.body);
  res.status(201).json(await storage.updateRun(owner(req), String(req.params.id), run => { const release = ensureRelease(run); if (isBusy(run) || release.revision !== b.expectedReleaseRevision || release.activePackVersionId !== b.expectedActivePackVersionId) throw new Error("The Pack changed. Refresh and apply your edit again."); const lineage = storyboardLineage(run); if (!lineage) throw new Error("Approve the current Storyboard first."); appendPack(run, b.content, "edited", b.changeSummary, owner(req), lineage); })); });
releaseRouter.post("/api/runs/:id/pack/restore", async (req, res) => { const b = z.object({ sourcePackVersionId: uuid, expectedActivePackVersionId: uuid, expectedReleaseRevision: z.number().int(), changeSummary: z.string().trim().min(1).max(500) }).parse(req.body);
  res.status(201).json(await storage.updateRun(owner(req), String(req.params.id), run => { const release = ensureRelease(run); if (release.revision !== b.expectedReleaseRevision || release.activePackVersionId !== b.expectedActivePackVersionId) throw new Error("The Pack changed. Refresh before restoring."); const prior = release.packVersions.find(v => v.id === b.sourcePackVersionId); if (!prior) throw new Error("That Pack version was not found."); appendPack(run, structuredClone(prior.content), "restored", b.changeSummary, owner(req), prior.storyboardLineage); })); });
releaseRouter.post("/api/runs/:id/final-media", async (req, res) => {
  const ownerId = owner(req), id = String(req.params.id), expectedRevision = Number(req.header("X-VPO-Release-Revision")), expectedLineage = req.header("X-VPO-Storyboard-Lineage") ?? "";
  const initial = await storage.getRun(ownerId, id), release = ensureRelease(initial); if (!Number.isInteger(expectedRevision) || release.revision !== expectedRevision || storyboardLineage(initial) !== expectedLineage) throw new Error("The release changed before upload. Refresh and try again.");
  const upload = await receiveUpload(req); let assetId: string | undefined;
  try { const checked = await probeVideo(upload.filePath, upload.byteSize); if (!checked.validation.valid) throw Object.assign(new Error(checked.validation.blockers.map(x => x.message).join(" ")), { status: 422 });
    const version = release.mediaVersions.length + 1, filename = safeFilename(req.header("X-VPO-Filename") ?? "finished-video.mp4");
    const asset = await storage.saveAssetFromFile(ownerId, id, { filePath: upload.filePath, extension: "mp4", byteSize: upload.byteSize, sha256: upload.sha256, originalFilename: filename, detectedMetadata: checked.probe, validation: checked.validation, mediaVersion: version, purpose: "final-video", mediaType: "video/mp4" }); assetId = asset.id;
    const saved = await storage.updateRun(ownerId, id, run => { const current = ensureRelease(run); if (current.revision !== expectedRevision || storyboardLineage(run) !== expectedLineage) throw new Error("The release changed during upload. Refresh and upload again."); const hadApproval=!!current.activeApprovalId; supersedeApproval(run, "Finished video replaced"); current.revision++; const media = { id: randomUUID(), version, assetId: asset.id, storyboardLineage: expectedLineage, originalSafeFilename: filename, detectedMediaType: "video/mp4" as const, byteSize: upload.byteSize, sha256: upload.sha256, probe: checked.probe, validation: checked.validation, createdAt: new Date().toISOString(), createdBy: ownerId }; current.mediaVersions.push(media); current.activeMediaVersionId = media.id; run.currentStage=hadApproval?"approve":"pack"; run.jobStatus = "needs_review"; calculateReadiness(run); });
    res.status(201).json(saved);
  } catch (e) { if (assetId) await storage.deleteAsset(ownerId, assetId).catch(() => {}); throw e; } finally { await cleanupUpload(upload.dir); }
});
releaseRouter.get("/api/runs/:id/final-media/:versionId/content", async (req, res) => { const ownerId = owner(req), run = await storage.getRun(ownerId, String(req.params.id)), media = ensureRelease(run).mediaVersions.find(v => v.id === String(req.params.versionId)); if (!media) throw Object.assign(new Error("Video was not found."), { status: 404 }); const asset = await storage.openAsset(ownerId, media.assetId); if (asset.record.runId !== run.id) throw Object.assign(new Error("Video was not found."), { status: 404 }); res.set({ "Content-Type": "video/mp4", "Content-Length": String(asset.bytes.length), "Cache-Control": "private, no-store", "X-Content-Type-Options": "nosniff", ...(req.query.download === "1" ? { "Content-Disposition": `attachment; filename="${media.originalSafeFilename.replace(/["\\]/g, "_")}"` } : {}) }).vary("Authorization").send(asset.bytes); });
releaseRouter.put("/api/runs/:id/destinations", async (req, res) => { const b = z.object({ destinations: z.array(destination).min(1), expectedReleaseRevision: z.number().int() }).parse(req.body); res.json(await storage.updateRun(owner(req), String(req.params.id), run => { const release = ensureRelease(run); if (release.revision !== b.expectedReleaseRevision) throw new Error("Destinations changed. Refresh first."); const next = [...new Set(b.destinations)].sort() as ReleaseDestination[]; if (JSON.stringify(next) !== JSON.stringify(release.selectedDestinations)) { const hadApproval=!!release.activeApprovalId; supersedeApproval(run, "Destinations changed"); release.selectedDestinations = next; release.destinationRevision++; release.revision++; if(hadApproval)run.currentStage="approve"; } calculateReadiness(run); })); });
releaseRouter.post("/api/runs/:id/release/review", async (req, res) => { const b = z.object({ expectedReleaseRevision: z.number().int() }).parse(req.body); res.json(await storage.updateRun(owner(req), String(req.params.id), run => { if (ensureRelease(run).revision !== b.expectedReleaseRevision) throw new Error("The release changed. Refresh first."); if (!activePack(run) || !activeMedia(run)) throw new Error("Save a valid Pack and finished video before final review."); run.currentStage = "approve"; calculateReadiness(run); })); });
releaseRouter.get("/api/runs/:id/release-readiness", async (req, res) => res.json(await storage.updateRun(owner(req), String(req.params.id), calculateReadiness)));
releaseRouter.post("/api/runs/:id/approve", async (req, res) => { const b = z.object({ expectedReleaseRevision: z.number().int(), storyboardLineage: z.string().length(64), packVersionId: uuid, mediaVersionId: uuid, mediaSha256: z.string().length(64), destinations: z.array(destination).min(1) }).parse(req.body); res.json(await storage.updateRun(owner(req), String(req.params.id), run => { const release = ensureRelease(run), readiness = calculateReadiness(run), pack = activePack(run), media = activeMedia(run), destinations = [...new Set(b.destinations)].sort();
    if (!readiness.valid || release.revision !== b.expectedReleaseRevision || readiness.storyboardLineage !== b.storyboardLineage || pack?.id !== b.packVersionId || media?.id !== b.mediaVersionId || media.sha256 !== b.mediaSha256 || JSON.stringify(destinations) !== JSON.stringify([...release.selectedDestinations].sort())) throw new Error(`Release is not ready: ${readiness.blockers.map(x => x.message).join(" ") || "versions changed; refresh and review again."}`);
    const readinessFingerprint = fingerprint({ epoch: release.approvalEpoch, lineage: b.storyboardLineage, pack: pack.id, media: media.id, sha256: media.sha256, destinations }); let approval = release.approvals.find(a => a.readinessFingerprint === readinessFingerprint);
    if (!approval) { approval = { id: createHash("sha256").update(readinessFingerprint).digest("hex").slice(0,8)+"-0000-4000-8000-"+createHash("sha256").update(readinessFingerprint).digest("hex").slice(8,20), version: release.approvals.length + 1, ownerId: owner(req), runId: run.id, approvalEpoch: release.approvalEpoch, storyboardLineage: b.storyboardLineage, packVersionId: pack.id, mediaVersionId: media.id, mediaSha256: media.sha256, destinations: destinations as ReleaseDestination[], readinessFingerprint, approvedAt: new Date().toISOString(), approvedBy: owner(req) }; release.approvals.push(approval); }
    release.activeApprovalId = approval.id; run.currentStage = "done"; run.jobStatus = "completed";
  })); });
releaseRouter.post("/api/runs/:id/approval/reopen", async (req, res) => { const b = z.object({ approvalId: uuid, expectedReleaseRevision: z.number().int(), confirmSupersession: z.literal(true) }).parse(req.body); res.json(await storage.updateRun(owner(req), String(req.params.id), run => { const release = ensureRelease(run); if (release.revision !== b.expectedReleaseRevision || release.activeApprovalId !== b.approvalId) throw new Error("Approval changed. Refresh first."); supersedeApproval(run, "Release reopened for editing"); release.revision++; run.currentStage = "pack"; run.jobStatus = "needs_review"; calculateReadiness(run); })); });
async function approvedRun(ownerId: string, id: string, approvalId: string) { const run = await storage.getRun(ownerId, id), release = ensureRelease(run); if (release.activeApprovalId !== approvalId) throw new Error("Only the current approved release can be downloaded."); const approval = release.approvals.find(a => a.id === approvalId), pack = release.packVersions.find(v => v.id === approval?.packVersionId), media = release.mediaVersions.find(v => v.id === approval?.mediaVersionId); if (!approval || !pack || !media || !calculateReadiness(run).valid) throw new Error("The approved release is no longer ready."); return { run, approval, pack, media }; }
releaseRouter.get("/api/runs/:id/approvals/:approvalId/export", async (req, res) => { const item = await approvedRun(owner(req), String(req.params.id), String(req.params.approvalId)), zip = new JSZip(); zip.file("platform-copy.md", `# Platform copy\n\n## YouTube Shorts\n${item.pack.content.platforms.youtube_shorts.title}\n\n${item.pack.content.platforms.youtube_shorts.description}\n\n## Instagram Reels\n${item.pack.content.platforms.instagram_reels.caption}\n\n## LinkedIn\n${item.pack.content.platforms.linkedin.commentary}\n`); zip.file("pack.json", JSON.stringify(item.pack, null, 2)); zip.file("validation-summary.json", JSON.stringify({ pack: item.pack.validation, media: item.media.validation, readiness: item.run.release!.readiness }, null, 2)); zip.file("approval-manifest.json", JSON.stringify({ approval: item.approval, finalMedia: { ...item.media, authenticatedDownloadPath: `/api/runs/${item.run.id}/approvals/${item.approval.id}/video` }, videoIncluded: false, reason: "The MP4 is a separate authenticated download to avoid duplicating up to 100 MB inside the ZIP." }, null, 2)); const data = await zip.generateAsync({ type: "nodebuffer" }); res.set({ "Content-Type": "application/zip", "Content-Disposition": `attachment; filename="approved-${item.run.id}.zip"`, "Cache-Control": "private, no-store" }).vary("Authorization").send(data); });
releaseRouter.get("/api/runs/:id/approvals/:approvalId/video", async (req, res) => { const item = await approvedRun(owner(req), String(req.params.id), String(req.params.approvalId)), asset = await storage.openAsset(owner(req), item.media.assetId); res.set({ "Content-Type": "video/mp4", "Content-Length": String(asset.bytes.length), "Content-Disposition": `attachment; filename="${item.media.originalSafeFilename.replace(/["\\]/g,"_")}"`, "Cache-Control": "private, no-store", "X-Content-Type-Options": "nosniff" }).vary("Authorization").send(asset.bytes); });
