import { Router, type Response } from "express";
import { randomUUID } from "node:crypto";
import { pipeline } from "node:stream/promises";
import JSZip from "jszip";
import { z } from "zod";
import type { FinalMediaVersion, ReleaseApproval, ReleaseDestination } from "../../frontend/lib/types.js";
import { owner } from "./auth.js";
import { storage } from "./storage.js";
import { createPackQuote, packSchema } from "./pack.js";
import { isBusy, startPackJob } from "./jobs.js";
import {
  activeMedia, activePack, applyApproval, applyMediaVersion, applyPackVersion, applyReopen, applySupersession, approvalMatchesActive,
  calculateReadiness, canonicalJson, ensureRelease, preparePackVersion, prepareSupersession,
  readinessFingerprint, RELEASE_POLICY_FINGERPRINT, RELEASE_POLICY_VERSION, storyboardLineage,
} from "./release.js";
import { assertUploadLength, cleanupUpload, probeVideo, receiveUpload, safeFilename } from "./media.js";

export const releaseRouter = Router();
const uuid=z.string().uuid(),destination=z.enum(["youtube_shorts","instagram_reels","linkedin"]),now=()=>new Date().toISOString();
const mediaHeader=(value:string|undefined)=>{if(value===undefined)throw Object.assign(new Error("The active-media version header is required. Refresh and try again."),{status:400});if(value==="none")return undefined;return uuid.parse(value);};
const notFound=()=>Object.assign(new Error("Release item was not found."),{status:404});

releaseRouter.post("/api/runs/:id/pack-quotes",async(req,res)=>{const body=z.object({expectedStoryboardLineage:z.string().length(64)}).parse(req.body);res.json(await createPackQuote(owner(req),String(req.params.id),body.expectedStoryboardLineage));});
releaseRouter.post("/api/runs/:id/pack",async(req,res)=>{const body=z.object({quoteId:uuid,expectedStoryboardLineage:z.string().length(64),expectedReleaseRevision:z.number().int().nonnegative()}).parse(req.body);res.status(202).json(await startPackJob(owner(req),String(req.params.id),body));});

releaseRouter.patch("/api/runs/:id/pack",async(req,res)=>{const ownerId=owner(req),id=String(req.params.id),body=z.object({expectedReleaseRevision:z.number().int(),expectedActivePackVersionId:uuid,changeSummary:z.string().trim().min(1).max(500),content:packSchema}).parse(req.body),before=await storage.getRun(ownerId,id),release=ensureRelease(before);if(isBusy(before)||release.revision!==body.expectedReleaseRevision||release.activePackVersionId!==body.expectedActivePackVersionId)throw new Error("The Pack changed. Refresh and apply your edit again.");const prepared=preparePackVersion(before,body.content,"edited",body.changeSummary,ownerId),supersession=prepareSupersession(before,"Pack edited",prepared.createdAt);res.status(201).json(await storage.updateRun(ownerId,id,run=>{if(isBusy(run))throw new Error("Wait for the active job.");applyPackVersion(run,prepared,body.expectedReleaseRevision,body.expectedActivePackVersionId,supersession);}));});
releaseRouter.post("/api/runs/:id/pack/restore",async(req,res)=>{const ownerId=owner(req),id=String(req.params.id),body=z.object({sourcePackVersionId:uuid,expectedActivePackVersionId:uuid,expectedReleaseRevision:z.number().int(),changeSummary:z.string().trim().min(1).max(500)}).parse(req.body),before=await storage.getRun(ownerId,id),release=ensureRelease(before),prior=release.packVersions.find((item)=>item.id===body.sourcePackVersionId);if(!prior)throw notFound();if(prior.provenance==="legacy_sample")throw new Error("Legacy sample Packs are read-only. Generate a new Pack instead.");const prepared=preparePackVersion(before,prior.content,"restored",body.changeSummary,ownerId,{provenance:prior.provenance}),supersession=prepareSupersession(before,"Pack restored",prepared.createdAt);res.status(201).json(await storage.updateRun(ownerId,id,run=>{applyPackVersion(run,prepared,body.expectedReleaseRevision,body.expectedActivePackVersionId,supersession);}));});

releaseRouter.post("/api/runs/:id/final-media",async(req,res)=>{const ownerId=owner(req),id=String(req.params.id),expectedRevision=Number(req.header("X-VPO-Release-Revision")),expectedLineage=req.header("X-VPO-Storyboard-Lineage")??"",expectedActive=mediaHeader(req.header("X-VPO-Active-Media-Version"));assertUploadLength(req.header("content-length"));const initial=await storage.getRun(ownerId,id),release=ensureRelease(initial);if(!Number.isInteger(expectedRevision)||release.revision!==expectedRevision||storyboardLineage(initial)!==expectedLineage||release.activeMediaVersionId!==expectedActive)throw new Error("The release or active video changed before upload. Refresh and try again.");const upload=await receiveUpload(req);let assetId:string|undefined;try{const checked=await probeVideo(upload.filePath,upload.byteSize);if(!checked.validation.valid)throw Object.assign(new Error(checked.validation.blockers.map((item)=>item.message).join(" ")),{status:422});const createdAt=now(),version=release.mediaVersions.length+1,filename=safeFilename(req.header("X-VPO-Filename")??"finished-video.mp4"),asset=await storage.saveAssetFromFile(ownerId,id,{filePath:upload.filePath,extension:"mp4",byteSize:upload.byteSize,sha256:upload.sha256,originalFilename:filename,detectedMetadata:checked.probe,validation:checked.validation,mediaVersion:version,purpose:"final-video",mediaType:"video/mp4"});assetId=asset.id;const prepared:FinalMediaVersion={id:randomUUID(),version,assetId:asset.id,storyboardLineage:expectedLineage,originalSafeFilename:filename,detectedMediaType:"video/mp4",byteSize:upload.byteSize,sha256:upload.sha256,probe:checked.probe,validation:checked.validation,createdAt,createdBy:ownerId},supersession=prepareSupersession(initial,"Finished video replaced",createdAt);const saved=await storage.updateRun(ownerId,id,run=>{applyMediaVersion(run,prepared,expectedRevision,expectedActive,supersession);});res.status(201).json(saved);}catch(error){if(assetId)await storage.deleteAsset(ownerId,assetId).catch(()=>{});throw error;}finally{await cleanupUpload(upload.dir);}});

async function streamAsset(res:Response,ownerId:string,assetId:string,expectedRunId:string){const asset=await storage.openAsset(ownerId,assetId);if(asset.record.runId!==expectedRunId)throw notFound();await pipeline(asset.stream,res);}
releaseRouter.get("/api/runs/:id/final-media/:versionId/content",async(req,res)=>{const ownerId=owner(req),run=await storage.getRun(ownerId,String(req.params.id)),media=ensureRelease(run).mediaVersions.find((item)=>item.id===String(req.params.versionId));if(!media)throw notFound();res.set({"Content-Type":"video/mp4","Content-Length":String(media.byteSize),"Cache-Control":"private, no-store","X-Content-Type-Options":"nosniff",...(req.query.download==="1"?{"Content-Disposition":`attachment; filename="${media.originalSafeFilename.replace(/["\\]/g,"_")}"`}:{})}).vary("Authorization");await streamAsset(res,ownerId,media.assetId,run.id);});

releaseRouter.put("/api/runs/:id/destinations",async(req,res)=>{const ownerId=owner(req),id=String(req.params.id),body=z.object({destinations:z.array(destination).min(1),expectedReleaseRevision:z.number().int()}).parse(req.body),before=await storage.getRun(ownerId,id),release=ensureRelease(before),destinations=[...new Set(body.destinations)].sort() as ReleaseDestination[];if(canonicalJson(destinations)===canonicalJson(release.selectedDestinations))return res.json(before);const changedAt=now(),supersession=prepareSupersession(before,"Destinations changed",changedAt),nextDestinationRevision=release.destinationRevision+1;res.json(await storage.updateRun(ownerId,id,run=>{const current=ensureRelease(run);if(current.revision!==body.expectedReleaseRevision)throw new Error("Destinations changed. Refresh first.");applySupersession(run,supersession);current.selectedDestinations=[...destinations];current.destinationRevision=nextDestinationRevision;current.revision++;if(supersession)run.currentStage="approve";calculateReadiness(run,changedAt);}));});
releaseRouter.post("/api/runs/:id/release/review",async(req,res)=>{const ownerId=owner(req),id=String(req.params.id),body=z.object({expectedReleaseRevision:z.number().int()}).parse(req.body),checkedAt=now();res.json(await storage.updateRun(ownerId,id,run=>{if(ensureRelease(run).revision!==body.expectedReleaseRevision)throw new Error("The release changed. Refresh first.");if(!activePack(run)||!activeMedia(run))throw new Error("Save a valid Pack and finished video before final review.");run.currentStage="approve";calculateReadiness(run,checkedAt);}));});
releaseRouter.post("/api/runs/:id/release/edit",async(req,res)=>{const ownerId=owner(req),id=String(req.params.id),body=z.object({expectedReleaseRevision:z.number().int()}).parse(req.body);res.json(await storage.updateRun(ownerId,id,run=>{const release=ensureRelease(run);if(release.revision!==body.expectedReleaseRevision)throw new Error("The release changed. Refresh first.");if(release.activeApprovalId)throw new Error("Reopen the active approval before editing.");if(run.currentStage!=="approve")throw new Error("Only a release in final review can return to Pack editing.");run.currentStage="pack";run.jobStatus="needs_review";}));});
releaseRouter.get("/api/runs/:id/release-readiness",async(req,res)=>{const checkedAt=now();res.json(await storage.updateRun(owner(req),String(req.params.id),run=>{calculateReadiness(run,checkedAt);}));});

releaseRouter.post("/api/runs/:id/approve",async(req,res)=>{const ownerId=owner(req),id=String(req.params.id),body=z.object({expectedReleaseRevision:z.number().int(),storyboardLineage:z.string().length(64),packVersionId:uuid,mediaVersionId:uuid,mediaSha256:z.string().length(64),destinations:z.array(destination).min(1)}).parse(req.body),before=await storage.getRun(ownerId,id),checkedAt=now(),release=ensureRelease(before),readiness=calculateReadiness(before,checkedAt),pack=activePack(before),media=activeMedia(before),destinations=[...new Set(body.destinations)].sort() as ReleaseDestination[],fingerprint=readinessFingerprint(before);if(!readiness.valid||release.revision!==body.expectedReleaseRevision||readiness.storyboardLineage!==body.storyboardLineage||pack?.id!==body.packVersionId||media?.id!==body.mediaVersionId||media.sha256!==body.mediaSha256||canonicalJson(destinations)!==canonicalJson([...release.selectedDestinations].sort())||!fingerprint)throw new Error(`Release is not ready: ${readiness.blockers.map((item)=>item.message).join(" ")||"versions changed; refresh and review again."}`);const existing=release.approvals.find((item)=>item.readinessFingerprint===fingerprint);if(existing&&release.activeApprovalId===existing.id&&approvalMatchesActive(before,existing))return res.json(before);const approval:ReleaseApproval=existing??{id:randomUUID(),version:release.approvals.length+1,ownerId,runId:id,approvalEpoch:release.approvalEpoch,storyboardLineage:body.storyboardLineage,packVersionId:pack.id,packProvenance:pack.provenance,policyFingerprint:RELEASE_POLICY_FINGERPRINT,mediaVersionId:media.id,mediaSha256:media.sha256,destinations,readinessFingerprint:fingerprint,approvedAt:checkedAt,approvedBy:ownerId};res.json(await storage.updateRun(ownerId,id,run=>{applyApproval(run,approval,body.expectedReleaseRevision,checkedAt);}));});
releaseRouter.post("/api/runs/:id/approval/reopen",async(req,res)=>{const ownerId=owner(req),id=String(req.params.id),body=z.object({approvalId:uuid,expectedReleaseRevision:z.number().int(),confirmSupersession:z.literal(true)}).parse(req.body),before=await storage.getRun(ownerId,id),reopenedAt=now(),supersession=prepareSupersession(before,"Release reopened for review",reopenedAt);if(!supersession||supersession.approvalId!==body.approvalId)throw new Error("Approval changed. Refresh first.");res.json(await storage.updateRun(ownerId,id,run=>{applyReopen(run,body.approvalId,body.expectedReleaseRevision,supersession,reopenedAt);}));});

async function approvedRun(ownerId:string,id:string,approvalId:string){const run=await storage.getRun(ownerId,id),release=ensureRelease(run),approval=release.approvals.find((item)=>item.id===approvalId);if(release.activeApprovalId!==approvalId||!approval||!approvalMatchesActive(run,approval)||!calculateReadiness(run,run.updatedAt).valid)throw new Error("Only the exact current approved release can be downloaded.");const pack=release.packVersions.find((item)=>item.id===approval.packVersionId),media=release.mediaVersions.find((item)=>item.id===approval.mediaVersionId);if(!pack||!media)throw new Error("The approved release is incomplete.");return{run,approval,pack,media};}
releaseRouter.get("/api/runs/:id/approvals/:approvalId/export",async(req,res)=>{const item=await approvedRun(owner(req),String(req.params.id),String(req.params.approvalId)),zip=new JSZip();zip.file("platform-copy.md",`# Platform copy\n\n## YouTube Shorts\n${item.pack.content.platforms.youtube_shorts.title}\n\n${item.pack.content.platforms.youtube_shorts.description}\n\n## Instagram Reels\n${item.pack.content.platforms.instagram_reels.caption}\n\n## LinkedIn\n${item.pack.content.platforms.linkedin.commentary}\n`);zip.file("pack.json",JSON.stringify(item.pack,null,2));zip.file("validation-summary.json",JSON.stringify({pack:item.pack.validation,media:item.media.validation,readiness:item.run.release!.readiness},null,2));zip.file("approval-manifest.json",JSON.stringify({approval:item.approval,finalMedia:{...item.media,authenticatedDownloadPath:`/api/runs/${item.run.id}/approvals/${item.approval.id}/video`},videoIncluded:false,reason:"The MP4 is a separate authenticated download to avoid duplicating up to 100 MB inside the ZIP."},null,2));const data=await zip.generateAsync({type:"nodebuffer"});res.set({"Content-Type":"application/zip","Content-Disposition":`attachment; filename="approved-${item.run.id}.zip"`,"Cache-Control":"private, no-store","X-Content-Type-Options":"nosniff"}).vary("Authorization").send(data);});
releaseRouter.get("/api/runs/:id/approvals/:approvalId/video",async(req,res)=>{const ownerId=owner(req),item=await approvedRun(ownerId,String(req.params.id),String(req.params.approvalId));res.set({"Content-Type":"video/mp4","Content-Length":String(item.media.byteSize),"Content-Disposition":`attachment; filename="${item.media.originalSafeFilename.replace(/["\\]/g,"_")}"`,"Cache-Control":"private, no-store","X-Content-Type-Options":"nosniff"}).vary("Authorization");await streamAsset(res,ownerId,item.media.assetId,item.run.id);});
