"use client";
import { useState } from "react";
import type { ReleaseDestination, Run } from "@/lib/types";
import { fetchDownload, saveDestinations } from "@/lib/api";
import { downloadBlob } from "@/lib/export";
const labels:Record<ReleaseDestination,string>={youtube_shorts:"YouTube Shorts",instagram_reels:"Instagram Reels",linkedin:"LinkedIn"};
const canonical=(values:ReleaseDestination[])=>JSON.stringify([...values].sort());
export default function ApprovePanel({run,busy,onApprove,onReopen,onEdit,onUpdate,saveDestinationsRequest=saveDestinations,downloadRequest=fetchDownload,download=downloadBlob,confirmReopen=(message)=>window.confirm(message)}:{run:Run;busy:boolean;onApprove:()=>Promise<void>;onReopen:()=>Promise<void>;onEdit:()=>Promise<void>;onUpdate:(run:Run)=>void;saveDestinationsRequest?:(runId:string,destinations:ReleaseDestination[],revision:number)=>Promise<Run>;downloadRequest?:(path:string)=>Promise<Blob>;download?:(blob:Blob,name:string)=>void;confirmReopen?:(message:string)=>boolean}){
  const release=run.release!,pack=release.packVersions.find((version)=>version.id===release.activePackVersionId),media=release.mediaVersions.find((version)=>version.id===release.activeMediaVersionId),approval=release.approvals.find((item)=>item.id===release.activeApprovalId),[selected,setSelected]=useState<ReleaseDestination[]>(release.selectedDestinations),[error,setError]=useState(""),destinationsDirty=canonical(selected)!==canonical(release.selectedDestinations);
  async function save(){setError("");try{onUpdate(await saveDestinationsRequest(run.id,selected,release.revision));}catch(cause){setError((cause as Error).message);}}
  async function downloadFile(path:string,name:string){try{download(await downloadRequest(path),name);}catch(cause){setError((cause as Error).message);}}
  async function reopen(){if(!approval)return;if(confirmReopen(`Reopen this release? Approval ${approval.id} will be superseded, but its Pack, media and audit record will be preserved.`))await onReopen();}
  return <section className="rounded-2xl border border-border bg-surface p-5 sm:p-6 space-y-5 min-w-0"><div><h2 className="text-lg font-semibold">Final review</h2><p className="text-sm text-muted">Approval binds these exact versions. It does not publish.</p></div><div className="grid gap-3 sm:grid-cols-2"><p>Pack <strong>v{pack?.version}</strong> · {pack?.provenance.toUpperCase()}</p><p>Video <strong>v{media?.version}</strong> · {media?.originalSafeFilename}</p></div>{media&&<p className="text-xs break-all text-muted">SHA-256 {media.sha256}</p>}
  <fieldset><legend className="font-semibold mb-2">Destinations</legend><div className="flex flex-wrap gap-4">{(Object.keys(labels) as ReleaseDestination[]).map((destination)=><label className="min-h-11 flex items-center gap-2" key={destination}><input type="checkbox" checked={selected.includes(destination)} onChange={(event)=>setSelected(event.target.checked?[...selected,destination]:selected.filter((item)=>item!==destination))}/>{labels[destination]}</label>)}</div><button className="rounded-lg border border-border px-4 py-2" disabled={busy||!selected.length||!destinationsDirty} onClick={()=>void save()}>Save destinations</button>{destinationsDirty&&<p role="alert" className="mt-2 text-sm text-warning">Save destination changes before approval. The server will approve only the saved set.</p>}</fieldset>
  <div><h3 className="font-semibold">Release readiness</h3>{release.readiness.blockers.length?release.readiness.blockers.map((item)=><p role="alert" className="text-warning mt-2" key={item.code}>{item.message}{item.nextAction?` ${item.nextAction}`:""}</p>):<p className="text-success mt-2">Ready for exact-version approval.</p>}{release.readiness.warnings.map((item)=><p className="text-muted text-sm mt-2" key={item.code}>Warning: {item.message}</p>)}</div>{error&&<p role="alert" className="text-warning">{error}</p>}
  {!approval?<div className="flex flex-wrap gap-3"><button className="rounded-lg bg-accent px-4 py-3 font-medium" disabled={busy||destinationsDirty||!release.readiness.valid} onClick={()=>void onApprove()}>Approve this release candidate</button><button className="rounded-lg border border-border px-4 py-3" disabled={busy} onClick={()=>void onEdit()}>Return to Pack editing</button></div>:<div className="space-y-4"><div className="rounded-lg border border-success/30 bg-success/10 p-3 text-success"><strong>Approved</strong><p className="text-sm break-all">{approval.id} · {new Date(approval.approvedAt).toLocaleString()}</p><p className="text-sm">Pack v{pack?.version} · video v{media?.version} · {approval.destinations.map((destination)=>labels[destination]).join(", ")}</p></div><div className="flex flex-wrap gap-3"><button className="rounded-lg bg-accent px-4 py-3" onClick={()=>void downloadFile(`/api/runs/${run.id}/approvals/${approval.id}/export`,"approved-pack.zip")}>Download approved pack</button><button className="rounded-lg border border-border px-4 py-3" onClick={()=>void downloadFile(`/api/runs/${run.id}/approvals/${approval.id}/video`,media?.originalSafeFilename??"finished-video.mp4")}>Download approved MP4</button><button className="rounded-lg border border-warning px-4 py-3" disabled={busy} onClick={()=>void reopen()}>Reopen for review</button></div></div>}</section>;
}
