"use client";
import { useState } from "react";
import type { ReleasePackContent, Run } from "@/lib/types";
import { fetchDownload, isSampleMode, uploadFinalMedia } from "@/lib/api";
import { downloadBlob } from "@/lib/export";
import ProtectedVideo from "@/components/ProtectedVideo";

const field="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm";
const same=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
export default function PackPanel({run,busy,onSave,onRestore,onContinue,onUpdate,uploadRequest=uploadFinalMedia,downloadRequest=fetchDownload,download=downloadBlob,confirmDiscard=(message)=>window.confirm(message),standaloneSample=isSampleMode()}:{run:Run;busy:boolean;onSave:(content:ReleasePackContent)=>Promise<void>;onRestore:(sourcePackVersionId:string)=>Promise<void>;onContinue:()=>Promise<void>;onUpdate:(run:Run)=>void;uploadRequest?:(run:Run,file:File,progress:(value:number)=>void)=>Promise<Run>;downloadRequest?:(path:string)=>Promise<Blob>;download?:(blob:Blob,name:string)=>void;confirmDiscard?:(message:string)=>boolean;standaloneSample?:boolean}){
  const release=run.release,active=release?.packVersions.find((version)=>version.id===release.activePackVersionId),media=release?.mediaVersions.find((version)=>version.id===release.activeMediaVersionId);
  const[draft,setDraft]=useState<ReleasePackContent|null>(active?structuredClone(active.content):null),[progress,setProgress]=useState<number|null>(null),[error,setError]=useState("");
  if(!release||!active||!draft)return null;const dirty=!same(draft,active.content);
  const setPlatform=(name:keyof ReleasePackContent["platforms"],key:string,value:string)=>setDraft({...draft,platforms:{...draft.platforms,[name]:{...draft.platforms[name],[key]:value}}});
  async function saveDraft(){if(!draft)return;setError("");try{await onSave(draft);}catch(cause){setError((cause as Error).message);}}
  async function upload(file?:File){if(!file)return;setError("");setProgress(0);try{onUpdate(await uploadRequest(run,file,setProgress));}catch(cause){setError((cause as Error).message);}finally{setProgress(null);}}
  async function restore(id:string){if(dirty&&!confirmDiscard("Restore this prior Pack as a new version? Your unsaved edits will remain on this screen until the server confirms the restore, but they will not be saved."))return;await onRestore(id);}
  async function downloadMedia(){if(!media)return;setError("");try{download(await downloadRequest(`/api/runs/${run.id}/final-media/${media.id}/content?download=1`),media.originalSafeFilename);}catch(cause){setError((cause as Error).message);}}
  return <div className="space-y-6"><section className="rounded-2xl border border-border bg-surface p-5 sm:p-6 space-y-4 min-w-0">
    <div><h2 className="text-lg font-semibold">Pack · version {active.version}</h2><p className="text-sm text-muted">{active.origin} · {active.provenance.toUpperCase()} · {active.changeSummary}</p></div>{active.validation.blockers.map((item)=><p role="alert" className="text-warning" key={item.code}>{item.message}</p>)}{dirty&&<p role="status" className="text-warning">Unsaved Pack changes</p>}
    <label>Final video prompt<textarea className={`${field} min-h-28`} value={draft.finalPrompt} onChange={(event)=>setDraft({...draft,finalPrompt:event.target.value})}/></label><label>Negative prompt<textarea className={`${field} min-h-20`} value={draft.negativePrompt} onChange={(event)=>setDraft({...draft,negativePrompt:event.target.value})}/></label><label>Thumbnail text<input className={field} value={draft.thumbnailText} onChange={(event)=>setDraft({...draft,thumbnailText:event.target.value})}/></label>
    <div className="grid gap-5 lg:grid-cols-3"><fieldset className="space-y-3 min-w-0"><legend className="font-semibold">YouTube Shorts</legend><input aria-label="YouTube title" className={field} value={draft.platforms.youtube_shorts.title} onChange={(event)=>setPlatform("youtube_shorts","title",event.target.value)}/><textarea aria-label="YouTube description" className={`${field} min-h-32`} value={draft.platforms.youtube_shorts.description} onChange={(event)=>setPlatform("youtube_shorts","description",event.target.value)}/><input aria-label="YouTube tags" className={field} value={draft.platforms.youtube_shorts.tags.join(", ")} onChange={(event)=>setDraft({...draft,platforms:{...draft.platforms,youtube_shorts:{...draft.platforms.youtube_shorts,tags:event.target.value.split(",").map((item)=>item.trim()).filter(Boolean)}}})}/><textarea aria-label="YouTube accessibility notes" className={field} value={draft.platforms.youtube_shorts.accessibilityNotes} onChange={(event)=>setPlatform("youtube_shorts","accessibilityNotes",event.target.value)}/><textarea aria-label="YouTube posting notes" className={field} value={draft.platforms.youtube_shorts.postingNotes} onChange={(event)=>setPlatform("youtube_shorts","postingNotes",event.target.value)}/></fieldset>
    <fieldset className="space-y-3 min-w-0"><legend className="font-semibold">Instagram Reels</legend><textarea aria-label="Instagram caption" className={`${field} min-h-32`} value={draft.platforms.instagram_reels.caption} onChange={(event)=>setPlatform("instagram_reels","caption",event.target.value)}/><input aria-label="Instagram hashtags" className={field} value={draft.platforms.instagram_reels.hashtags.join(" ")} onChange={(event)=>setDraft({...draft,platforms:{...draft.platforms,instagram_reels:{...draft.platforms.instagram_reels,hashtags:event.target.value.split(/\s+/).filter(Boolean)}}})}/><textarea aria-label="Instagram alt text" className={field} value={draft.platforms.instagram_reels.altText} onChange={(event)=>setPlatform("instagram_reels","altText",event.target.value)}/><textarea aria-label="Instagram posting notes" className={field} value={draft.platforms.instagram_reels.postingNotes} onChange={(event)=>setPlatform("instagram_reels","postingNotes",event.target.value)}/></fieldset>
    <fieldset className="space-y-3 min-w-0"><legend className="font-semibold">LinkedIn</legend><input aria-label="LinkedIn title" className={field} value={draft.platforms.linkedin.title} onChange={(event)=>setPlatform("linkedin","title",event.target.value)}/><textarea aria-label="LinkedIn commentary" className={`${field} min-h-32`} value={draft.platforms.linkedin.commentary} onChange={(event)=>setPlatform("linkedin","commentary",event.target.value)}/><input aria-label="LinkedIn hashtags" className={field} value={draft.platforms.linkedin.hashtags.join(" ")} onChange={(event)=>setDraft({...draft,platforms:{...draft.platforms,linkedin:{...draft.platforms.linkedin,hashtags:event.target.value.split(/\s+/).filter(Boolean)}}})}/><textarea aria-label="LinkedIn accessibility notes" className={field} value={draft.platforms.linkedin.accessibilityNotes} onChange={(event)=>setPlatform("linkedin","accessibilityNotes",event.target.value)}/><textarea aria-label="LinkedIn posting notes" className={field} value={draft.platforms.linkedin.postingNotes} onChange={(event)=>setPlatform("linkedin","postingNotes",event.target.value)}/></fieldset></div>
    <button className="rounded-lg bg-accent px-4 py-3 font-medium" disabled={standaloneSample||busy||!dirty} onClick={()=>void saveDraft()}>Save as new Pack version</button>{error&&<p role="alert" className="text-warning">{error}</p>}
    <details><summary className="cursor-pointer">Pack history ({release.packVersions.length})</summary><div className="divide-y divide-border">{[...release.packVersions].reverse().map((version)=><details className="py-3" key={version.id}><summary className="cursor-pointer">v{version.version} · {version.origin} · {version.provenance.toUpperCase()} · {version.changeSummary}</summary><div className="mt-2 space-y-2 text-sm"><p>By {version.createdBy} · {new Date(version.createdAt).toLocaleString()}</p><p>{version.validation.valid?"Validation passed":`${version.validation.blockers.length} blocker(s)`} · policy {version.validation.policyVersion}</p><pre className="max-h-64 overflow-auto whitespace-pre-wrap rounded bg-background p-3">{JSON.stringify(version.content,null,2)}</pre>{version.id!==active.id&&<button className="rounded-lg border border-border px-3 py-2 font-medium" disabled={standaloneSample||busy} onClick={()=>void restore(version.id)}>Restore as new version</button>}</div></details>)}</div></details></section>
    <section className="rounded-2xl border border-border bg-surface p-5 sm:p-6 space-y-4"><h2 className="text-lg font-semibold">Finished video</h2><p className="text-sm text-muted">Select one MP4. H.264 · optional AAC · 15–60 seconds · 1080×1920 or 720×1280 · up to 100 MB.</p>{standaloneSample&&<p className="text-sm text-warning">Connect the backend to validate and privately store a finished video. Standalone sample data cannot be approved.</p>}<label className="block rounded-xl border border-dashed border-border p-5">Select one MP4<input aria-label="Select finished MP4" className="mt-3 block max-w-full" type="file" accept="video/mp4" disabled={standaloneSample||busy||progress!==null} onChange={(event)=>{void upload(event.target.files?.[0]);event.target.value="";}}/></label>{progress!==null&&<div role="status"><progress className="w-full" max={100} value={progress}/><p>{progress<100?`Uploading ${progress}%`:"Validating and saving privately…"}</p></div>}{media&&<div className="space-y-3"><p><strong>{media.originalSafeFilename}</strong> · {(media.byteSize/1048576).toFixed(1)} MB · {media.probe.durationSeconds.toFixed(2)}s · {media.probe.displayWidth}×{media.probe.displayHeight} · {media.probe.videoCodec}{media.probe.audioCodecs.length?` / ${media.probe.audioCodecs.join(", ")}`:" / no audio"}</p>{media.validation.warnings.map((item)=><p className="text-sm text-warning" key={item.code}>Warning: {item.message}</p>)}<p className="text-xs break-all text-muted">SHA-256 {media.sha256}</p><ProtectedVideo src={`/api/runs/${run.id}/final-media/${media.id}/content`} className="max-h-[520px] w-full bg-black"/><button className="rounded-lg border border-border px-4 py-2" onClick={()=>void downloadMedia()}>Download current authenticated MP4</button></div>}<button className="rounded-lg bg-accent px-4 py-3 font-medium" disabled={busy||dirty||!media||!active.validation.valid} onClick={()=>void onContinue()}>Continue to final review</button></section></div>;
}
